import type { HelpCatalog } from "./types";

const en: HelpCatalog = {
  "page.dashboard": {
    title: "Dashboard",
    summary: "KPIs plus interactive sales charts filtered by date range.",
    what: "Shows today's sales, cash position, low-stock alerts, pending approvals, and revenue/order trends for a selected date range so owners and managers can decide what to do next.",
    how: [
      "After sign-in, review today's KPI cards.",
      "Set the from/to dates to refresh revenue and order charts.",
      "Hover a chart point for the daily total or ticket count.",
      "Use low-stock or approval cards to jump to Inventory or Returns.",
      "Switch business or branch from the header when you manage multiple locations.",
    ],
    when: "At shift start, end of day, or whenever you need a health check on the branch.",
    tips: [
      "Charts use completed sales for the selected business (RPT-FR-001).",
      "If charts look empty, widen the date range or confirm till activity.",
    ],
  },
  "page.pos": {
    title: "Point of Sale",
    summary: "Fast checkout with cart, customer, and payment.",
    what: "Cashiers can sell products, attach customers for loyalty or credit (credit), apply discounts or coupons, and take payment by cash, card, wallet, or credit.",
    how: [
      "Open a till before taking cash sales.",
      "Add products to the cart by search or barcode scan.",
      "Attach a customer when needed for loyalty or credit.",
      "Review the total, tap Proceed to checkout, and choose a payment method.",
      "Complete the order with Place order, then print or share the receipt.",
    ],
    when: "For every customer checkout at the counter.",
    tips: [
      "Credit payment requires an active credit on the customer.",
      "Keep the till open during the shift and count cash before closing at end of day.",
    ],
  },
  "page.inventory": {
    title: "Inventory & Purchasing",
    summary: "Catalog, on-hand stock, suppliers, purchase orders, transfers, and adjustments.",
    what: "The place to maintain products, view stock levels, buy from suppliers, move stock between branches, and correct quantities.",
    how: [
      "Create or update SKUs and prices from Products.",
      "View on-hand quantity and average cost from Stock.",
      "Add suppliers, then create purchase orders and receive goods (GRN).",
      "Use Transfers to move stock between branches and Adjust to fix quantities.",
    ],
    when: "When receiving goods, adding new items, doing a stock count, or transferring between branches.",
    tips: [
      "Receive against a PO so cost and accounts payable stay accurate.",
      "Use a clear reason code in Adjust for audit trails.",
    ],
  },
  "page.inventory.supplier": {
    title: "Supplier detail",
    summary: "Contact, terms, and products linked for purchase orders.",
    what: "Each supplier record stores company and contact details plus an explicit list of catalog products they can supply. Only linked products appear when raising a PO for that supplier (INV-FR).",
    how: [
      "Open a supplier from Inventory → Suppliers.",
      "Review contact, address, and payment terms.",
      "Attach catalog products this supplier fulfills.",
      "Detach products the supplier no longer carries.",
      "Create purchase orders from Inventory → Purchase orders using linked products only.",
    ],
    when: "When onboarding a vendor, updating who supplies which SKUs, or before raising a PO.",
    tips: [
      "Link products before creating POs — the API rejects lines for unlinked SKUs.",
      "Receive goods (GRN) against the PO so stock and average cost stay accurate.",
    ],
  },
  "page.customers": {
    title: "Customers & Credit",
    summary: "Customer profiles, credit/credit balance, ledger, and loyalty points.",
    what: "Stores customer details and lets you enable credit, view the ledger, manage credit limits, and adjust loyalty points.",
    how: [
      "Add a customer with name and phone.",
      "Enable credit for credit sales.",
      "Open Ledger to see debits, credits, and outstanding balance.",
      "Adjust loyalty points for promotions or corrections.",
    ],
    when: "For CRM, credit sales, and loyalty programs.",
    tips: [
      "Attach the customer at POS before credit payment.",
      "Check credit limit before large credit sales.",
    ],
  },
  "page.sales": {
    title: "Sales History",
    summary: "Full list of sales invoices for the selected branch.",
    what: "Shows past checkouts with invoice number, customer, total, status, and time so you can reopen or verify a sale.",
    how: [
      "Search or browse the sales list.",
      "Open a row to view line items and payments.",
      "Use the invoice number when processing a return.",
    ],
    when: "For customer inquiries, audits, reprinting receipts, or before a return.",
    tips: ["Sales appear after a successful POS checkout."],
  },
  "page.returns": {
    title: "Returns & Tills",
    summary: "Refunds on past sales and till open/close history.",
    what: "Staff can look up a sale and submit a return, and view till sessions including over/short amounts.",
    how: [
      "Search by the original sale invoice number.",
      "Submit the return with refund method and reason.",
      "Managers approve or reject pending returns.",
      "Review opening/closing cash and variance in till history.",
    ],
    when: "When issuing refunds, handling damaged goods, or reconciling tills.",
    tips: ["Keep the original invoice—returns link back to that sale."],
  },
  "page.accounting": {
    title: "Accounting",
    summary: "IFRS-for-SMEs books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools aligned with IFRS for SMEs presentation: chart of accounts (create/edit), journals, trial balance, sectioned P&L and balance sheet, cash flow, general ledger, and receivables/payables aging.",
    how: [
      "Create or edit ledger accounts on Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, Cash flow, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Header accounts are for structure only—post to leaf accounts.",
    ],
  },
  "page.hr": {
    title: "HR & Payroll",
    summary: "Employees, attendance, leave, and payroll runs.",
    what: "Manages staff master data, attendance, leave requests, and payroll calculation and approval.",
    how: [
      "Add employees or invite existing users.",
      "Record attendance and review leave requests.",
      "Run payroll for a period, then approve it.",
    ],
    when: "For hiring, daily attendance, leave approval, and salary cycles.",
    tips: ["Payroll approval may require a specific role or bundle."],
  },
  "page.marketing": {
    title: "Marketing",
    summary: "Campaigns, message templates, segments, coupons, and loyalty tiers.",
    what: "Helps you message customers with reusable templates, target segments, set up promo codes, and configure loyalty earn/redeem rates.",
    how: [
      "Create a draft campaign with audience and message.",
      "Reuse templates with {{placeholders}} for consistent copy.",
      "Send when ready—delivery status appears on the campaign.",
      "Build segments and coupons for targeted offers.",
      "Set loyalty tiers based on points bands.",
    ],
    when: "For promotions, festival offers, win-back messages, and loyalty setup.",
    tips: ["Connect customer channels for better delivery."],
  },
  "page.reports": {
    title: "Reports",
    summary: "Operational sales and product performance.",
    what: "Branch reports such as daily sales and top products. Full financial statements live under Accounting.",
    how: [
      "Choose a date range.",
      "Review daily sales and ticket counts.",
      "Check best-selling products by quantity.",
    ],
    when: "For weekly reviews, merchandising decisions, or owner updates.",
    tips: ["Open Accounting for P&L or balance sheet."],
  },
  "page.settings": {
    title: "Settings",
    summary: "Profile, plan limits, billing, notifications, FBR flags, and roles.",
    what: "Business and account configuration: profile, subscription usage, notification preferences, integrations, and role access (some tabs are owner-only).",
    how: [
      "Update your profile under the Profile tab.",
      "Review usage against plan limits and upgrade from plan cards.",
      "Owners can manage integrations, branding, and roles for the active business.",
    ],
    when: "During onboarding, plan upgrades, or when changing module access.",
    tips: ["Some settings are owner-only—ask the owner if a tab is missing."],
  },
  "page.businesses": {
    title: "Businesses",
    summary: "Create and manage businesses under your owner account.",
    what: "Owner list of businesses with create, open detail, and soft-deactivate.",
    how: [
      "Create a business with name and industry.",
      "Open a business to edit details, branches, and branding.",
      "Deactivate when a location closes—history is retained.",
    ],
    when: "When expanding to a new brand or shutting down a business.",
    tips: ["Plan limits apply to how many businesses and branches you can add."],
  },
  "page.notifications": {
    title: "Notifications",
    summary: "Leave, payroll, billing, and campaign alerts.",
    what: "System and workflow alerts so approvals and campaign results are not missed.",
    how: [
      "Open Notifications to see unread items.",
      "Click a linked alert to go to the related screen.",
      "Adjust preferences in Settings if alerts are too noisy.",
    ],
    when: "Throughout the day for approvals and operational updates.",
    tips: ["Keep the panel open on busy days so leave and payroll requests stay visible."],
  },
  "page.profile": {
    title: "Your Profile",
    summary: "Personal name, phone, password, and photo.",
    what: "Updates your user account—not full business settings.",
    how: [
      "Change display name and phone.",
      "Set a new password only when you need to change it.",
      "Upload a profile photo when available.",
    ],
    when: "On first login setup or when updating personal details.",
    tips: ["Change language from the sidebar language control."],
  },
  "page.businessDetail": {
    title: "Business detail",
    summary: "Edit one business: branding, marketplace, and branches.",
    what: "Owner tools for a single business identity and locations.",
    how: [
      "Update name, industry, tagline, and brand color.",
      "Upload a logo and configure marketplace listing.",
      "Add or deactivate branches as needed.",
    ],
    when: "When launching a store or refreshing brand look.",
    tips: ["Deactivating keeps historical financial data; nothing is hard-deleted."],
  },
  "page.ess": {
    title: "Staff Tools (ESS)",
    summary: "Employee self-service for attendance and leave.",
    what: "Staff can check in/out and submit leave without full HR admin access.",
    how: [
      "Mark today's attendance.",
      "Submit leave with dates and reason.",
      "Check approval status after submitting.",
    ],
    when: "Daily for staff using self-service HR.",
    tips: ["Managers still approve leave from the HR Leave tab."],
  },

  "tab.inventory.stock": {
    title: "On-hand Stock",
    summary: "Quantity and average cost for each product at this branch.",
    what: "Inventory balance view after purchases, sales, transfers, and adjustments.",
    how: [
      "Search by SKU or product name.",
      "Review quantity before reordering.",
      "Compare with Products if something looks wrong.",
    ],
    when: "Before placing orders, spot checks, or investigating shortages.",
    tips: ["Average cost updates when goods are received."],
  },
  "tab.inventory.products": {
    title: "Products",
    summary: "Sale items, services, prices, and barcodes.",
    what: "Create and edit products used in POS and stock tracking.",
    how: [
      "Add a product with SKU, name, and price.",
      "Set a barcode for scanning at checkout.",
      "Open a product to view or edit details.",
    ],
    when: "When adding new items or updating prices.",
    tips: ["Keep SKUs unique across the business."],
  },
  "tab.inventory.suppliers": {
    title: "Suppliers",
    summary: "Vendor master for purchasing.",
    what: "Supplier contact, payment terms, and status used on purchase orders.",
    how: [
      "Add a supplier with name and contact details.",
      "Set payment terms before creating a PO.",
      "Open a supplier to view full details.",
    ],
    when: "When setting up purchasing or updating vendor details.",
    tips: ["Do not use inactive suppliers on new POs."],
  },
  "tab.inventory.pos": {
    title: "Purchase Orders",
    summary: "Supplier orders and goods receipt (GRN).",
    what: "Create POs, track status, and receive quantities into stock.",
    how: [
      "Create a PO with supplier and line items.",
      "Receive goods against the PO when stock arrives (GRN).",
      "Open a PO to review lines and status.",
    ],
    when: "When reordering stock from a supplier.",
    tips: ["Receive only what arrived—partial receipts are supported."],
  },
  "tab.inventory.transfers": {
    title: "Transfers",
    summary: "Move stock between branches.",
    what: "Creates a transfer document that must be confirmed so stock moves from one branch to another.",
    how: [
      "Choose destination branch, product, and quantity.",
      "Create the transfer and confirm once goods are moved.",
    ],
    when: "When balancing stock across locations.",
    tips: ["Confirm promptly so on-hand quantities stay accurate."],
  },
  "tab.inventory.adjust": {
    title: "Stock Adjustment",
    summary: "Correct quantity for damage, count variance, or write-offs.",
    what: "Changes quantity (+/−) with a reason code for audit.",
    how: [
      "Choose product and quantity delta.",
      "Select a reason code.",
      "Save to update on-hand stock.",
    ],
    when: "After a physical count or when goods are damaged or lost.",
    tips: ["Prefer GRN/transfers for normal movement; use Adjust for corrections."],
  },

  "tab.accounting.coa": {
    title: "Chart of Accounts",
    summary: "IFRS-for-SMEs ledger accounts for journals and statements.",
    what: "Hierarchical list of account codes with type, classification, and normal balance. Create new accounts or edit existing ones.",
    how: [
      "Use New account to add a postable or header account.",
      "Browse by code; indent shows parent hierarchy.",
      "Edit an account to change labels or classification.",
    ],
    when: "During setup review or when you need a new ledger account.",
    tips: [
      "Do not delete accounts that already have postings.",
    ],
  },
  "tab.accounting.journals": {
    title: "Journals",
    summary: "Manual and system journal entries.",
    what: "Shows posted journals and lets you post balanced manual entries.",
    how: [
      "Open a journal to view debit/credit lines.",
      "Use Post journal for a two-line adjustment when needed.",
    ],
    when: "For corrections, accruals, or reviewing auto-posted entries.",
    tips: ["Debits must equal credits before posting."],
  },
  "tab.accounting.tb": {
    title: "Trial Balance",
    summary: "Account-wise debit/credit totals for a period.",
    what: "Verifies books are balanced before running statements.",
    how: ["Set From/To dates.", "Review account totals."],
    when: "At month-end or before P&L / balance sheet.",
    tips: ["Investigate unexpectedly large balances."],
  },
  "tab.accounting.pl": {
    title: "Profit & Loss",
    summary: "Sectioned income statement (IFRS for SMEs).",
    what: "Revenue, cost of sales, operating expenses, and net income for the selected period.",
    how: [
      "Choose dates.",
      "Review sections and subtotals (gross / operating / net).",
    ],
    when: "For owner review and period close.",
    tips: [
      "Accuracy depends on correct account classifications and postings.",
    ],
  },
  "tab.accounting.bs": {
    title: "Balance Sheet",
    summary: "Sectioned statement of financial position.",
    what: "Current and non-current assets/liabilities plus equity as of the report date.",
    how: [
      "Set the as-of date.",
      "Review current vs non-current sections.",
    ],
    when: "For period close and financial discussions.",
    tips: [
      "AR/AP aging complements customer and supplier balances.",
    ],
  },
  "tab.accounting.cf": {
    title: "Cash Flow",
    summary: "Indirect cash flow summary for a period.",
    what: "Starts from net income and adjusts for working-capital changes (AR, inventory, AP).",
    how: [
      "Choose dates.",
      "Review cash from operations.",
    ],
    when: "For cash planning alongside P&L and balance sheet.",
    tips: [
      "This is a simplified indirect method—not a full IAS 7 statement.",
    ],
  },

  "tab.accounting.gl": {
    title: "General Ledger",
    summary: "Line-by-line activity for one account.",
    what: "Debit/credit history for a single account.",
    how: ["Select an account.", "Set dates.", "Review each posting."],
    when: "When investigating balances or reconciling an account.",
    tips: ["Run trial balance first, then open GL for odd accounts."],
  },
  "tab.accounting.ar": {
    title: "AR Aging",
    summary: "Customer receivables by age bucket.",
    what: "Open invoice balances grouped by age (current, 30, 60 days, etc.).",
    how: ["Review buckets.", "Open an invoice for details.", "Follow up with the customer."],
    when: "For collections and credit control.",
    tips: ["Credit/credit sales may appear in AR."],
  },
  "tab.accounting.ap": {
    title: "AP Aging",
    summary: "Supplier payables by age bucket.",
    what: "Bills you owe, grouped by due date.",
    how: ["Review buckets.", "Open a bill for details.", "Plan supplier payments."],
    when: "For supplier payment and cash planning.",
    tips: ["PO receipts often create AP bills."],
  },

  "tab.hr.employees": {
    title: "Employees",
    summary: "Staff master list and employment details.",
    what: "Create employee records, edit base salary, and open profiles.",
    how: [
      "Add an employee or invite an existing user.",
      "Edit title, salary, and status.",
      "Open an employee for full details.",
    ],
    when: "For hiring, role changes, or salary updates.",
    tips: ["Invite links the HR record to login access."],
  },
  "tab.hr.attendance": {
    title: "Attendance",
    summary: "Check-in / check-out history.",
    what: "Attendance rows for payroll and compliance.",
    how: ["Filter by date.", "Fix missing punches via ESS or a manager."],
    when: "For daily operations and before payroll.",
    tips: ["Source may be ESS or manager entry."],
  },
  "tab.hr.leave": {
    title: "Leave",
    summary: "Leave requests and approvals.",
    what: "Managers approve or reject leave based on role permissions.",
    how: [
      "Review pending requests.",
      "Approve or reject carefully.",
      "Confirm dates with the employee if unclear.",
    ],
    when: "When staff request time off.",
    tips: ["Approval depends on leave_approve access."],
  },
  "tab.hr.payroll": {
    title: "Payroll",
    summary: "Pay runs for a selected period.",
    what: "Generate payroll, view runs, and approve when authorized.",
    how: [
      "Set period start and end.",
      "Run payroll.",
      "Open details and approve if you have rights.",
    ],
    when: "At salary cycle close.",
    tips: ["Fix attendance/leave issues before running payroll."],
  },

  "page.marketing.template": {
    title: "Message template",
    summary: "Preview how a CRM template looks when sent to customers.",
    what: "Shows the raw title/body placeholders and an interpolated preview using live business branding plus sample customer values.",
    how: [
      "Open a template from Marketing → Templates.",
      "Review placeholders in the overview.",
      "Check the customer preview with sample values.",
      "Use Back to return to the Templates tab.",
    ],
    when: "When drafting reusable campaign messages or checking SMS length.",
    tips: ["Placeholders are flat keys like {{business}} — nested {{customer.name}} is not supported."],
  },

  "tab.marketing.campaigns": {
    title: "Campaigns",
    summary: "Draft and send customer messages.",
    what: "Create marketing campaigns, choose audience, and send with delivery summary.",
    how: [
      "Create a draft campaign.",
      "Review audience and message.",
      "Send when ready and open results for details.",
    ],
    when: "For promotions and customer outreach.",
    tips: ["Drafts can be edited before sending."],
  },
  "tab.marketing.segments": {
    title: "Segments",
    summary: "Saved customer audiences for targeting.",
    what: "Reusable filters for campaigns (e.g. by loyalty).",
    how: ["Build a segment with filters.", "Reuse it when composing a campaign."],
    when: "For targeted offers instead of blasting everyone.",
    tips: ["Keep segment names descriptive."],
  },
  "tab.marketing.coupons": {
    title: "Coupons",
    summary: "Promo codes for POS checkout.",
    what: "Discount codes cashiers can enter in the cart.",
    how: [
      "Create a code and discount value.",
      "Share with customers.",
      "Enter the code at POS before checkout.",
    ],
    when: "For discount campaigns and partner offers.",
    tips: ["Set usage limits so codes are not over-redeemed."],
  },
  "tab.marketing.tiers": {
    title: "Loyalty Tiers",
    summary: "Earn/redeem rates by points band.",
    what: "Configures how quickly customers earn and redeem points.",
    how: [
      "Add a tier with minimum points.",
      "Set earn/redeem multipliers.",
      "Test with a sample customer.",
    ],
    when: "When launching or tuning loyalty.",
    tips: ["Higher tiers usually earn faster—communicate this to customers."],
  },

  "tab.settings.notifications": {
    title: "Notification Preferences",
    summary: "Choose which alerts you receive.",
    what: "Per-user toggles for notification types.",
    how: ["Open the Notifications tab in Settings.", "Turn types on or off as needed."],
    when: "When alerts are too noisy or important items are being missed.",
    tips: ["These preferences apply to your user, not the whole business."],
  },
  "tab.settings.profile": {
    title: "Profile",
    summary: "Your name, phone, password, and photo.",
    what: "Personal account details for the signed-in user.",
    how: [
      "Update display name and phone.",
      "Upload a profile photo.",
      "Set a new password only when needed.",
    ],
    when: "On first login or when personal details change.",
  },
  "tab.settings.subscriptions": {
    title: "Subscription & Usage",
    summary: "Plan status and seat/branch limits.",
    what: "Current plan, status, usage versus limits, and Safepay upgrade checkout (JazzCash, Easypaisa, or card).",
    how: [
      "Review usage counters.",
      "Choose a plan and pay with JazzCash, Easypaisa, or card to upgrade.",
    ],
    when: "When approaching limits or at billing renewal.",
    tips: ["Owner access is required for this tab."],
  },
  "tab.businesses.details": {
    title: "Business details",
    summary: "Name, industry, and tax jurisdiction.",
    what: "Core identity fields for the selected business.",
    how: ["Edit fields and save.", "Use Deactivate when the business should stop operations."],
    when: "When renaming or correcting business metadata.",
  },
  "tab.businesses.branches": {
    title: "Branches",
    summary: "Locations under this business.",
    what: "Create and soft-deactivate branches within plan limits.",
    how: ["Add a branch with a name.", "Deactivate closed locations."],
    when: "Opening a new till location or closing one.",
  },
  "tab.businesses.branding": {
    title: "Business branding",
    summary: "Logo, tagline, color, and marketplace copy.",
    what: "Visual identity used on marketplace and staff UI for this business.",
    how: ["Upload a logo.", "Pick a brand color.", "Save branding."],
    when: "Before listing on the marketplace or refreshing brand identity.",
  },
  "tab.settings.integrations": {
    title: "Integrations",
    summary: "External connections and compliance flags.",
    what: "Owner tools to connect services for the business (e.g. FBR flags).",
    how: ["Review available integration settings.", "Change flags only when you understand the impact."],
    when: "When setting up integrations or compliance.",
    tips: ["Wrong flags can affect tax reporting—confirm with your accountant."],
  },
  "tab.settings.roles": {
    title: "Roles",
    summary: "Who can access which modules.",
    what: "Owner configuration of role-based access on Kaarobar bundles.",
    how: ["Review role assignments.", "Change carefully—staff may lose access."],
    when: "When hiring, promoting, or tightening security.",
    tips: ["Least privilege: give each role only the bundles they need."],
  },
  "tab.settings.branding": {
    title: "Store branding",
    summary: "Logo, colors, and marketplace listing for your business.",
    what: "Controls how your store looks in Discover/catalog and remaps the in-app UI scheme (buttons, focus rings, nav) from primary color.",
    how: [
      "Upload a logo and pick a primary brand color.",
      "Add tagline and marketplace description.",
      "Save branding, then preview Discover or shop as a consumer.",
    ],
    when: "Before going live on the marketplace or refreshing brand look.",
    tips: ["Owner access is required. Saving branding updates the staff workspace theme immediately."],
  },
  "tab.marketing.templates": {
    title: "Message templates",
    summary: "Reusable CRM message bodies with variables.",
    what: "Saved templates for campaigns and previews (business name, tagline, etc.).",
    how: [
      "Create a template in the modal with placeholders.",
      "Browse available {{variables}} on the Templates tab.",
      "Open a template to preview interpolated customer copy.",
      "Select the template when composing a campaign.",
    ],
    when: "When standardizing promotional or transactional messages.",
    tips: ["Keep templates short for SMS/WhatsApp channels.", "Only flat keys like {{name}} work — not {{customer.name}}."],
  },
  "page.appointments": {
    title: "Appointments",
    summary: "Staff day schedule for service bookings.",
    what: "Lists appointments for the selected date (and optional staff). Complete or cancel bookings; completion can link a POS sale stub (SCH-FR-005).",
    how: [
      "Pick a date and optionally filter by staff.",
      "Search or filter by status.",
      "Tap Complete to advance a visit, or Cancel for Booked rows.",
    ],
    when: "On salon / appointments-enabled businesses during the service day.",
    tips: ["Customers book from the marketplace Book flow; staff manage the day here."],
  },
};

export default en;
