import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Panel de control",
    summary: "KPIs más gráficos de ventas interactivos filtrados por rango de fechas.",
    what: "Muestra las ventas de hoy, posición de efectivo, stock bajo, aprobaciones pendientes y tendencias de ingresos/pedidos para un rango de fechas.",
    how: [
      "Tras iniciar sesión, revise las tarjetas KPI de hoy.",
      "Defina las fechas desde/hasta para actualizar los gráficos.",
      "Pase el cursor por un punto del gráfico para ver el total diario o los tickets.",
      "Use las tarjetas de stock bajo o aprobaciones para ir a Inventario o Devoluciones.",
      "Cambie negocio o sucursal en la cabecera si gestiona varias ubicaciones.",
    ],
    when: "Al inicio del turno, al final del día o cuando necesites un control de salud en la sucursal.",
    tips: [
      "Los gráficos usan ventas completadas del negocio seleccionado (RPT-FR-001).",
      "Si los gráficos están vacíos, amplíe el rango o revise la actividad de caja.",
    ],
  },
  "page.pos": {
    title: "Punto de Venta",
    summary: "Pago rápido con carrito, cliente y pago.",
    what: "Los cajeros pueden vender productos, vincular clientes por fidelidad o crédito (crédito), aplicar descuentos o cupones y aceptar pagos en efectivo, tarjeta, billetera o crédito.",
    how: [
      "Abra una caja antes de realizar ventas en efectivo.",
      "Agregue productos al carrito mediante búsqueda o escaneo de código de barras.",
      "Adjunte un cliente cuando sea necesario para fidelizarlo o crédito.",
      "Revise el total, toque Continuar con el pago y elija un método de pago.",
      "Complete el pedido con Realizar pedido y luego imprima o comparta el recibo.",
    ],
    when: "Por cada pago del cliente en el mostrador.",
    tips: [
      "El pago Crédito requiere un crédito activo en el cliente.",
      "Mantenga la caja abierta durante el turno y cuente el efectivo antes de cerrar al final del día.",
    ],
  },
  "page.inventory": {
    title: "Inventario y compras",
    summary: "Catálogo, stock disponible, proveedores, órdenes de compra, traslados y ajustes.",
    what: "El lugar para mantener productos, ver niveles de stock, comprar a proveedores, mover stock entre sucursales y corregir cantidades.",
    how: [
      "Cree o actualice SKU y precios de Productos.",
      "Vea la cantidad disponible y el costo promedio del inventario.",
      "Agregue proveedores, luego cree órdenes de compra y reciba mercancías (GRN).",
      "Utilice Transferencias para mover stock entre sucursales y Ajustar para fijar cantidades.",
    ],
    when: "Al recibir mercancías, agregar nuevos artículos, realizar un recuento de existencias o realizar transferencias entre sucursales.",
    tips: [
      "Reciba contra una orden de compra para que los costos y las cuentas por pagar se mantengan precisos.",
      "Utilice un código de motivo claro en Ajustar para los seguimientos de auditoría.",
    ],
  },
  "page.customers": {
    title: "Clientes y Crédito",
    summary: "Perfiles de clientes, saldo de crédito/crédito, libro mayor y puntos de fidelidad.",
    what: "Almacena los detalles del cliente y le permite habilitar crédito, ver el libro mayor, administrar los límites de crédito y ajustar los puntos de fidelidad.",
    how: [
      "Agregue un cliente con nombre y teléfono.",
      "Habilite crédito para ventas a crédito.",
      "Abra Ledger para ver débitos, créditos y saldo pendiente.",
      "Ajustar puntos de fidelidad por promociones o correcciones.",
    ],
    when: "Para CRM, ventas a crédito y programas de fidelización.",
    tips: [
      "Adjunte al cliente en POS antes del pago crédito.",
      "Verifique el límite de crédito antes de grandes ventas de crédito.",
    ],
  },
  "page.sales": {
    title: "Historial de ventas",
    summary: "Listado completo de facturas de venta de la sucursal seleccionada.",
    what: "Muestra pagos anteriores con número de factura, cliente, total, estado y hora para que pueda reabrir o verificar una venta.",
    how: [
      "Busque o explore la lista de ventas.",
      "Abra una fila para ver partidas y pagos.",
      "Utilice el número de factura al procesar una devolución.",
    ],
    when: "Para consultas de clientes, auditorías, reimpresión de recibos o antes de una devolución.",
    tips: ["Las ventas aparecen después de un pago exitoso POS."],
  },
  "page.returns": {
    title: "Devoluciones y Cajas",
    summary: "Reembolsos sobre ventas pasadas y hasta el historial de apertura/cierre.",
    what: "El personal puede buscar una venta y enviar una devolución, y ver sesiones de caja que incluyen montos excesivos o insuficientes.",
    how: [
      "Busque por el número de factura de venta original.",
      "Envíe la devolución con el método de reembolso y el motivo.",
      "Los directivos aprueban o rechazan las devoluciones pendientes.",
      "Revise el efectivo de apertura/cierre y la variación en el historial de caja.",
    ],
    when: "Al emitir reembolsos, manipular mercancías dañadas o conciliar cajas.",
    tips: ["Conserve la factura original: devuelve el enlace a esa venta."],
  },
  "page.accounting": {
    title: "Contabilidad",
    summary: "IFRS-for-SMEs books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools aligned with IFRS for SMEs presentation: chart of accounts (create/edit), journals, trial balance, sectioned P&L and balance sheet, cash flow, general ledger, and receivables/payables aging.",
    how: [
      "Create or edit ledger accounts on Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, Cash flow, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Header accounts are for structure only—post to leaf accounts.",
    ],
  },
  "page.hr": {
    title: "Recursos Humanos y Nómina",
    summary: "Empleados, asistencia, licencias y cálculos de nómina.",
    what: "Gestiona los datos maestros del personal, la asistencia, las solicitudes de licencia y el cálculo y aprobación de la nómina.",
    how: [
      "Agregue empleados o invite a usuarios existentes.",
      "Registre la asistencia y revise las solicitudes de licencia.",
      "Ejecute la nómina por un período y luego apruebe.",
    ],
    when: "Para contratación, asistencia diaria, aprobación de licencias y ciclos salariales.",
    tips: ["La aprobación de la nómina puede requerir un rol o paquete específico."],
  },
  "page.marketing": {
    title: "Comercialización",
    summary: "Campañas, segmentos, cupones y niveles de fidelización.",
    what: "Le ayuda a enviar mensajes a los clientes, apuntar a segmentos, configurar códigos promocionales y configurar tasas de obtención/canje de fidelidad.",
    how: [
      "Crea un borrador de campaña con audiencia y mensaje.",
      "Envíe cuando esté listo: el estado de entrega aparece en la campaña.",
      "Cree segmentos y cupones para ofertas específicas.",
      "Establezca niveles de fidelidad basados en bandas de puntos.",
    ],
    when: "Para promociones, ofertas de festivales, mensajes de recuperación y configuración de fidelización.",
    tips: ["Conecte los canales de los clientes para una mejor entrega."],
  },
  "page.reports": {
    title: "Informes",
    summary: "Ventas operativas y desempeño del producto.",
    what: "Informes de sucursales como ventas diarias y productos principales. Los estados financieros completos se encuentran en Contabilidad.",
    how: [
      "Elija un rango de fechas.",
      "Revise las ventas diarias y el recuento de entradas.",
      "Consulta los productos más vendidos por cantidad.",
    ],
    when: "Para revisiones semanales, decisiones de comercialización o actualizaciones de propietarios.",
    tips: ["Abra Contabilidad para P&L o balance."],
  },
  "page.settings": {
    title: "Configuración",
    summary: "Perfil, límites del plan, facturación, notificaciones, indicadores FBR y roles.",
    what: "Configuración de cuenta y negocio: perfil, uso de suscripción, preferencias de notificación, integraciones y acceso a roles (algunas pestañas son solo para propietarios).",
    how: [
      "Actualice su perfil en la pestaña Perfil.",
      "Revise el uso con respecto a los límites del plan y actualice desde las tarjetas del plan.",
      "Los propietarios pueden gestionar integraciones, marcas y roles para la empresa activa.",
    ],
    when: "Durante la incorporación, las actualizaciones del plan o al cambiar el acceso al módulo.",
    tips: ["Algunas configuraciones son solo para el propietario: pregúntele al propietario si falta una pestaña."],
  },
  "page.businesses": {
    title: "Empresas",
    summary: "Cree y administre negocios con su cuenta de propietario.",
    what: "Lista de propietarios de empresas con creación, detalles abiertos y desactivación temporal.",
    how: [
      "Crear un negocio con nombre e industria.",
      "Abra una empresa para editar detalles, sucursales y marca.",
      "Desactívelo cuando cierre una ubicación: se conserva el historial.",
    ],
    when: "Al expandirse a una nueva marca o cerrar un negocio.",
    tips: ["Los límites del plan se aplican a la cantidad de empresas y sucursales que puede agregar."],
  },
  "page.notifications": {
    title: "Notificaciones",
    summary: "Alertas de bajas, nómina, facturación y campaña.",
    what: "Alertas del sistema y del flujo de trabajo para que no se pierdan las aprobaciones y los resultados de la campaña.",
    how: [
      "Abra Notificaciones para ver elementos no leídos.",
      "Haga clic en una alerta vinculada para ir a la pantalla relacionada.",
      "Ajuste las preferencias en Configuración si las alertas son demasiado ruidosas.",
    ],
    when: "Durante todo el día para aprobaciones y actualizaciones operativas.",
    tips: ["Mantenga el panel abierto en los días de mayor actividad para que las solicitudes de licencia y nómina permanezcan visibles."],
  },
  "page.profile": {
    title: "Tu perfil",
    summary: "Nombre personal, teléfono, contraseña y foto.",
    what: "Actualiza su cuenta de usuario, no la configuración comercial completa.",
    how: [
      "Cambiar nombre para mostrar y teléfono.",
      "Establezca una nueva contraseña sólo cuando necesite cambiarla.",
      "Sube una foto de perfil cuando esté disponible.",
    ],
    when: "Al configurar el primer inicio de sesión o al actualizar datos personales.",
    tips: ["Cambie el idioma desde el control de idioma de la barra lateral."],
  },
  "page.businessDetail": {
    title: "Detalle del negocio",
    summary: "Edite una empresa: marca, mercado y sucursales.",
    what: "Herramientas de propietario para una única identidad empresarial y ubicaciones.",
    how: [
      "Actualice el nombre, la industria, el eslogan y el color de la marca.",
      "Cargue un logotipo y configure la lista del mercado.",
      "Agregue o desactive sucursales según sea necesario.",
    ],
    when: "Al lanzar una tienda o renovar la apariencia de la marca.",
    tips: ["La desactivación mantiene los datos financieros históricos; nada se elimina por completo."],
  },
  "page.ess": {
    title: "Herramientas del personal (ESS)",
    summary: "Autoservicio del empleado para asistencia y bajas.",
    what: "El personal puede realizar el registro de entrada/salida y enviar licencias sin acceso completo de administrador de recursos humanos.",
    how: [
      "Marque la asistencia de hoy.",
      "Presentar licencia con fechas y motivo.",
      "Verifique el estado de aprobación después del envío.",
    ],
    when: "Diariamente para el personal que utiliza el autoservicio de RRHH.",
    tips: ["Los gerentes aún aprueban las licencias desde la pestaña Licencia de Recursos Humanos."],
  },

  "tab.inventory.stock": {
    title: "Stock disponible",
    summary: "Cantidad y costo promedio de cada producto en esta sucursal.",
    what: "Vista del saldo de inventario después de compras, ventas, transferencias y ajustes.",
    how: [
      "Busque por SKU o nombre del producto.",
      "Revise la cantidad antes de realizar otro pedido.",
      "Compare con Productos si algo parece estar mal.",
    ],
    when: "Antes de realizar pedidos, realizar inspecciones al azar o investigar la escasez.",
    tips: ["Actualizaciones de costos promedio cuando se reciben los bienes."],
  },
  "tab.inventory.products": {
    title: "Productos",
    summary: "Venta de artículos, servicios, precios y códigos de barras.",
    what: "Cree y edite productos utilizados en POS y seguimiento de existencias.",
    how: [
      "Agregue un producto con SKU, nombre y precio.",
      "Configure un código de barras para escanear al finalizar la compra.",
      "Abra un producto para ver o editar detalles.",
    ],
    when: "Al agregar nuevos artículos o actualizar precios.",
    tips: ["Mantenga los SKU únicos en toda la empresa."],
  },
  "tab.inventory.suppliers": {
    title: "Proveedores",
    summary: "Maestro de proveedores para compras.",
    what: "Contacto del proveedor, condiciones de pago y estado utilizados en las órdenes de compra.",
    how: [
      "Agregue un proveedor con nombre y datos de contacto.",
      "Establezca las condiciones de pago antes de crear una orden de compra.",
      "Abra un proveedor para ver todos los detalles.",
    ],
    when: "Al configurar compras o actualizar los detalles del proveedor.",
    tips: ["No utilice proveedores inactivos en el nuevo POs."],
  },
  "tab.inventory.pos": {
    title: "Órdenes de compra",
    summary: "Pedidos de proveedores y entrada de mercancías (GRN).",
    what: "Cree POs, realice un seguimiento del estado y reciba cantidades en stock.",
    how: [
      "Cree una orden de compra con proveedores y artículos de línea.",
      "Recibir mercancías contra la orden de compra cuando llegue el stock (GRN).",
      "Abra una orden de compra para revisar las líneas y el estado.",
    ],
    when: "Al reordenar stock a un proveedor.",
    tips: ["Reciba solo lo que llegó: se admiten recibos parciales."],
  },
  "tab.inventory.transfers": {
    title: "Transferencias",
    summary: "Mover stock entre sucursales.",
    what: "Crea un documento de transferencia que debe ser confirmado para que el stock pase de una sucursal a otra.",
    how: [
      "Elige sucursal de destino, producto y cantidad.",
      "Cree la transferencia y confirme una vez que se muevan las mercancías.",
    ],
    when: "Al equilibrar el stock entre ubicaciones.",
    tips: ["Confirme con prontitud para que las cantidades disponibles sean precisas."],
  },
  "tab.inventory.adjust": {
    title: "Ajuste de existencias",
    summary: "Cantidad correcta por daños, variación de conteo o cancelaciones.",
    what: "Cantidad de cambios (+/-) con un código de motivo para auditoría.",
    how: [
      "Elija producto y cantidad delta.",
      "Seleccione un código de motivo.",
      "Guárdelo para actualizar el stock disponible.",
    ],
    when: "Después de un recuento físico o cuando la mercancía se daña o se pierde.",
    tips: ["Prefiera GRN/transferencias para movimiento normal; utilice Ajustar para realizar correcciones."],
  },

  "tab.accounting.coa": {
    title: "Plan de cuentas",
    summary: "IFRS-for-SMEs ledger accounts for journals and statements.",
    what: "Hierarchical list of account codes with type, classification, and normal balance. Create new accounts or edit existing ones.",
    how: [
      "Use New account to add a postable or header account.",
      "Browse by code; indent shows parent hierarchy.",
      "Edit an account to change labels or classification.",
    ],
    when: "During setup review or when you need a new ledger account.",
    tips: [
      "Do not delete accounts that already have postings.",
    ],
  },
  "tab.accounting.journals": {
    title: "Revistas",
    summary: "Asientos de diario manuales y del sistema.",
    what: "Muestra diarios publicados y le permite publicar entradas manuales equilibradas.",
    how: [
      "Abra un diario para ver las líneas de débito/crédito.",
      "Utilice Publicar diario para realizar un ajuste de dos líneas cuando sea necesario.",
    ],
    when: "Para correcciones, acumulaciones o revisión de entradas publicadas automáticamente.",
    tips: ["Los débitos deben ser iguales a los créditos antes de su contabilización."],
  },
  "tab.accounting.tb": {
    title: "Saldo de prueba",
    summary: "Totales de débito/crédito por cuenta para un período.",
    what: "Verifica que los libros estén equilibrados antes de ejecutar los extractos.",
    how: ["Establecer fechas desde/hasta.", "Revisar los totales de la cuenta."],
    when: "Al final de mes o antes de P&L / balance.",
    tips: ["Investigue saldos inesperadamente grandes."],
  },
  "tab.accounting.pl": {
    title: "PyG",
    summary: "Sectioned income statement (IFRS for SMEs).",
    what: "Revenue, cost of sales, operating expenses, and net income for the selected period.",
    how: [
      "Choose dates.",
      "Review sections and subtotals (gross / operating / net).",
    ],
    when: "For owner review and period close.",
    tips: [
      "Accuracy depends on correct account classifications and postings.",
    ],
  },
  "tab.accounting.bs": {
    title: "Balance",
    summary: "Sectioned statement of financial position.",
    what: "Current and non-current assets/liabilities plus equity as of the report date.",
    how: [
      "Set the as-of date.",
      "Review current vs non-current sections.",
    ],
    when: "For period close and financial discussions.",
    tips: [
      "AR/AP aging complements customer and supplier balances.",
    ],
  },
  "tab.accounting.cf": {
    title: "Flujo de efectivo",
    summary: "Indirect cash flow summary for a period.",
    what: "Starts from net income and adjusts for working-capital changes (AR, inventory, AP).",
    how: [
      "Choose dates.",
      "Review cash from operations.",
    ],
    when: "For cash planning alongside P&L and balance sheet.",
    tips: [
      "This is a simplified indirect method—not a full IAS 7 statement.",
    ],
  },

  "tab.accounting.gl": {
    title: "Libro mayor",
    summary: "Actividad línea por línea para una cuenta.",
    what: "Historial de débito/crédito para una sola cuenta.",
    how: ["Seleccione una cuenta.", "Establecer fechas.", "Revisa cada publicación."],
    when: "Al investigar saldos o conciliar una cuenta.",
    tips: ["Primero ejecute el balance de comprobación y luego abra GL para cuentas impares."],
  },
  "tab.accounting.ar": {
    title: "Envejecimiento AR",
    summary: "Cuentas por cobrar de clientes por grupo de edad.",
    what: "Saldos de facturas abiertas agrupados por antigüedad (vigente, 30, 60 días, etc.).",
    how: ["Revisar los cubos.", "Abra una factura para obtener más detalles.", "Seguimiento con el cliente."],
    when: "Para cobranzas y control de crédito.",
    tips: ["Crédito/ventas a crédito pueden aparecer en AR."],
  },
  "tab.accounting.ap": {
    title: "Envejecimiento AP",
    summary: "Cuentas por pagar de proveedores por grupo de edad.",
    what: "Facturas que debes, agrupadas por fecha de vencimiento.",
    how: ["Revisar los cubos.", "Abra una factura para obtener más detalles.", "Planificar pagos a proveedores."],
    when: "Para pago de proveedores y planificación de efectivo.",
    tips: ["Los recibos de PO a menudo crean facturas AP."],
  },

  "tab.hr.employees": {
    title: "Empleados",
    summary: "Lista maestra de personal y detalles de empleo.",
    what: "Cree registros de empleados, edite el salario base y abra perfiles.",
    how: [
      "Agregue un empleado o invite a un usuario existente.",
      "Edite el título, el salario y el estado.",
      "Abra un empleado para obtener todos los detalles.",
    ],
    when: "Para contrataciones, cambios de roles o actualizaciones salariales.",
    tips: ["La invitación vincula el registro de recursos humanos para iniciar sesión."],
  },
  "tab.hr.attendance": {
    title: "Asistencia",
    summary: "Historial de check-in/check-out.",
    what: "Filas de asistencia para nómina y cumplimiento.",
    how: ["Filtrar por fecha.", "Corrija los golpes faltantes a través de ESS o un administrador."],
    when: "Para operaciones diarias y antes de nómina.",
    tips: ["La fuente puede ser ESS o la entrada del administrador."],
  },
  "tab.hr.leave": {
    title: "salir",
    summary: "Dejar solicitudes y aprobaciones.",
    what: "Los gerentes aprueban o rechazan las licencias según los permisos de función.",
    how: [
      "Revisar solicitudes pendientes.",
      "Aprobar o rechazar con cuidado.",
      "Confirme las fechas con el empleado si no están claras.",
    ],
    when: "Cuando el personal solicite tiempo libre.",
    tips: ["La aprobación depende del acceso a Leave_approve."],
  },
  "tab.hr.payroll": {
    title: "Nómina",
    summary: "El pago se ejecuta durante un período seleccionado.",
    what: "Genere nómina, vea ejecuciones y apruebe cuando esté autorizado.",
    how: [
      "Establecer el inicio y el final del período.",
      "Ejecutar nómina.",
      "Abra los detalles y apruebe si tiene derechos.",
    ],
    when: "Al cierre del ciclo salarial.",
    tips: ["Solucione problemas de asistencia/licencias antes de ejecutar la nómina."],
  },

  "page.marketing.template": {
    title: "Plantilla de mensaje",
    summary: "Vista previa de cómo se ve una plantilla CRM al enviarla a clientes.",
    what: "Muestra marcadores en bruto y una vista interpolada con branding del negocio y valores de muestra.",
    how: [
      "Abra una plantilla en Marketing → Plantillas.",
      "Revise los marcadores en el resumen.",
      "Compruebe la vista previa del cliente.",
      "Atrás vuelve a la pestaña Plantillas.",
    ],
    when: "Al redactar mensajes de campaña reutilizables.",
    tips: ["Los marcadores son claves planas como {{business}} — no se admite {{customer.name}}."],
  },

  "tab.marketing.campaigns": {
    title: "Campañas",
    summary: "Redactar y enviar mensajes a los clientes.",
    what: "Cree campañas de marketing, elija audiencia y envíelas con un resumen de entrega.",
    how: [
      "Crea un borrador de campaña.",
      "Revisar audiencia y mensaje.",
      "Envíe cuando esté listo y abra los resultados para obtener más detalles.",
    ],
    when: "Para promociones y atención al cliente.",
    tips: ["Los borradores se pueden editar antes de enviarlos."],
  },
  "tab.marketing.segments": {
    title: "Segmentos",
    summary: "Audiencias de clientes guardadas para segmentación.",
    what: "Filtros reutilizables para campañas (p. ej. por fidelización).",
    how: ["Construya un segmento con filtros.", "Reutilícelo al redactar una campaña."],
    when: "Para ofertas específicas en lugar de criticar a todos.",
    tips: ["Mantenga los nombres de los segmentos descriptivos."],
  },
  "tab.marketing.coupons": {
    title: "Cupones",
    summary: "Códigos promocionales para el pago POS.",
    what: "Los códigos de descuento que los cajeros pueden ingresar en el carrito.",
    how: [
      "Crea un código y un valor de descuento.",
      "Compartir con los clientes.",
      "Ingrese el código en POS antes de realizar el pago.",
    ],
    when: "Para campañas de descuentos y ofertas de socios.",
    tips: [
      "Establezca límites de uso para que los códigos no se canjeen en exceso.",
      "Deje Válido desde/hasta vacío sin límite de fechas; ventanas vencidas fallan en POS.",
    ],
  },
  "tab.marketing.tiers": {
    title: "Niveles de lealtad",
    summary: "Gane/canjee tarifas por banda de puntos.",
    what: "Configura la rapidez con la que los clientes ganan y canjean puntos.",
    how: [
      "Añade un nivel con puntos mínimos.",
      "Establezca multiplicadores de ganancias/canjeos.",
      "Pruebe con un cliente de muestra.",
    ],
    when: "Al lanzar o afinar la fidelización.",
    tips: ["Los niveles más altos generalmente ganan más rápido; comuníqueselo a los clientes."],
  },

  "tab.settings.notifications": {
    title: "Preferencias de notificación",
    summary: "Elija qué alertas recibir.",
    what: "Por usuario alterna entre los tipos de notificación.",
    how: ["Abra la pestaña Notificaciones en Configuración.", "Active o desactive los tipos según sea necesario."],
    when: "Cuando las alertas son demasiado ruidosas o se pasan por alto elementos importantes.",
    tips: ["Estas preferencias se aplican a su usuario, no a toda la empresa."],
  },
  "tab.settings.profile": {
    title: "Perfil",
    summary: "Tu nombre, teléfono, contraseña y foto.",
    what: "Detalles de la cuenta personal del usuario que inició sesión.",
    how: [
      "Actualice el nombre para mostrar y el teléfono.",
      "Sube una foto de perfil.",
      "Establezca una nueva contraseña sólo cuando sea necesario.",
    ],
    when: "Al iniciar sesión por primera vez o cuando cambian los datos personales.",
  },
  "tab.settings.subscriptions": {
    title: "Suscripción y uso",
    summary: "Estado del plan y límites de asientos/sucursales.",
    what: "Plan actual, estado, uso versus límites y pago de actualización de Safepay (JazzCash, Easypaisa o tarjeta).",
    how: [
      "Revisar los contadores de uso.",
      "Elija un plan y pague con JazzCash, Easypaisa o tarjeta para actualizar.",
    ],
    when: "Al acercarse a límites o en renovación de facturación.",
    tips: ["Se requiere acceso de propietario para esta pestaña."],
  },
  "tab.businesses.details": {
    title: "Detalles del negocio",
    summary: "Nombre, industria y jurisdicción fiscal.",
    what: "Campos de identidad principales para la empresa seleccionada.",
    how: ["Edite campos y guarde.", "Utilice Desactivar cuando la empresa deba detener sus operaciones."],
    when: "Al cambiar el nombre o corregir los metadatos comerciales.",
  },
  "tab.businesses.branches": {
    title: "Sucursales",
    summary: "Ubicaciones bajo este negocio.",
    what: "Cree y desactive sucursales dentro de los límites del plan.",
    how: ["Agrega una rama con un nombre.", "Desactivar ubicaciones cerradas."],
    when: "Abrir una nueva ubicación de caja o cerrar una.",
  },
  "tab.businesses.branding": {
    title: "marca empresarial",
    summary: "Logotipo, eslogan, color y copia del mercado.",
    what: "Identidad visual utilizada en el mercado y en la interfaz de usuario del personal de este negocio.",
    how: ["Sube un logotipo.", "Elige un color de marca.", "Guardar marca."],
    when: "Antes de cotizar en el mercado o actualizar la identidad de la marca.",
  },
  "tab.settings.integrations": {
    title: "Integraciones",
    summary: "Conexiones externas y banderas de cumplimiento.",
    what: "Herramientas de propietario para conectar servicios para la empresa (por ejemplo, banderas FBR).",
    how: ["Revise la configuración de integración disponible.", "Cambie las banderas sólo cuando comprenda el impacto."],
    when: "Al configurar integraciones o cumplimiento.",
    tips: ["Las marcas incorrectas pueden afectar la declaración de impuestos; confírmela con su contador."],
  },
  "tab.settings.roles": {
    title: "Roles",
    summary: "Quién puede acceder a qué módulos.",
    what: "Configuración del propietario del acceso basado en roles en paquetes Kaarobar.",
    how: ["Revisar las asignaciones de roles.", "Cambie con cuidado: el personal puede perder el acceso."],
    when: "Al contratar, promocionar o reforzar la seguridad.",
    tips: ["Mínimo privilegio: otorga a cada rol solo los paquetes que necesita."],
  },
  "tab.settings.branding": {
    title: "Marca de la tienda",
    summary: "Logotipo, colores y listado del mercado para su negocio.",
    what: "Controla el aspecto de tu tienda en Descubrir/catálogo y reasigna el esquema de interfaz de usuario en la aplicación (botones, anillos de enfoque, navegación) desde el color primario.",
    how: [
      "Cargue un logotipo y elija un color de marca principal.",
      "Agregue un eslogan y una descripción del mercado.",
      "Guarde la marca y luego obtenga una vista previa de Descubrir o comprar como consumidor.",
    ],
    when: "Antes de lanzarse al mercado o de renovar la apariencia de la marca.",
    tips: ["Se requiere acceso de propietario. Al guardar la marca, se actualiza el tema del espacio de trabajo del personal de inmediato."],
  },
  "tab.marketing.templates": {
    title: "Plantillas de mensajes",
    summary: "Cuerpos de mensajes de CRM reutilizables con variables.",
    what: "Plantillas guardadas para campañas y vistas previas (nombre comercial, eslogan, etc.).",
    how: [
      "Cree o edite una plantilla con marcadores de posición.",
      "Vista previa con variables comerciales de muestra.",
      "Seleccione la plantilla al redactar una campaña.",
    ],
    when: "Al estandarizar mensajes promocionales o transaccionales.",
    tips: ["Mantenga las plantillas breves para los canales de SMS/WhatsApp."],
  },
  "page.appointments": {
    title: "Citas",
    summary: "Agenda diaria del personal para reservas de servicios.",
    what: "Muestra las citas de la fecha seleccionada y, opcionalmente, de un profesional. Permite completar o cancelar reservas; al completarlas se puede preparar una venta POS vinculada (SCH-FR-005).",
    how: [
      "Elige una fecha y, si lo necesitas, filtra por profesional.",
      "Busca o filtra por estado.",
      "Pulsa Completar para finalizar una visita o Cancelar en las citas reservadas.",
    ],
    when: "Durante la jornada en salones y otros negocios con citas habilitadas.",
    tips: ["Los clientes reservan desde Reservar en el marketplace; el personal gestiona aquí la agenda del día."],
  },
};

export default catalog;
