import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Tableau de bord",
    summary: "KPIs et graphiques de ventes interactifs filtrés par période.",
    what: "Affiche les ventes du jour, la trésorerie, les stocks bas, les validations en attente et les tendances CA/commandes pour une période choisie.",
    how: [
      "Après connexion, consultez les cartes KPI du jour.",
      "Définissez les dates de/à pour actualiser les graphiques.",
      "Survolez un point pour le total journalier ou le nombre de tickets.",
      "Utilisez les cartes stock bas ou validations pour aller vers Inventaire ou Retours.",
      "Changez d'entreprise ou de succursale dans l'en-tête si besoin.",
    ],
    when: "Au début du quart de travail, à la fin de la journée ou chaque fois que vous avez besoin d’un bilan de santé en agence.",
    tips: [
      "Les graphiques utilisent les ventes terminées de l'entreprise sélectionnée (RPT-FR-001).",
      "Graphiques vides : élargissez la période ou vérifiez l'activité de caisse.",
    ],
  },
  "page.pos": {
    title: "Point de vente",
    summary: "Paiement rapide avec panier, client et paiement.",
    what: "Les caissiers peuvent vendre des produits, fidéliser les clients ou crédit (crédit), appliquer des remises ou des coupons et accepter les paiements en espèces, par carte, par portefeuille ou par crédit.",
    how: [
      "Ouvrez une caisse avant d'effectuer des ventes au comptant.",
      "Ajoutez des produits au panier par recherche ou numérisation de codes-barres.",
      "Attachez un client en cas de besoin pour la fidélité ou crédit.",
      "Vérifiez le total, appuyez sur Passer à la caisse et choisissez un mode de paiement.",
      "Complétez la commande avec Passer la commande, puis imprimez ou partagez le reçu.",
    ],
    when: "Pour chaque paiement client au comptoir.",
    tips: [
      "Le paiement Crédit nécessite un crédit actif sur le client.",
      "Gardez la caisse ouverte pendant le quart de travail et comptez les espèces avant de fermer en fin de journée.",
    ],
  },
  "page.inventory": {
    title: "Inventaire et achats",
    summary: "Catalogue, stock disponible, fournisseurs, bons de commande, transferts et ajustements.",
    what: "L'endroit où gérer les produits, consulter les niveaux de stock, acheter auprès des fournisseurs, déplacer les stocks entre les succursales et corriger les quantités.",
    how: [
      "Créez ou mettez à jour les SKU et les prix à partir des produits.",
      "Affichez la quantité disponible et le coût moyen du stock.",
      "Ajoutez des fournisseurs, puis créez des bons de commande et recevez des marchandises (GRN).",
      "Utilisez les transferts pour déplacer le stock entre les succursales et Ajuster pour fixer les quantités.",
    ],
    when: "Lors de la réception de marchandises, de l'ajout de nouveaux articles, d'un inventaire ou d'un transfert entre succursales.",
    tips: [
      "Recevez contre un bon de commande afin que les coûts et les comptes créditeurs restent exacts.",
      "Utilisez un code motif clair dans Adjust pour les pistes d’audit.",
    ],
  },
  "page.inventory.supplier": {
    title: "Détail fournisseur",
    summary: "Contact, conditions et produits liés pour les bons de commande.",
    what: "Chaque fournisseur stocke les coordonnées et une liste explicite des produits catalogue qu’il peut fournir. Seuls les produits liés apparaissent lors d’un bon de commande (INV-FR).",
    how: [
      "Ouvrez un fournisseur depuis Inventaire → Fournisseurs.",
      "Vérifiez le contact, l’adresse et les conditions de paiement.",
      "Liez les produits catalogue que ce fournisseur fournit.",
      "Déliez les produits que le fournisseur ne propose plus.",
      "Créez des bons de commande depuis Inventaire → Bons de commande avec les produits liés uniquement.",
    ],
    when: "Lors de l’onboarding d’un fournisseur, de la mise à jour des SKU, ou avant un bon de commande.",
    tips: [
      "Liez les produits avant les BC — l’API refuse les lignes pour des SKU non liés.",
      "Réceptionnez (GRN) contre le BC pour garder stock et coût moyen exacts.",
    ],
  },
  "page.customers": {
    title: "Clients et Crédit",
    summary: "Profils clients, crédit/solde crédit, grand livre et points de fidélité.",
    what: "Stocke les détails du client et vous permet d'activer crédit, d'afficher le grand livre, de gérer les limites de crédit et d'ajuster les points de fidélité.",
    how: [
      "Ajoutez un client avec son nom et son téléphone.",
      "Activez crédit pour les ventes à crédit.",
      "Ouvrez Ledger pour voir les débits, les crédits et le solde impayé.",
      "Ajustez les points de fidélité pour les promotions ou les corrections.",
    ],
    when: "Pour les programmes CRM, de vente à crédit et de fidélité.",
    tips: [
      "Attachez le client à POS avant le paiement crédit.",
      "Vérifiez la limite de crédit avant les ventes crédit importantes.",
    ],
  },
  "page.sales": {
    title: "Historique des ventes",
    summary: "Liste complète des factures de ventes de la succursale sélectionnée.",
    what: "Affiche les paiements passés avec le numéro de facture, le client, le total, le statut et l'heure afin que vous puissiez rouvrir ou vérifier une vente.",
    how: [
      "Recherchez ou parcourez la liste des ventes.",
      "Ouvrez une ligne pour afficher les éléments de campagne et les paiements.",
      "Utilisez le numéro de facture lors du traitement d'un retour.",
    ],
    when: "Pour les demandes des clients, les audits, la réimpression des reçus ou avant un retour.",
    tips: ["Les ventes apparaissent après un paiement POS réussi."],
  },
  "page.returns": {
    title: "Retours et caisses",
    summary: "Remboursements sur les ventes passées et jusqu’à l’historique d’ouverture/fermeture.",
    what: "Le personnel peut rechercher une vente et soumettre un retour, et consulter les sessions de caisse, y compris les montants excédentaires/courts.",
    how: [
      "Recherchez par le numéro de facture de vente originale.",
      "Soumettez le retour avec la méthode de remboursement et le motif.",
      "Les gestionnaires approuvent ou rejettent les retours en attente.",
      "Examinez la trésorerie d'ouverture/de clôture et les écarts dans l'historique de la caisse.",
    ],
    when: "Lors de l'émission de remboursements, de la manipulation de marchandises endommagées ou du rapprochement des caisses.",
    tips: ["Conservez la facture originale : les retours renvoient à cette vente."],
  },
  "page.accounting": {
    title: "Comptabilité",
    summary: "IFRS-for-SMEs books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools aligned with IFRS for SMEs presentation: chart of accounts (create/edit), journals, trial balance, sectioned P&L and balance sheet, cash flow, general ledger, and receivables/payables aging.",
    how: [
      "Create or edit ledger accounts on Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, Cash flow, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Header accounts are for structure only—post to leaf accounts.",
    ],
  },
  "page.hr": {
    title: "RH et Paie",
    summary: "Exécutions des employés, des présences, des congés et de la paie.",
    what: "Gère les données de base du personnel, les présences, les demandes de congés, ainsi que le calcul et l'approbation de la paie.",
    how: [
      "Ajoutez des employés ou invitez des utilisateurs existants.",
      "Enregistrer les présences et examiner les demandes de congés.",
      "Exécutez la paie pour une période, puis approuvez-la.",
    ],
    when: "Pour l'embauche, la présence quotidienne, l'approbation des congés et les cycles de salaire.",
    tips: ["L’approbation de la paie peut nécessiter un rôle ou un ensemble spécifique."],
  },
  "page.marketing": {
    title: "Commercialisation",
    summary: "Campagnes, segments, coupons et niveaux de fidélité.",
    what: "Vous aide à envoyer des messages aux clients, à cibler des segments, à configurer des codes promotionnels et à configurer les taux de fidélité/d'échange.",
    how: [
      "Créez un brouillon de campagne avec une audience et un message.",
      "Envoyer lorsque vous êtes prêt : le statut de livraison apparaît sur la campagne.",
      "Créez des segments et des coupons pour des offres ciblées.",
      "Définissez des niveaux de fidélité en fonction de tranches de points.",
    ],
    when: "Pour les promotions, les offres de festival, les messages de reconquête et la configuration de la fidélité.",
    tips: ["Connectez les canaux clients pour une meilleure livraison."],
  },
  "page.reports": {
    title: "Rapports",
    summary: "Ventes opérationnelles et performance produits.",
    what: "Rapports de succursale tels que les ventes quotidiennes et les meilleurs produits. Les états financiers complets sont disponibles sous Comptabilité.",
    how: [
      "Choisissez une plage de dates.",
      "Passez en revue les ventes quotidiennes et le nombre de billets.",
      "Vérifiez les produits les plus vendus par quantité.",
    ],
    when: "Pour les revues hebdomadaires, les décisions de marchandisage ou les mises à jour des propriétaires.",
    tips: ["Comptabilité ouverte pour le P&L ou le bilan."],
  },
  "page.settings": {
    title: "Paramètres",
    summary: "Profil, limites du forfait, facturation, notifications, indicateurs FBR et rôles.",
    what: "Configuration de l'entreprise et du compte : profil, utilisation de l'abonnement, préférences de notification, intégrations et accès aux rôles (certains onglets sont réservés au propriétaire).",
    how: [
      "Mettez à jour votre profil sous l'onglet Profil.",
      "Examinez l'utilisation par rapport aux limites du forfait et effectuez une mise à niveau à partir des cartes de forfait.",
      "Les propriétaires peuvent gérer les intégrations, la marque et les rôles pour l'entreprise active.",
    ],
    when: "Lors de l'intégration, planifiez des mises à niveau ou lors de la modification de l'accès au module.",
    tips: ["Certains paramètres sont réservés au propriétaire : demandez au propriétaire s'il manque un onglet."],
  },
  "page.businesses": {
    title: "Entreprises",
    summary: "Créez et gérez des entreprises sous votre compte propriétaire.",
    what: "Liste des propriétaires d'entreprises avec création, ouverture de détails et désactivation logicielle.",
    how: [
      "Créez une entreprise avec un nom et un secteur d'activité.",
      "Ouvrez une entreprise pour modifier les détails, les succursales et l'image de marque.",
      "Désactivez-le lorsqu'un emplacement ferme : l'historique est conservé.",
    ],
    when: "Lors de l’expansion vers une nouvelle marque ou de la fermeture d’une entreprise.",
    tips: ["Les limites du forfait s'appliquent au nombre d'entreprises et de succursales que vous pouvez ajouter."],
  },
  "page.notifications": {
    title: "Notifications",
    summary: "Alertes de congés, de paie, de facturation et de campagne.",
    what: "Alertes du système et du flux de travail pour que les approbations et les résultats de la campagne ne soient pas manqués.",
    how: [
      "Ouvrez les notifications pour voir les éléments non lus.",
      "Cliquez sur une alerte liée pour accéder à l'écran associé.",
      "Ajustez les préférences dans Paramètres si les alertes sont trop bruyantes.",
    ],
    when: "Tout au long de la journée pour les approbations et les mises à jour opérationnelles.",
    tips: ["Gardez le panneau ouvert les jours de pointe afin que les demandes de congés et de paie restent visibles."],
  },
  "page.profile": {
    title: "Votre profil",
    summary: "Nom personnel, téléphone, mot de passe et photo.",
    what: "Met à jour votre compte utilisateur, et non les paramètres professionnels complets.",
    how: [
      "Changez le nom d’affichage et le téléphone.",
      "Définissez un nouveau mot de passe uniquement lorsque vous devez le modifier.",
      "Téléchargez une photo de profil lorsqu’elle est disponible.",
    ],
    when: "Lors de la première configuration de connexion ou lors de la mise à jour des informations personnelles.",
    tips: ["Changez la langue à partir du contrôle de langue de la barre latérale."],
  },
  "page.businessDetail": {
    title: "Détail de l'entreprise",
    summary: "Modifiez une entreprise : image de marque, place de marché et succursales.",
    what: "Outils propriétaires pour une identité commerciale et des emplacements uniques.",
    how: [
      "Mettez à jour le nom, le secteur d’activité, le slogan et la couleur de la marque.",
      "Téléchargez un logo et configurez la liste du marché.",
      "Ajoutez ou désactivez des branches selon vos besoins.",
    ],
    when: "Lors du lancement d’un magasin ou du rafraîchissement du look de la marque.",
    tips: ["La désactivation conserve les données financières historiques ; rien n'est définitivement supprimé."],
  },
  "page.ess": {
    title: "Outils du personnel (ESS)",
    summary: "Libre-service des employés pour les présences et les congés.",
    what: "Le personnel peut s'enregistrer/départ et soumettre des congés sans accès complet à l'administrateur RH.",
    how: [
      "Notez la présence d'aujourd'hui.",
      "Soumettez le congé avec les dates et le motif.",
      "Vérifiez le statut d'approbation après la soumission.",
    ],
    when: "Quotidien pour le personnel utilisant les RH en libre-service.",
    tips: ["Les managers approuvent toujours les congés à partir de l'onglet Congés RH."],
  },

  "tab.inventory.stock": {
    title: "Stock disponible",
    summary: "Quantité et coût moyen pour chaque produit dans cette succursale.",
    what: "Vue du solde des stocks après achats, ventes, transferts et ajustements.",
    how: [
      "Recherchez par SKU ou par nom de produit.",
      "Vérifiez la quantité avant de commander à nouveau.",
      "Comparez avec les produits si quelque chose ne va pas.",
    ],
    when: "Avant de passer des commandes, des contrôles ponctuels ou d’enquêter sur des pénuries.",
    tips: ["Le coût moyen est mis à jour lorsque les marchandises sont reçues."],
  },
  "tab.inventory.products": {
    title: "Produits",
    summary: "Articles en vente, services, prix et codes-barres.",
    what: "Créez et modifiez les produits utilisés dans POS et le suivi des stocks.",
    how: [
      "Ajoutez un produit avec SKU, nom et prix.",
      "Définissez un code-barres à numériser à la caisse.",
      "Ouvrez un produit pour afficher ou modifier les détails.",
    ],
    when: "Lors de l'ajout de nouveaux articles ou de la mise à jour des prix.",
    tips: ["Gardez les SKU uniques dans toute l’entreprise."],
  },
  "tab.inventory.suppliers": {
    title: "Fournisseurs",
    summary: "Maître des fournisseurs pour les achats.",
    what: "Contact du fournisseur, conditions de paiement et statut utilisés sur les bons de commande.",
    how: [
      "Ajoutez un fournisseur avec son nom et ses coordonnées.",
      "Définissez les conditions de paiement avant de créer un bon de commande.",
      "Ouvrez un fournisseur pour afficher tous les détails.",
    ],
    when: "Lors de la configuration des achats ou de la mise à jour des détails du fournisseur.",
    tips: ["N'utilisez pas de fournisseurs inactifs sur le nouveau POs."],
  },
  "tab.inventory.pos": {
    title: "Bons de commande",
    summary: "Commandes fournisseurs et entrée de marchandises (GRN).",
    what: "Créez POs, suivez le statut et recevez les quantités en stock.",
    how: [
      "Créez un bon de commande avec un fournisseur et des éléments de campagne.",
      "Réceptionner les marchandises contre le bon de commande à l'arrivée du stock (GRN).",
      "Ouvrez un bon de commande pour consulter les lignes et le statut.",
    ],
    when: "Lors d’une commande de stock auprès d’un fournisseur.",
    tips: ["Recevez uniquement ce qui est arrivé : les reçus partiels sont pris en charge."],
  },
  "tab.inventory.transfers": {
    title: "Transferts",
    summary: "Déplacez le stock entre les succursales.",
    what: "Crée un document de transfert qui doit être confirmé pour que le stock passe d'une succursale à une autre.",
    how: [
      "Choisissez la succursale de destination, le produit et la quantité.",
      "Créez le transfert et confirmez une fois les marchandises déplacées.",
    ],
    when: "Lors de l’équilibrage des stocks entre les sites.",
    tips: ["Confirmez rapidement afin que les quantités disponibles restent exactes."],
  },
  "tab.inventory.adjust": {
    title: "Ajustement des stocks",
    summary: "Corrigez la quantité pour les dommages, les écarts de comptage ou les radiations.",
    what: "Modifie la quantité (+/−) avec un code motif pour audit.",
    how: [
      "Choisissez le produit et le delta de quantité.",
      "Sélectionnez un code motif.",
      "Enregistrez pour mettre à jour le stock disponible.",
    ],
    when: "Après un comptage physique ou lorsque des marchandises sont endommagées ou perdues.",
    tips: ["Préférez GRN/transferts pour un mouvement normal ; utilisez Ajuster pour les corrections."],
  },

  "tab.accounting.coa": {
    title: "Plan comptable",
    summary: "IFRS-for-SMEs ledger accounts for journals and statements.",
    what: "Hierarchical list of account codes with type, classification, and normal balance. Create new accounts or edit existing ones.",
    how: [
      "Use New account to add a postable or header account.",
      "Browse by code; indent shows parent hierarchy.",
      "Edit an account to change labels or classification.",
    ],
    when: "During setup review or when you need a new ledger account.",
    tips: [
      "Do not delete accounts that already have postings.",
    ],
  },
  "tab.accounting.journals": {
    title: "Journaux",
    summary: "Écritures de journal manuelles et système.",
    what: "Affiche les journaux publiés et vous permet de publier des écritures manuelles équilibrées.",
    how: [
      "Ouvrez un journal pour afficher les lignes de débit/crédit.",
      "Utilisez le journal de publication pour un ajustement sur deux lignes si nécessaire.",
    ],
    when: "Pour les corrections, les régularisations ou la révision des entrées publiées automatiquement.",
    tips: ["Les débits doivent être égaux aux crédits avant la comptabilisation."],
  },
  "tab.accounting.tb": {
    title: "Balance de vérification",
    summary: "Totaux de débit/crédit par compte pour une période.",
    what: "Vérifie que les livres sont équilibrés avant d’exécuter des relevés.",
    how: ["Définissez les dates du/au.", "Vérifiez les totaux du compte."],
    when: "En fin de mois ou avant P&L/bilan.",
    tips: ["Enquêtez sur des soldes étonnamment importants."],
  },
  "tab.accounting.pl": {
    title: "Compte de résultat",
    summary: "Sectioned income statement (IFRS for SMEs).",
    what: "Revenue, cost of sales, operating expenses, and net income for the selected period.",
    how: [
      "Choose dates.",
      "Review sections and subtotals (gross / operating / net).",
    ],
    when: "For owner review and period close.",
    tips: [
      "Accuracy depends on correct account classifications and postings.",
    ],
  },
  "tab.accounting.bs": {
    title: "Bilan",
    summary: "Sectioned statement of financial position.",
    what: "Current and non-current assets/liabilities plus equity as of the report date.",
    how: [
      "Set the as-of date.",
      "Review current vs non-current sections.",
    ],
    when: "For period close and financial discussions.",
    tips: [
      "AR/AP aging complements customer and supplier balances.",
    ],
  },
  "tab.accounting.cf": {
    title: "Flux de trésorerie",
    summary: "Indirect cash flow summary for a period.",
    what: "Starts from net income and adjusts for working-capital changes (AR, inventory, AP).",
    how: [
      "Choose dates.",
      "Review cash from operations.",
    ],
    when: "For cash planning alongside P&L and balance sheet.",
    tips: [
      "This is a simplified indirect method—not a full IAS 7 statement.",
    ],
  },

  "tab.accounting.gl": {
    title: "Grand livre général",
    summary: "Activité ligne par ligne pour un compte.",
    what: "Historique de débit/crédit pour un seul compte.",
    how: ["Sélectionnez un compte.", "Fixez des dates.", "Examinez chaque publication."],
    when: "Lors de l’enquête sur les soldes ou du rapprochement d’un compte.",
    tips: ["Exécutez d'abord la balance de vérification, puis ouvrez GL pour les comptes impairs."],
  },
  "tab.accounting.ar": {
    title: "Vieillissement de la RA",
    summary: "Créances clients par tranche d’âge.",
    what: "Soldes de factures ouvertes regroupés par âge (actuel, 30, 60 jours, etc.).",
    how: ["Examinez les compartiments.", "Ouvrez une facture pour plus de détails.", "Effectuer le suivi auprès du client."],
    when: "Pour les recouvrements et le contrôle du crédit.",
    tips: ["Les ventes Crédit/à crédit peuvent apparaître dans AR."],
  },
  "tab.accounting.ap": {
    title: "Vieillissement AP",
    summary: "Dettes fournisseurs par tranche d’âge.",
    what: "Factures que vous devez, regroupées par date d'échéance.",
    how: ["Examinez les compartiments.", "Ouvrez une facture pour plus de détails.", "Planifier les paiements des fournisseurs."],
    when: "Pour le paiement des fournisseurs et la planification de la trésorerie.",
    tips: ["Les reçus de bon de commande créent souvent des factures AP."],
  },

  "tab.hr.employees": {
    title: "Employés",
    summary: "Liste principale du personnel et détails de l'emploi.",
    what: "Créez des dossiers d'employés, modifiez le salaire de base et ouvrez des profils.",
    how: [
      "Ajoutez un employé ou invitez un utilisateur existant.",
      "Modifiez le titre, le salaire et le statut.",
      "Ouvrez un employé pour plus de détails.",
    ],
    when: "Pour l'embauche, les changements de rôle ou les mises à jour de salaire.",
    tips: ["L'invitation relie l'enregistrement RH à l'accès à la connexion."],
  },
  "tab.hr.attendance": {
    title: "Participation",
    summary: "Historique d’arrivée/départ.",
    what: "Lignes de présence pour la paie et la conformité.",
    how: ["Filtrer par date.", "Corrigez les poinçons manquants via ESS ou un manager."],
    when: "Pour les opérations quotidiennes et avant la paie.",
    tips: ["La source peut être ESS ou une entrée du gestionnaire."],
  },
  "tab.hr.leave": {
    title: "Partir",
    summary: "Laissez les demandes et les approbations.",
    what: "Les responsables approuvent ou rejettent les congés en fonction des autorisations des rôles.",
    how: [
      "Examinez les demandes en attente.",
      "Approuvez ou rejetez soigneusement.",
      "Confirmez les dates avec l'employé si elles ne sont pas claires.",
    ],
    when: "Lorsque le personnel demande un congé.",
    tips: ["L’approbation dépend de l’accès Leave_approve."],
  },
  "tab.hr.payroll": {
    title: "Paie",
    summary: "La paie s'exécute pour une période sélectionnée.",
    what: "Générez la paie, consultez les exécutions et approuvez lorsque cela est autorisé.",
    how: [
      "Définir le début et la fin de la période.",
      "Exécutez la paie.",
      "Ouvrez les détails et approuvez si vous avez des droits.",
    ],
    when: "À la clôture du cycle salarial.",
    tips: ["Résolvez les problèmes de présence/congés avant d’exécuter la paie."],
  },

  "page.marketing.template": {
    title: "Modèle de message",
    summary: "Aperçu de l’apparence d’un modèle CRM pour les clients.",
    what: "Affiche les variables brutes et un aperçu interpolé avec la marque et des valeurs d’exemple.",
    how: [
      "Ouvrez un modèle dans Marketing → Modèles.",
      "Vérifiez les variables dans l’aperçu.",
      "Contrôlez l’aperçu client.",
      "Retour rouvre l’onglet Modèles.",
    ],
    when: "Lors de la rédaction de messages de campagne réutilisables.",
    tips: ["Les variables sont des clés plates comme {{business}} — {{customer.name}} n’est pas pris en charge."],
  },

  "tab.marketing.campaigns": {
    title: "Campagnes",
    summary: "Rédiger et envoyer des messages clients.",
    what: "Créez des campagnes marketing, choisissez votre audience et envoyez-les avec un récapitulatif de livraison.",
    how: [
      "Créez un brouillon de campagne.",
      "Examinez l’audience et le message.",
      "Envoyez lorsque vous êtes prêt et ouvrez les résultats pour plus de détails.",
    ],
    when: "Pour les promotions et la sensibilisation des clients.",
    tips: ["Les brouillons peuvent être modifiés avant l’envoi."],
  },
  "tab.marketing.segments": {
    title: "Segments",
    summary: "Audiences de clients enregistrées pour le ciblage.",
    what: "Filtres réutilisables pour les campagnes (par exemple par fidélité).",
    how: ["Créez un segment avec des filtres.", "Réutilisez-le lors de la composition d’une campagne."],
    when: "Pour des offres ciblées au lieu de faire exploser tout le monde.",
    tips: ["Gardez les noms de segments descriptifs."],
  },
  "tab.marketing.coupons": {
    title: "Coupons",
    summary: "Codes promotionnels pour le paiement POS.",
    what: "Les caissiers peuvent saisir des codes de réduction dans le panier.",
    how: [
      "Créez un code et une valeur de réduction.",
      "Partagez avec les clients.",
      "Entrez le code sur POS avant de procéder au paiement.",
    ],
    when: "Pour les campagnes de réduction et les offres partenaires.",
    tips: [
      "Définissez des limites d'utilisation afin que les codes ne soient pas utilisés de manière excessive.",
      "Laissez Valide du/au vide pour aucune limite de dates ; une fenêtre expirée échoue au POS.",
    ],
  },
  "tab.marketing.tiers": {
    title: "Niveaux de fidélité",
    summary: "Gagnez/échangez des taux par tranche de points.",
    what: "Configure la rapidité avec laquelle les clients gagnent et échangent des points.",
    how: [
      "Ajoutez un niveau avec un minimum de points.",
      "Définissez des multiplicateurs de gain/échange.",
      "Testez avec un échantillon de client.",
    ],
    when: "Lors du lancement ou du réglage de la fidélité.",
    tips: ["Les niveaux supérieurs gagnent généralement plus rapidement : communiquez-le aux clients."],
  },

  "tab.settings.notifications": {
    title: "Préférences de notifications",
    summary: "Choisissez les alertes que vous recevez.",
    what: "Bascule par utilisateur pour les types de notification.",
    how: ["Ouvrez l'onglet Notifications dans Paramètres.", "Activez ou désactivez les types selon vos besoins."],
    when: "Lorsque les alertes sont trop bruyantes ou que des éléments importants sont manqués.",
    tips: ["Ces préférences s'appliquent à votre utilisateur, et non à l'ensemble de l'entreprise."],
  },
  "tab.settings.profile": {
    title: "Profil",
    summary: "Votre nom, téléphone, mot de passe et photo.",
    what: "Détails du compte personnel de l'utilisateur connecté.",
    how: [
      "Mettez à jour le nom d’affichage et le téléphone.",
      "Téléchargez une photo de profil.",
      "Définissez un nouveau mot de passe uniquement lorsque cela est nécessaire.",
    ],
    when: "Lors de la première connexion ou lorsque les données personnelles changent.",
  },
  "tab.settings.subscriptions": {
    title: "Abonnement et utilisation",
    summary: "Statut du plan et limites de sièges/succursales.",
    what: "Forfait actuel, statut, utilisation par rapport aux limites et paiement de la mise à niveau Safepay (JazzCash, Easypaisa ou carte).",
    how: [
      "Examinez les compteurs d’utilisation.",
      "Choisissez un forfait et payez avec JazzCash, Easypaisa ou une carte pour mettre à niveau.",
    ],
    when: "À l’approche des limites ou au renouvellement de la facturation.",
    tips: ["L'accès propriétaire est requis pour cet onglet."],
  },
  "tab.businesses.details": {
    title: "Détails de l'entreprise",
    summary: "Nom, secteur d’activité et juridiction fiscale.",
    what: "Champs d’identité de base pour l’entreprise sélectionnée.",
    how: ["Modifiez les champs et enregistrez.", "Utilisez Désactiver lorsque l’entreprise doit arrêter ses opérations."],
    when: "Lors du renommage ou de la correction des métadonnées commerciales.",
  },
  "tab.businesses.branches": {
    title: "Succursales",
    summary: "Emplacements sous cette entreprise.",
    what: "Créez et désactivez en douceur des branches dans les limites du plan.",
    how: ["Ajoutez une branche avec un nom.", "Désactivez les emplacements fermés."],
    when: "Ouvrir une nouvelle caisse ou en fermer une.",
  },
  "tab.businesses.branding": {
    title: "Image de marque de l'entreprise",
    summary: "Logo, slogan, couleur et copie du marché.",
    what: "Identité visuelle utilisée sur la place de marché et l'interface utilisateur du personnel pour cette entreprise.",
    how: ["Téléchargez un logo.", "Choisissez une couleur de marque.", "Sauvez l’image de marque."],
    when: "Avant de s'inscrire sur la Marketplace ou de rafraîchir l'identité de la marque.",
  },
  "tab.settings.integrations": {
    title: "Intégrations",
    summary: "Connexions externes et indicateurs de conformité.",
    what: "Outils propriétaires pour connecter les services pour l'entreprise (par exemple, les indicateurs FBR).",
    how: ["Vérifiez les paramètres d’intégration disponibles.", "Changez les drapeaux uniquement lorsque vous comprenez l’impact."],
    when: "Lors de la mise en place d’intégrations ou de conformité.",
    tips: ["Des indicateurs erronés peuvent affecter la déclaration fiscale : confirmez auprès de votre comptable."],
  },
  "tab.settings.roles": {
    title: "Rôles",
    summary: "Qui peut accéder à quels modules.",
    what: "Configuration propriétaire de l'accès basé sur les rôles sur les bundles Kaarobar.",
    how: ["Passez en revue les attributions de rôles.", "Changez-le avec précaution : le personnel pourrait perdre l’accès."],
    when: "Lors de l’embauche, de la promotion ou du renforcement de la sécurité.",
    tips: ["Moindre privilège : accordez à chaque rôle uniquement les bundles dont il a besoin."],
  },
  "tab.settings.branding": {
    title: "Image de marque du magasin",
    summary: "Logo, couleurs et liste de places de marché pour votre entreprise.",
    what: "Contrôle l'apparence de votre boutique dans Discover/catalogue et remappe le schéma d'interface utilisateur de l'application (boutons, bagues de mise au point, navigation) à partir de la couleur primaire.",
    how: [
      "Téléchargez un logo et choisissez une couleur principale de marque.",
      "Ajoutez un slogan et une description du marché.",
      "Enregistrez la marque, puis prévisualisez Discover ou achetez en tant que consommateur.",
    ],
    when: "Avant d'être mis en ligne sur le marché ou de rafraîchir le look de la marque.",
    tips: ["L'accès du propriétaire est requis. L’enregistrement de la marque met immédiatement à jour le thème de l’espace de travail du personnel."],
  },
  "tab.marketing.templates": {
    title: "Modèles de messages",
    summary: "Corps de message CRM réutilisables avec variables.",
    what: "Modèles enregistrés pour les campagnes et les aperçus (nom de l'entreprise, slogan, etc.).",
    how: [
      "Créez ou modifiez un modèle avec des espaces réservés.",
      "Aperçu avec des exemples de variables métier.",
      "Sélectionnez le modèle lors de la composition d'une campagne.",
    ],
    when: "Lors de la standardisation des messages promotionnels ou transactionnels.",
    tips: ["Gardez les modèles courts pour les canaux SMS/WhatsApp."],
  },
  "page.appointments": {
    title: "Rendez-vous",
    summary: "Planning quotidien du personnel pour les prestations réservées.",
    what: "Affiche les rendez-vous de la date sélectionnée et, si besoin, d’un professionnel précis. Les réservations peuvent être terminées ou annulées ; leur achèvement peut préparer une vente POS liée (SCH-FR-005).",
    how: [
      "Choisissez une date et filtrez éventuellement par professionnel.",
      "Recherchez ou filtrez par statut.",
      "Appuyez sur Terminer pour clôturer une visite, ou sur Annuler pour un rendez-vous réservé.",
    ],
    when: "Pendant la journée de service dans les salons et autres établissements où les rendez-vous sont activés.",
    tips: ["Les clients réservent via Réserver sur la place de marché ; le personnel gère ici le planning du jour."],
  },
};

export default catalog;
