import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Painel",
    summary: "KPIs e gráficos interativos de vendas filtrados por período.",
    what: "Mostra vendas de hoje, posição de caixa, estoque baixo, aprovações pendentes e tendências de receita/pedidos no período selecionado.",
    how: [
      "Após entrar, revise os cartões de KPI do dia.",
      "Defina de/até para atualizar os gráficos de receita e pedidos.",
      "Passe o mouse em um ponto para ver o total diário ou o número de tickets.",
      "Use estoque baixo ou aprovações para ir a Inventário ou Devoluções.",
      "Troque empresa ou filial no cabeçalho se gerenciar vários locais.",
    ],
    when: "No início do turno, no final do dia ou sempre que precisar de um exame de saúde na agência.",
    tips: [
      "Os gráficos usam vendas concluídas da empresa selecionada (RPT-FR-001).",
      "Se os gráficos estiverem vazios, amplie o período ou confira o caixa.",
    ],
  },
  "page.pos": {
    title: "Ponto de Venda",
    summary: "Check-out rápido com carrinho, cliente e pagamento.",
    what: "Os caixas podem vender produtos, fidelizar clientes ou crédito (crédito), aplicar descontos ou cupons e receber pagamentos em dinheiro, cartão, carteira ou crédito.",
    how: [
      "Abra uma caixa registradora antes de realizar vendas à vista.",
      "Adicione produtos ao carrinho por pesquisa ou leitura de código de barras.",
      "Anexe um cliente quando necessário para fidelização ou crédito.",
      "Revise o total, toque em Prosseguir para finalização da compra e escolha uma forma de pagamento.",
      "Conclua o pedido com Fazer pedido e imprima ou compartilhe o recibo.",
    ],
    when: "Para cada checkout do cliente no balcão.",
    tips: [
      "O pagamento Crédito requer um crédito ativo no cliente.",
      "Mantenha a caixa aberta durante o turno e conte o dinheiro antes de fechar no final do dia.",
    ],
  },
  "page.inventory": {
    title: "Estoque e compras",
    summary: "Catálogo, estoque disponível, fornecedores, pedidos de compra, transferências e ajustes.",
    what: "O local para manter produtos, visualizar níveis de estoque, comprar de fornecedores, movimentar estoque entre filiais e corrigir quantidades.",
    how: [
      "Crie ou atualize SKUs e preços de Produtos.",
      "Visualize a quantidade disponível e o custo médio do estoque.",
      "Adicione fornecedores, crie pedidos de compra e receba mercadorias (GRN).",
      "Use Transferências para movimentar o estoque entre filiais e Ajustar para fixar quantidades.",
    ],
    when: "No recebimento de mercadorias, na adição de novos itens, na contagem de estoque ou na transferência entre filiais.",
    tips: [
      "Receba contra uma ordem de compra para que o custo e as contas a pagar permaneçam precisos.",
      "Use um código de motivo claro em Ajustar para trilhas de auditoria.",
    ],
  },
  "page.inventory.supplier": {
    title: "Detalhes do fornecedor",
    summary: "Contato, condições e produtos vinculados para pedidos de compra.",
    what: "Cada fornecedor guarda dados da empresa e contato, além de uma lista explícita de produtos do catálogo que pode fornecer. Ao criar um pedido, só aparecem produtos vinculados (INV-FR).",
    how: [
      "Abra um fornecedor em Estoque → Fornecedores.",
      "Revise contato, endereço e condições de pagamento.",
      "Vincule produtos do catálogo que este fornecedor atende.",
      "Desvincule produtos que o fornecedor não fornece mais.",
      "Crie pedidos em Estoque → Pedidos de compra usando apenas produtos vinculados.",
    ],
    when: "Ao cadastrar um fornecedor, atualizar quais SKUs ele fornece ou antes de criar um pedido.",
    tips: [
      "Vincule produtos antes dos pedidos — a API rejeita linhas de SKUs não vinculados.",
      "Receba mercadorias (GRN) contra o pedido para manter estoque e custo médio corretos.",
    ],
  },
  "page.customers": {
    title: "Clientes e Crédito",
    summary: "Perfis de clientes, saldo de crédito/crédito, razão e pontos de fidelidade.",
    what: "Armazena detalhes do cliente e permite ativar crédito, visualizar o razão, gerenciar limites de crédito e ajustar pontos de fidelidade.",
    how: [
      "Adicione um cliente com nome e telefone.",
      "Habilite crédito para vendas a crédito.",
      "Abra o Ledger para ver débitos, créditos e saldo pendente.",
      "Ajuste pontos de fidelidade para promoções ou correções.",
    ],
    when: "Para CRM, vendas a crédito e programas de fidelidade.",
    tips: [
      "Anexe o cliente em POS antes do pagamento crédito.",
      "Verifique o limite de crédito antes de grandes vendas crédito.",
    ],
  },
  "page.sales": {
    title: "Histórico de vendas",
    summary: "Lista completa de faturas de vendas da filial selecionada.",
    what: "Mostra checkouts anteriores com número da fatura, cliente, total, status e horário para que você possa reabrir ou verificar uma venda.",
    how: [
      "Pesquise ou navegue na lista de vendas.",
      "Abra uma linha para visualizar itens de linha e pagamentos.",
      "Use o número da fatura ao processar uma devolução.",
    ],
    when: "Para consultas de clientes, auditorias, reimpressão de recibos ou antes de uma devolução.",
    tips: ["As vendas aparecem após uma finalização de compra POS bem-sucedida."],
  },
  "page.returns": {
    title: "Devoluções e caixas",
    summary: "Reembolsos em vendas anteriores e até o histórico de abertura/fechamento.",
    what: "A equipe pode procurar uma venda e enviar uma devolução, além de visualizar sessões de caixa incluindo valores acima/aquém.",
    how: [
      "Pesquise pelo número da fatura de venda original.",
      "Envie a devolução com método de reembolso e motivo.",
      "Os gerentes aprovam ou rejeitam devoluções pendentes.",
      "Revise o caixa de abertura/fechamento e a variação no histórico de caixa.",
    ],
    when: "Ao emitir reembolsos, manusear mercadorias danificadas ou reconciliar caixas registradoras.",
    tips: ["Guarde a fatura original – devolve o link para essa venda."],
  },
  "page.accounting": {
    title: "Contabilidade",
    summary: "IFRS-for-SMEs books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools aligned with IFRS for SMEs presentation: chart of accounts (create/edit), journals, trial balance, sectioned P&L and balance sheet, cash flow, general ledger, and receivables/payables aging.",
    how: [
      "Create or edit ledger accounts on Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, Cash flow, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Header accounts are for structure only—post to leaf accounts.",
    ],
  },
  "page.hr": {
    title: "RH e folha de pagamento",
    summary: "Funcionários, frequência, licenças e execução de folha de pagamento.",
    what: "Gerencia dados mestre de pessoal, frequência, solicitações de licença e cálculo e aprovação de folha de pagamento.",
    how: [
      "Adicione funcionários ou convide usuários existentes.",
      "Registre a presença e analise os pedidos de licença.",
      "Execute a folha de pagamento por um período e depois aprove-a.",
    ],
    when: "Para contratações, atendimento diário, aprovação de licenças e ciclos salariais.",
    tips: ["A aprovação da folha de pagamento pode exigir uma função ou pacote específico."],
  },
  "page.marketing": {
    title: "Comercialização",
    summary: "Campanhas, segmentos, cupons e níveis de fidelidade.",
    what: "Ajuda você a enviar mensagens aos clientes, segmentar segmentos, configurar códigos promocionais e configurar taxas de ganho/resgate de fidelidade.",
    how: [
      "Crie um rascunho de campanha com público e mensagem.",
      "Envie quando estiver pronto: o status da entrega aparece na campanha.",
      "Crie segmentos e cupons para ofertas direcionadas.",
      "Defina níveis de fidelidade com base em faixas de pontos.",
    ],
    when: "Para promoções, ofertas de festivais, mensagens de reconquista e configuração de fidelidade.",
    tips: ["Conecte os canais do cliente para uma melhor entrega."],
  },
  "page.reports": {
    title: "Relatórios",
    summary: "Vendas operacionais e desempenho do produto.",
    what: "Relatórios de filiais, como vendas diárias e principais produtos. As demonstrações financeiras completas estão em Contabilidade.",
    how: [
      "Escolha um intervalo de datas.",
      "Revise as vendas diárias e a contagem de ingressos.",
      "Verifique os produtos mais vendidos por quantidade.",
    ],
    when: "Para análises semanais, decisões de merchandising ou atualizações do proprietário.",
    tips: ["Contabilidade aberta para lucros e perdas ou balanço."],
  },
  "page.settings": {
    title: "Configurações",
    summary: "Perfil, limites do plano, cobrança, notificações, sinalizadores FBR e funções.",
    what: "Configuração comercial e de conta: perfil, uso de assinatura, preferências de notificação, integrações e acesso a funções (algumas guias são exclusivas do proprietário).",
    how: [
      "Atualize seu perfil na guia Perfil.",
      "Revise o uso em relação aos limites do plano e faça upgrade dos cartões do plano.",
      "Os proprietários podem gerenciar integrações, marcas e funções para o negócio ativo.",
    ],
    when: "Durante a integração, planeje atualizações ou ao alterar o acesso ao módulo.",
    tips: ["Algumas configurações são exclusivas do proprietário. Pergunte ao proprietário se alguma guia estiver faltando."],
  },
  "page.businesses": {
    title: "Negócios",
    summary: "Crie e gerencie empresas com sua conta de proprietário.",
    what: "Lista de proprietários de empresas com criação, detalhes abertos e desativação suave.",
    how: [
      "Crie um negócio com nome e setor.",
      "Abra uma empresa para editar detalhes, filiais e marca.",
      "Desative quando um local fechar – o histórico é mantido.",
    ],
    when: "Ao expandir para uma nova marca ou encerrar um negócio.",
    tips: ["Os limites do plano se aplicam a quantas empresas e filiais você pode adicionar."],
  },
  "page.notifications": {
    title: "Notificações",
    summary: "Alertas de licença, folha de pagamento, cobrança e campanha.",
    what: "Alertas de sistema e fluxo de trabalho para que aprovações e resultados de campanhas não sejam perdidos.",
    how: [
      "Abra Notificações para ver os itens não lidos.",
      "Clique em um alerta vinculado para ir para a tela relacionada.",
      "Ajuste as preferências em Configurações se os alertas forem muito barulhentos.",
    ],
    when: "Durante todo o dia para aprovações e atualizações operacionais.",
    tips: ["Mantenha o painel aberto em dias movimentados para que as solicitações de licença e folha de pagamento fiquem visíveis."],
  },
  "page.profile": {
    title: "Seu perfil",
    summary: "Nome pessoal, telefone, senha e foto.",
    what: "Atualiza sua conta de usuário, não as configurações comerciais completas.",
    how: [
      "Altere o nome de exibição e o telefone.",
      "Defina uma nova senha somente quando precisar alterá-la.",
      "Carregue uma foto de perfil quando disponível.",
    ],
    when: "Na primeira configuração de login ou ao atualizar dados pessoais.",
    tips: ["Altere o idioma no controle de idioma da barra lateral."],
  },
  "page.businessDetail": {
    title: "Detalhe do negócio",
    summary: "Edite um negócio: marca, mercado e filiais.",
    what: "Ferramentas do proprietário para uma única identidade comercial e locais.",
    how: [
      "Atualize o nome, o setor, o slogan e a cor da marca.",
      "Faça upload de um logotipo e configure a listagem do mercado.",
      "Adicione ou desative ramificações conforme necessário.",
    ],
    when: "Ao lançar uma loja ou renovar o visual da marca.",
    tips: ["A desativação mantém dados financeiros históricos; nada é excluído permanentemente."],
  },
  "page.ess": {
    title: "Ferramentas de equipe (ESS)",
    summary: "Autoatendimento dos funcionários para comparecimento e licenças.",
    what: "A equipe pode fazer check-in/out e enviar licença sem acesso total do administrador de RH.",
    how: [
      "Marque a presença de hoje.",
      "Envie a licença com datas e motivo.",
      "Verifique o status de aprovação após o envio.",
    ],
    when: "Diariamente para funcionários que usam RH de autoatendimento.",
    tips: ["Os gerentes ainda aprovam licenças na guia Licenças de RH."],
  },

  "tab.inventory.stock": {
    title: "Estoque disponível",
    summary: "Quantidade e custo médio de cada produto desta filial.",
    what: "Visualização do saldo do estoque após compras, vendas, transferências e ajustes.",
    how: [
      "Pesquise por SKU ou nome do produto.",
      "Revise a quantidade antes de fazer um novo pedido.",
      "Compare com Produtos se algo parecer errado.",
    ],
    when: "Antes de fazer pedidos, verificações pontuais ou investigar faltas.",
    tips: ["O custo médio é atualizado quando as mercadorias são recebidas."],
  },
  "tab.inventory.products": {
    title: "Produtos",
    summary: "Itens de venda, serviços, preços e códigos de barras.",
    what: "Crie e edite produtos usados em POS e rastreamento de estoque.",
    how: [
      "Adicione um produto com SKU, nome e preço.",
      "Defina um código de barras para leitura na finalização da compra.",
      "Abra um produto para visualizar ou editar detalhes.",
    ],
    when: "Ao adicionar novos itens ou atualizar preços.",
    tips: ["Mantenha os SKUs exclusivos em toda a empresa."],
  },
  "tab.inventory.suppliers": {
    title: "Fornecedores",
    summary: "Mestre de fornecedores para compras.",
    what: "Contato do fornecedor, condições de pagamento e status utilizados nos pedidos de compra.",
    how: [
      "Adicione um fornecedor com nome e detalhes de contato.",
      "Defina as condições de pagamento antes de criar um pedido.",
      "Abra um fornecedor para ver todos os detalhes.",
    ],
    when: "Ao configurar a compra ou atualizar detalhes do fornecedor.",
    tips: ["Não use fornecedores inativos no novo POs."],
  },
  "tab.inventory.pos": {
    title: "Pedidos de compra",
    summary: "Pedidos de fornecedores e entrada de mercadorias (GRN).",
    what: "Crie POs, acompanhe o status e receba as quantidades em estoque.",
    how: [
      "Crie um pedido de compra com fornecedor e itens de linha.",
      "Receber mercadorias contra o pedido quando o estoque chegar (GRN).",
      "Abra um pedido de compra para revisar linhas e status.",
    ],
    when: "Ao reordenar estoque de um fornecedor.",
    tips: ["Receba apenas o que chegou – recebimentos parciais são suportados."],
  },
  "tab.inventory.transfers": {
    title: "Transferências",
    summary: "Mova o estoque entre filiais.",
    what: "Cria um documento de transferência que deve ser confirmado para que o estoque passe de uma filial para outra.",
    how: [
      "Escolha a filial de destino, o produto e a quantidade.",
      "Crie a transferência e confirme assim que as mercadorias forem movimentadas.",
    ],
    when: "Ao equilibrar o estoque entre locais.",
    tips: ["Confirme imediatamente para que as quantidades disponíveis permaneçam precisas."],
  },
  "tab.inventory.adjust": {
    title: "Ajuste de estoque",
    summary: "Quantidade correta para danos, variação de contagem ou baixas.",
    what: "Altera a quantidade (+/−) com um código de motivo para auditoria.",
    how: [
      "Escolha o delta do produto e da quantidade.",
      "Selecione um código de motivo.",
      "Salve para atualizar o estoque disponível.",
    ],
    when: "Após uma contagem física ou quando as mercadorias são danificadas ou perdidas.",
    tips: ["Prefira GRN/transferências para movimento normal; use Ajustar para correções."],
  },

  "tab.accounting.coa": {
    title: "Plano de contas",
    summary: "IFRS-for-SMEs ledger accounts for journals and statements.",
    what: "Hierarchical list of account codes with type, classification, and normal balance. Create new accounts or edit existing ones.",
    how: [
      "Use New account to add a postable or header account.",
      "Browse by code; indent shows parent hierarchy.",
      "Edit an account to change labels or classification.",
    ],
    when: "During setup review or when you need a new ledger account.",
    tips: [
      "Do not delete accounts that already have postings.",
    ],
  },
  "tab.accounting.journals": {
    title: "Diários",
    summary: "Lançamentos manuais e do sistema.",
    what: "Mostra diários lançados e permite lançar lançamentos manuais balanceados.",
    how: [
      "Abra um diário para visualizar as linhas de débito/crédito.",
      "Use Postar diário para um ajuste de duas linhas quando necessário.",
    ],
    when: "Para correções, acréscimos ou revisão de entradas postadas automaticamente.",
    tips: ["Os débitos devem ser iguais aos créditos antes da postagem."],
  },
  "tab.accounting.tb": {
    title: "Balancete",
    summary: "Totais de débito/crédito em conta para um período.",
    what: "Verifica se os livros estão equilibrados antes de executar as declarações.",
    how: ["Defina datas de/até.", "Revise os totais da conta."],
    when: "No final do mês ou antes do resultado/balanço.",
    tips: ["Investigue saldos inesperadamente grandes."],
  },
  "tab.accounting.pl": {
    title: "DRE",
    summary: "Sectioned income statement (IFRS for SMEs).",
    what: "Revenue, cost of sales, operating expenses, and net income for the selected period.",
    how: [
      "Choose dates.",
      "Review sections and subtotals (gross / operating / net).",
    ],
    when: "For owner review and period close.",
    tips: [
      "Accuracy depends on correct account classifications and postings.",
    ],
  },
  "tab.accounting.bs": {
    title: "Balanço patrimonial",
    summary: "Sectioned statement of financial position.",
    what: "Current and non-current assets/liabilities plus equity as of the report date.",
    how: [
      "Set the as-of date.",
      "Review current vs non-current sections.",
    ],
    when: "For period close and financial discussions.",
    tips: [
      "AR/AP aging complements customer and supplier balances.",
    ],
  },
  "tab.accounting.cf": {
    title: "Fluxo de caixa",
    summary: "Indirect cash flow summary for a period.",
    what: "Starts from net income and adjusts for working-capital changes (AR, inventory, AP).",
    how: [
      "Choose dates.",
      "Review cash from operations.",
    ],
    when: "For cash planning alongside P&L and balance sheet.",
    tips: [
      "This is a simplified indirect method—not a full IAS 7 statement.",
    ],
  },

  "tab.accounting.gl": {
    title: "Razão Geral",
    summary: "Atividade linha por linha para uma conta.",
    what: "Histórico de débito/crédito para uma única conta.",
    how: ["Selecione uma conta.", "Defina datas.", "Revise cada postagem."],
    when: "Ao investigar saldos ou reconciliar uma conta.",
    tips: ["Execute o balancete primeiro e, em seguida, abra o GL para contas ímpares."],
  },
  "tab.accounting.ar": {
    title: "Envelhecimento em RA",
    summary: "Contas a receber de clientes por faixa etária.",
    what: "Saldos de faturas em aberto agrupados por idade (atual, 30, 60 dias, etc.).",
    how: ["Revise os baldes.", "Abra uma fatura para obter detalhes.", "Acompanhe o cliente."],
    when: "Para cobranças e controle de crédito.",
    tips: ["Crédito/vendas a crédito podem aparecer em AR."],
  },
  "tab.accounting.ap": {
    title: "Envelhecimento AP",
    summary: "Contas a pagar do fornecedor por faixa etária.",
    what: "Contas que você deve, agrupadas por data de vencimento.",
    how: ["Revise os baldes.", "Abra uma fatura para obter detalhes.", "Planeje pagamentos de fornecedores."],
    when: "Para pagamento de fornecedores e planejamento de caixa.",
    tips: ["Os recibos de PO geralmente criam contas de contas a pagar."],
  },

  "tab.hr.employees": {
    title: "Funcionários",
    summary: "Lista mestre de funcionários e detalhes de emprego.",
    what: "Crie registros de funcionários, edite o salário base e abra perfis.",
    how: [
      "Adicione um funcionário ou convide um usuário existente.",
      "Edite título, salário e status.",
      "Abra um funcionário para obter todos os detalhes.",
    ],
    when: "Para contratações, mudanças de funções ou atualizações salariais.",
    tips: ["Convidar vincula o registro de RH ao acesso de login."],
  },
  "tab.hr.attendance": {
    title: "Presença",
    summary: "Histórico de check-in/check-out.",
    what: "Linhas de presença para folha de pagamento e conformidade.",
    how: ["Filtrar por data.", "Corrija punções perdidas por meio de ESS ou de um gerenciador."],
    when: "Para operações diárias e antes da folha de pagamento.",
    tips: ["A fonte pode ser ESS ou entrada do gerenciador."],
  },
  "tab.hr.leave": {
    title: "Sair",
    summary: "Deixe solicitações e aprovações.",
    what: "Os gerentes aprovam ou rejeitam licenças com base nas permissões da função.",
    how: [
      "Revise as solicitações pendentes.",
      "Aprove ou rejeite com cuidado.",
      "Confirme as datas com o funcionário se não estiver claro.",
    ],
    when: "Quando a equipe solicita folga.",
    tips: ["A aprovação depende do acesso leave_approve."],
  },
  "tab.hr.payroll": {
    title: "Folha de pagamento",
    summary: "O pagamento é executado por um período selecionado.",
    what: "Gere folha de pagamento, visualize execuções e aprove quando autorizado.",
    how: [
      "Defina o início e o fim do período.",
      "Execute a folha de pagamento.",
      "Abra os detalhes e aprove se você tiver direitos.",
    ],
    when: "No encerramento do ciclo salarial.",
    tips: ["Corrija problemas de frequência/licença antes de executar a folha de pagamento."],
  },

  "page.marketing.template": {
    title: "Modelo de mensagem",
    summary: "Prévia de como um modelo CRM aparece para os clientes.",
    what: "Mostra marcadores brutos e uma prévia interpolada com branding e valores de exemplo.",
    how: [
      "Abra um modelo em Marketing → Modelos.",
      "Revise os marcadores na visão geral.",
      "Confira a prévia do cliente.",
      "Voltar restaura a aba Modelos.",
    ],
    when: "Ao redigir mensagens de campanha reutilizáveis.",
    tips: ["Marcadores são chaves simples como {{business}} — {{customer.name}} não é suportado."],
  },

  "tab.marketing.campaigns": {
    title: "Campanhas",
    summary: "Elabore e envie mensagens aos clientes.",
    what: "Crie campanhas de marketing, escolha o público e envie com resumo da entrega.",
    how: [
      "Crie um rascunho de campanha.",
      "Revise o público e a mensagem.",
      "Envie quando estiver pronto e abra os resultados para obter detalhes.",
    ],
    when: "Para promoções e contato com o cliente.",
    tips: ["Os rascunhos podem ser editados antes do envio."],
  },
  "tab.marketing.segments": {
    title: "Segmentos",
    summary: "Públicos de clientes salvos para segmentação.",
    what: "Filtros reutilizáveis para campanhas (por exemplo, por fidelização).",
    how: ["Crie um segmento com filtros.", "Reutilize-o ao compor uma campanha."],
    when: "Para ofertas direcionadas, em vez de criticar todo mundo.",
    tips: ["Mantenha os nomes dos segmentos descritivos."],
  },
  "tab.marketing.coupons": {
    title: "Cupons",
    summary: "Códigos promocionais para checkout POS.",
    what: "Os caixas de códigos de desconto podem inserir no carrinho.",
    how: [
      "Crie um código e valor de desconto.",
      "Compartilhe com os clientes.",
      "Digite o código em POS antes de finalizar a compra.",
    ],
    when: "Para campanhas de descontos e ofertas de parceiros.",
    tips: [
      "Defina limites de uso para que os códigos não sejam resgatados em excesso.",
      "Deixe Válido de/até em branco sem limite de datas; janelas expiradas falham no POS.",
    ],
  },
  "tab.marketing.tiers": {
    title: "Níveis de fidelidade",
    summary: "Ganhe/resgate taxas por faixa de pontos.",
    what: "Configura a rapidez com que os clientes ganham e resgatam pontos.",
    how: [
      "Adicione uma camada com pontos mínimos.",
      "Defina multiplicadores de ganho/resgate.",
      "Teste com um cliente de amostra.",
    ],
    when: "Ao lançar ou ajustar a fidelidade.",
    tips: ["Os níveis mais altos geralmente ganham mais rápido – comunique isso aos clientes."],
  },

  "tab.settings.notifications": {
    title: "Preferências de notificação",
    summary: "Escolha quais alertas você receberá.",
    what: "Alterna por usuário para tipos de notificação.",
    how: ["Abra a guia Notificações em Configurações.", "Ative ou desative os tipos conforme necessário."],
    when: "Quando os alertas são muito barulhentos ou itens importantes estão sendo perdidos.",
    tips: ["Essas preferências se aplicam ao seu usuário, não a todo o negócio."],
  },
  "tab.settings.profile": {
    title: "Perfil",
    summary: "Seu nome, telefone, senha e foto.",
    what: "Detalhes da conta pessoal do usuário conectado.",
    how: [
      "Atualize o nome de exibição e o telefone.",
      "Carregue uma foto de perfil.",
      "Defina uma nova senha somente quando necessário.",
    ],
    when: "No primeiro login ou quando os dados pessoais mudam.",
  },
  "tab.settings.subscriptions": {
    title: "Assinatura e uso",
    summary: "Status do plano e limites de assentos/filiais.",
    what: "Plano atual, status, uso versus limites e verificação de atualização Safepay (JazzCash, Easypaisa ou cartão).",
    how: [
      "Revise os contadores de uso.",
      "Escolha um plano e pague com JazzCash, Easypaisa ou cartão para fazer upgrade.",
    ],
    when: "Ao se aproximar dos limites ou na renovação da fatura.",
    tips: ["O acesso do proprietário é necessário para esta guia."],
  },
  "tab.businesses.details": {
    title: "Detalhes do negócio",
    summary: "Nome, setor e jurisdição fiscal.",
    what: "Campos de identidade principais da empresa selecionada.",
    how: ["Edite os campos e salve.", "Use Desativar quando a empresa precisar interromper as operações."],
    when: "Ao renomear ou corrigir metadados comerciais.",
  },
  "tab.businesses.branches": {
    title: "Filiais",
    summary: "Locais sob esta empresa.",
    what: "Crie e desative filiais dentro dos limites do plano.",
    how: ["Adicione uma ramificação com um nome.", "Desative locais fechados."],
    when: "Abrindo um novo local de caixa ou fechando um.",
  },
  "tab.businesses.branding": {
    title: "Marca comercial",
    summary: "Logotipo, slogan, cor e cópia do mercado.",
    what: "Identidade visual usada no marketplace e UI da equipe deste negócio.",
    how: ["Carregue um logotipo.", "Escolha uma cor de marca.", "Salve a marca."],
    when: "Antes de listar no mercado ou atualizar a identidade da marca.",
  },
  "tab.settings.integrations": {
    title: "Integrações",
    summary: "Conexões externas e sinalizadores de conformidade.",
    what: "Ferramentas do proprietário para conectar serviços para o negócio (por exemplo, sinalizadores FBR).",
    how: ["Revise as configurações de integração disponíveis.", "Altere os sinalizadores somente quando compreender o impacto."],
    when: "Ao configurar integrações ou conformidade.",
    tips: ["Sinalizadores errados podem afetar os relatórios fiscais – confirme com seu contador."],
  },
  "tab.settings.roles": {
    title: "Funções",
    summary: "Quem pode acessar quais módulos.",
    what: "Configuração do proprietário do acesso baseado em função em pacotes configuráveis Kaarobar.",
    how: ["Revise as atribuições de função.", "Mude com cuidado – a equipe pode perder o acesso."],
    when: "Ao contratar, promover ou reforçar a segurança.",
    tips: ["Privilégio mínimo: dê a cada função apenas os pacotes necessários."],
  },
  "tab.settings.branding": {
    title: "Marca da loja",
    summary: "Logotipo, cores e listagem de mercado para sua empresa.",
    what: "Controla a aparência da sua loja no Discover/catálogo e remapeia o esquema de UI no aplicativo (botões, anéis de foco, navegação) a partir da cor primária.",
    how: [
      "Faça upload de um logotipo e escolha uma cor primária de marca.",
      "Adicione o slogan e a descrição do mercado.",
      "Salve a marca e visualize o Discover ou compre como consumidor.",
    ],
    when: "Antes de ir ao ar no mercado ou atualizar o visual da marca.",
    tips: ["É necessário acesso do proprietário. Salvar a marca atualiza o tema do espaço de trabalho da equipe imediatamente."],
  },
  "tab.marketing.templates": {
    title: "Modelos de mensagens",
    summary: "Corpos de mensagens CRM reutilizáveis com variáveis.",
    what: "Modelos salvos para campanhas e visualizações (nome da empresa, slogan, etc.).",
    how: [
      "Crie ou edite um modelo com espaços reservados.",
      "Visualização com variáveis de negócios de amostra.",
      "Selecione o modelo ao compor uma campanha.",
    ],
    when: "Ao padronizar mensagens promocionais ou transacionais.",
    tips: ["Mantenha os modelos curtos para canais de SMS/WhatsApp."],
  },
  "page.appointments": {
    title: "Agendamentos",
    summary: "Agenda diária da equipe para serviços reservados.",
    what: "Mostra os agendamentos da data selecionada e, opcionalmente, de um profissional específico. É possível concluir ou cancelar reservas; a conclusão pode preparar uma venda POS vinculada (SCH-FR-005).",
    how: [
      "Escolha uma data e, se necessário, filtre por profissional.",
      "Pesquise ou filtre por status.",
      "Toque em Concluir para finalizar uma visita ou em Cancelar nos horários reservados.",
    ],
    when: "Durante o expediente em salões e outros estabelecimentos com agendamentos habilitados.",
    tips: ["Os clientes agendam pela opção Agendar no marketplace; a equipe gerencia aqui a agenda do dia."],
  },
};

export default catalog;
