import { apiClient } from "@/lib/api/client";
import { filenameFromDisposition, saveBlob } from "@/lib/download";
import type { ApiEnvelope } from "@/types/api/common";
import type {
  BranchRow,
  CashierRow,
  CategoryRow,
  DailyRow,
  ExportableReport,
  HourRow,
  ProfitAndLoss,
  ReportPeriod,
  SalesSummary,
  TaxRow,
  TenderRow,
  TopProductRow,
} from "@/types/api/reports";

async function get<T>(path: string, params?: object): Promise<T> {
  const response = await apiClient.get<ApiEnvelope<T>>(path, { params });
  return response.data.data;
}

export const getSalesSummary = (period: ReportPeriod) =>
  get<SalesSummary>("/reports/summary", period);
export const getDaily = (period: ReportPeriod) => get<DailyRow[]>("/reports/daily", period);
export const getTopProducts = (period: ReportPeriod & { limit?: number }) =>
  get<TopProductRow[]>("/reports/top-products", period);
export const getByCategory = (period: ReportPeriod) =>
  get<CategoryRow[]>("/reports/by-category", period);
export const getByTender = (period: ReportPeriod) => get<TenderRow[]>("/reports/by-tender", period);
export const getByCashier = (period: ReportPeriod) =>
  get<CashierRow[]>("/reports/by-cashier", period);
export const getByBranch = (period: ReportPeriod) => get<BranchRow[]>("/reports/by-branch", period);
export const getByHour = (period: ReportPeriod) => get<HourRow[]>("/reports/by-hour", period);
export const getProfit = (period: ReportPeriod) => get<ProfitAndLoss>("/reports/profit", period);
export const getTaxReport = (period: ReportPeriod) => get<TaxRow[]>("/reports/tax", period);

/**
 * Downloads a report as CSV — generated by the backend
 * (`GET /reports/:report/export.csv`) so the file carries exactly the
 * figures the API does, not a client-side re-rendering of the table.
 */
export async function downloadReportCsv(
  report: ExportableReport,
  period: ReportPeriod,
): Promise<void> {
  const response = await apiClient.get<Blob>(`/reports/${report}/export.csv`, {
    params: period,
    responseType: "blob",
  });
  const header = response.headers["content-disposition"] as string | undefined;
  saveBlob(response.data, filenameFromDisposition(header, `${report}.csv`));
}

// --- Documents ----------------------------------------------------------------

export type DocumentOptions = { paper?: string; language?: string };

/** The receipt as a printable HTML page, for an iframe preview. */
export async function getReceiptHtml(saleId: string, options: DocumentOptions = {}) {
  const response = await apiClient.get<string>(`/sales/${saleId}/receipt`, {
    params: { format: "html", ...options },
    responseType: "text",
  });
  return response.data;
}

/** A customer's account statement as a printable HTML page. */
export async function getStatementHtml(
  customerId: string,
  options: DocumentOptions & { from?: string; to?: string } = {},
) {
  const response = await apiClient.get<string>(`/customers/${customerId}/statement`, {
    params: options,
    responseType: "text",
  });
  return response.data;
}
