defmodule Kaarobar.Prepaid.GiftCard do
  @moduledoc """
  A bearer instrument: whoever holds the code may spend it.

  That single fact drives the whole design.

  ## The code is the money

  So only its hash is stored, with the last four characters kept separately for
  staff to find a card the customer is holding. A database dump can then never
  hand anyone a spendable balance — which is the same reasoning applied to
  passwords and API tokens elsewhere in the system, for the same reason: this
  column is worth stealing.

  ## `customer_id` is not a restriction

  It records who the card was bought *for*, so an unredeemed one can be chased
  up. Requiring the named customer to be the one spending it would make the
  thing not a gift.

  ## Activation is separate from issue

  A card sold but not paid for is worth nothing yet. `status` starts
  `inactive`, and the sale that pays for it activates it — otherwise a voided
  sale leaves a live card in someone's pocket.
  """

  use Kaarobar.Schema

  alias Kaarobar.Accounts.User
  alias Kaarobar.Customers.Customer
  alias Kaarobar.Money
  alias Kaarobar.Sales.Sale
  alias Kaarobar.Tenancy.Business
  alias Kaarobar.Tenancy.Organization

  @statuses ~w(inactive active depleted expired voided)

  schema "gift_cards" do
    field :code_hash, :binary
    field :code_last_four, :string
    # Never persisted. Set once on creation so the code can be shown to the
    # person buying it, and only then.
    field :code, :string, virtual: true

    field :currency, :string
    field :issued_amount, :decimal
    field :balance, :decimal
    field :status, :string, default: "inactive"

    field :recipient_name, :string
    field :message, :string

    field :issued_at, :utc_datetime_usec
    field :expires_on, :date
    field :activated_at, :utc_datetime_usec

    belongs_to :organization, Organization
    belongs_to :business, Business
    belongs_to :customer, Customer
    belongs_to :issued_by_sale, Sale
    belongs_to :issued_by, User

    timestamps()
  end

  @doc "The states a card moves through."
  def statuses, do: @statuses

  @doc """
  Hashes a code for storage or lookup.

  SHA-256 rather than a password hash: this is looked up on every redemption at
  a busy till, and unlike a password the code is high-entropy and generated by
  us, so there is nothing to brute-force offline.
  """
  @spec hash_code(String.t()) :: binary()
  def hash_code(code), do: :crypto.hash(:sha256, normalize(code))

  @doc "Strips the formatting people type. `abcd-efgh` and `ABCDEFGH` are one code."
  @spec normalize(String.t()) :: String.t()
  def normalize(code),
    do: code |> String.upcase() |> String.replace(~r/[^A-Z0-9]/, "")

  def changeset(card, attrs) do
    card
    |> cast(attrs, [
      :organization_id,
      :business_id,
      :customer_id,
      :code,
      :currency,
      :issued_amount,
      :recipient_name,
      :message,
      :issued_by_sale_id,
      :issued_by_id,
      :issued_at,
      :expires_on
    ])
    |> validate_required([
      :organization_id,
      :business_id,
      :code,
      :currency,
      :issued_amount,
      :issued_at
    ])
    |> validate_number(:issued_amount, greater_than: 0)
    |> validate_code()
    |> put_code_fields()
    |> put_initial_balance()
    |> unique_constraint(:code,
      name: :gift_cards_business_id_code_hash_index,
      message: "is already in use"
    )
  end

  @doc "Brings a card to life once it has been paid for."
  def activate_changeset(card),
    do: change(card, status: "active", activated_at: DateTime.utc_now())

  @doc "Moves the balance, settling the status with it. Only the ledger calls this."
  def balance_changeset(card, new_balance) do
    rounded = Money.round(new_balance)

    card
    |> change(balance: rounded, status: status_for(card, rounded))
    |> validate_number(:balance, greater_than_or_equal_to: 0)
  end

  @doc "Kills a card — lost, fraudulent, or sold on a sale that was voided."
  def void_changeset(card),
    do: change(card, status: "voided", balance: Money.zero())

  @doc "True when the card may be spent today."
  @spec spendable?(t(), Date.t()) :: boolean()
  def spendable?(%__MODULE__{status: status}, _today) when status != "active", do: false

  def spendable?(%__MODULE__{} = card, today),
    do: Money.positive?(card.balance) and not expired?(card, today)

  @doc "True when the card is past its date."
  @spec expired?(t(), Date.t()) :: boolean()
  def expired?(%__MODULE__{expires_on: nil}, _today), do: false
  def expired?(%__MODULE__{expires_on: on}, today), do: Date.compare(on, today) == :lt

  @doc "How the card reads on a receipt: the last four, never the whole code."
  @spec masked(t()) :: String.t()
  def masked(%__MODULE__{code_last_four: last_four}), do: "····#{last_four}"

  # A card that still has money on it stays active; one drained by a purchase is
  # done. Expiry, voiding and activation are none of them decided here — those
  # are events, not consequences of the balance.
  #
  # `inactive` is preserved for that reason. Posting the opening balance would
  # otherwise activate every card the instant it was issued, which is exactly
  # what `inactive` exists to prevent: a card sold on a sale that is then voided
  # must not be left live in somebody's pocket.
  defp status_for(%__MODULE__{status: status}, _balance)
       when status in ["voided", "expired", "inactive"],
       do: status

  defp status_for(%__MODULE__{}, balance) do
    if Money.positive?(balance), do: "active", else: "depleted"
  end

  defp validate_code(changeset) do
    case get_change(changeset, :code) do
      nil ->
        changeset

      code ->
        if String.length(normalize(code)) < 8 do
          add_error(changeset, :code, "must be at least 8 letters or digits")
        else
          changeset
        end
    end
  end

  defp put_code_fields(changeset) do
    case get_change(changeset, :code) do
      nil ->
        changeset

      code ->
        normalized = normalize(code)

        changeset
        |> put_change(:code_hash, hash_code(normalized))
        |> put_change(:code_last_four, String.slice(normalized, -4, 4))
    end
  end

  defp put_initial_balance(changeset) do
    case get_field(changeset, :balance) do
      nil -> put_change(changeset, :balance, get_field(changeset, :issued_amount))
      _balance -> changeset
    end
  end
end
