import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Armaturenbrett",
    summary: "KPIs plus interaktive Verkaufscharts nach Datumsbereich.",
    what: "Zeigt heutige Verkäufe, Cash-Position, niedrigen Bestand, ausstehende Freigaben sowie Umsatz-/Bestelltrends für einen gewählten Zeitraum.",
    how: [
      "Nach der Anmeldung die KPI-Karten des Tages prüfen.",
      "Von/Bis-Daten setzen, um Umsatz- und Bestellcharts zu aktualisieren.",
      "Über einen Chartpunkt fahren für Tagesumsatz oder Ticketanzahl.",
      "Über Low-Stock- oder Freigabekarten zu Inventar oder Retouren springen.",
      "Bei mehreren Standorten Geschäft oder Filiale in der Kopfzeile wechseln.",
    ],
    when: "Zu Schichtbeginn, am Ende des Tages oder wann immer Sie einen Gesundheitscheck in der Filiale benötigen.",
    tips: [
      "Charts nutzen abgeschlossene Verkäufe des gewählten Geschäfts (RPT-FR-001).",
      "Leere Charts? Zeitraum erweitern oder Kassenaktivität prüfen.",
    ],
  },
  "page.pos": {
    title: "Verkaufsstelle",
    summary: "Schneller Checkout mit Warenkorb, Kunde und Zahlung.",
    what: "Kassierer können Produkte verkaufen, Kunden für Treue oder Kredit (Guthaben) gewinnen, Rabatte oder Coupons anwenden und Zahlungen in bar, mit Karte, Geldbörse oder Kredit entgegennehmen.",
    how: [
      "Öffnen Sie eine Kasse, bevor Sie Barverkäufe entgegennehmen.",
      "Fügen Sie Produkte per Suche oder Barcode-Scan zum Warenkorb hinzu.",
      "Fügen Sie bei Bedarf einen Kunden für die Treue oder Kredit hinzu.",
      "Überprüfen Sie den Gesamtbetrag, tippen Sie auf „Zur Kasse gehen“ und wählen Sie eine Zahlungsmethode aus.",
      "Schließen Sie die Bestellung mit „Bestellung aufgeben“ ab und drucken Sie dann den Beleg aus oder teilen Sie ihn.",
    ],
    when: "Für jede Kundenkasse an der Theke.",
    tips: [
      "Für die Kredit-Zahlung ist ein aktives Kredit beim Kunden erforderlich.",
      "Halten Sie die Kasse während der Schicht geöffnet und zählen Sie das Bargeld, bevor Sie am Ende des Tages schließen.",
    ],
  },
  "page.inventory": {
    title: "Inventar und Einkauf",
    summary: "Katalog, Lagerbestand, Lieferanten, Bestellungen, Transfers und Anpassungen.",
    what: "Der Ort, an dem Sie Produkte pflegen, Lagerbestände einsehen, bei Lieferanten einkaufen, Lagerbestände zwischen Filialen verschieben und Mengen korrigieren können.",
    how: [
      "Erstellen oder aktualisieren Sie SKUs und Preise aus Produkten.",
      "Zeigen Sie die verfügbare Menge und die durchschnittlichen Kosten ab Lager an.",
      "Fügen Sie Lieferanten hinzu, erstellen Sie dann Bestellungen und erhalten Sie Waren (GRN).",
      "Verwenden Sie „Transfers“, um Lagerbestände zwischen Filialen zu verschieben, und „Anpassen“, um Mengen festzulegen.",
    ],
    when: "Beim Wareneingang, beim Hinzufügen neuer Artikel, bei der Bestandszählung oder beim Umladen zwischen Filialen.",
    tips: [
      "Erhalten Sie Zahlungen gegen eine Bestellung, sodass Kosten und Verbindlichkeiten korrekt bleiben.",
      "Verwenden Sie unter „Anpassen für Prüfpfade“ einen eindeutigen Ursachencode.",
    ],
  },
  "page.inventory.supplier": {
    title: "Lieferantendetails",
    summary: "Kontakt, Konditionen und verknüpfte Produkte für Bestellungen.",
    what: "Jeder Lieferant speichert Firmendaten und Kontakt sowie eine explizite Liste der Katalogprodukte, die er liefern kann. Beim Erstellen einer Bestellung erscheinen nur verknüpfte Produkte (INV-FR).",
    how: [
      "Öffnen Sie einen Lieferanten unter Inventar → Lieferanten.",
      "Prüfen Sie Kontakt, Adresse und Zahlungsbedingungen.",
      "Verknüpfen Sie Katalogprodukte, die dieser Lieferant liefert.",
      "Trennen Sie Produkte, die der Lieferant nicht mehr führt.",
      "Erstellen Sie Bestellungen unter Inventar → Bestellungen nur mit verknüpften Produkten.",
    ],
    when: "Beim Onboarding eines Lieferanten, bei der Zuordnung von SKUs oder vor einer Bestellung.",
    tips: [
      "Verknüpfen Sie Produkte vor Bestellungen — die API lehnt Zeilen für nicht verknüpfte SKUs ab.",
      "Empfangen Sie Waren (GRN) gegen die Bestellung, damit Bestand und Durchschnittskosten stimmen.",
    ],
  },
  "page.customers": {
    title: "Kunden & Kredit",
    summary: "Kundenprofile, Guthaben/Kredit-Guthaben, Hauptbuch und Treuepunkte.",
    what: "Speichert Kundendaten und ermöglicht Ihnen die Aktivierung von Kredit, die Anzeige des Hauptbuchs, die Verwaltung von Kreditlimits und die Anpassung von Treuepunkten.",
    how: [
      "Fügen Sie einen Kunden mit Namen und Telefonnummer hinzu.",
      "Aktivieren Sie Kredit für Kreditverkäufe.",
      "Öffnen Sie das Hauptbuch, um Belastungen, Gutschriften und ausstehende Beträge anzuzeigen.",
      "Passen Sie Treuepunkte für Werbeaktionen oder Korrekturen an.",
    ],
    when: "Für CRM, Kreditverkäufe und Treueprogramme.",
    tips: [
      "Hängen Sie den Kunden unter POS vor der Zahlung Kredit an.",
      "Überprüfen Sie das Kreditlimit vor großen Kredit-Verkäufen.",
    ],
  },
  "page.sales": {
    title: "Verkaufshistorie",
    summary: "Vollständige Liste der Verkaufsrechnungen für die ausgewählte Filiale.",
    what: "Zeigt vergangene Kassen mit Rechnungsnummer, Kunde, Gesamtsumme, Status und Uhrzeit an, damit Sie einen Verkauf erneut eröffnen oder bestätigen können.",
    how: [
      "Durchsuchen oder durchsuchen Sie die Verkaufsliste.",
      "Öffnen Sie eine Zeile, um Einzelposten und Zahlungen anzuzeigen.",
      "Verwenden Sie bei der Bearbeitung einer Retoure die Rechnungsnummer.",
    ],
    when: "Für Kundenanfragen, Audits, Nachdruck von Belegen oder vor einer Retoure.",
    tips: ["Verkäufe erscheinen nach einem erfolgreichen POS-Kaufvorgang."],
  },
  "page.returns": {
    title: "Rückgaben und Kassen",
    summary: "Rückerstattungen für vergangene Verkäufe und den Verlauf der geöffneten/geschlossenen Kassen.",
    what: "Die Mitarbeiter können einen Verkauf nachschlagen, eine Retoure einreichen und Kassensitzungen einschließlich Über-/Minderbeträge einsehen.",
    how: [
      "Suchen Sie nach der ursprünglichen Verkaufsrechnungsnummer.",
      "Reichen Sie die Rücksendung mit Rückerstattungsmethode und -grund ein.",
      "Vorgesetzte genehmigen ausstehende Rücksendungen oder lehnen sie ab.",
      "Überprüfen Sie die Eröffnungs-/Abschlussbeträge und Abweichungen in der Kassenhistorie.",
    ],
    when: "Bei der Ausstellung von Rückerstattungen, dem Umgang mit beschädigten Waren oder dem Abgleich von Kassen.",
    tips: ["Bewahren Sie die Originalrechnung auf – Link zur Rücksendung zu diesem Verkauf."],
  },
  "page.accounting": {
    title: "Buchhaltung",
    summary: "IFRS-for-SMEs books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools aligned with IFRS for SMEs presentation: chart of accounts (create/edit), journals, trial balance, sectioned P&L and balance sheet, cash flow, general ledger, and receivables/payables aging.",
    how: [
      "Create or edit ledger accounts on Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, Cash flow, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Header accounts are for structure only—post to leaf accounts.",
    ],
  },
  "page.hr": {
    title: "Personalwesen und Gehaltsabrechnung",
    summary: "Mitarbeiter-, Anwesenheits-, Urlaubs- und Gehaltsabrechnungen.",
    what: "Verwaltet Personalstammdaten, Anwesenheit, Urlaubsanträge sowie die Berechnung und Genehmigung der Gehaltsabrechnung.",
    how: [
      "Fügen Sie Mitarbeiter hinzu oder laden Sie bestehende Benutzer ein.",
      "Erfassen Sie die Anwesenheit und überprüfen Sie Urlaubsanträge.",
      "Führen Sie die Lohn- und Gehaltsabrechnung für einen bestimmten Zeitraum durch und genehmigen Sie sie dann.",
    ],
    when: "Für Einstellungen, tägliche Anwesenheit, Urlaubsgenehmigung und Gehaltszyklen.",
    tips: ["Für die Genehmigung der Gehaltsabrechnung ist möglicherweise eine bestimmte Rolle oder ein bestimmtes Paket erforderlich."],
  },
  "page.marketing": {
    title: "Marketing",
    summary: "Kampagnen, Segmente, Coupons und Treuestufen.",
    what: "Hilft Ihnen, Kunden zu benachrichtigen, Segmente anzusprechen, Promo-Codes einzurichten und Treue-Gewinn-/Einlöseraten zu konfigurieren.",
    how: [
      "Erstellen Sie einen Kampagnenentwurf mit Zielgruppe und Botschaft.",
      "Senden, wenn bereit: Der Lieferstatus wird in der Kampagne angezeigt.",
      "Erstellen Sie Segmente und Coupons für gezielte Angebote.",
      "Legen Sie Treuestufen basierend auf Punktebändern fest.",
    ],
    when: "Für Werbeaktionen, Festivalangebote, Rückgewinnungsnachrichten und die Einrichtung von Treueprogrammen.",
    tips: ["Verbinden Sie Kundenkanäle für eine bessere Lieferung."],
  },
  "page.reports": {
    title: "Berichte",
    summary: "Operative Vertriebs- und Produktleistung.",
    what: "Branchenberichte wie Tagesverkäufe und Top-Produkte. Vollständige Finanzberichte finden Sie unter Buchhaltung.",
    how: [
      "Wählen Sie einen Datumsbereich.",
      "Überprüfen Sie die täglichen Verkäufe und Ticketzahlen.",
      "Überprüfen Sie die meistverkauften Produkte nach Menge.",
    ],
    when: "Für wöchentliche Rezensionen, Merchandising-Entscheidungen oder Besitzer-Updates.",
    tips: ["Öffnen Sie die Buchhaltung für Gewinn und Verlust oder Bilanz."],
  },
  "page.settings": {
    title: "Einstellungen",
    summary: "Profil, Planlimits, Abrechnung, Benachrichtigungen, FBR-Flags und Rollen.",
    what: "Kontoprofil für alle Mitarbeiter sowie Unternehmenskonfiguration: Abonnementnutzung, Benachrichtigungseinstellungen, Integrationen und Rollenzugriff (einige Registerkarten sind nur für Eigentümer verfügbar).",
    how: [
      "Aktualisieren Sie Ihr Profil auf der Registerkarte „Profil“.",
      "Überprüfen Sie die Nutzung anhand der Plangrenzen.",
      "Eigentümer können Integrationen, Branding und Rollen für das aktive Unternehmen verwalten.",
    ],
    when: "Planen Sie beim Onboarding Upgrades oder ändern Sie den Modulzugriff.",
    tips: ["Einige Einstellungen gelten nur für den Eigentümer. Fragen Sie den Eigentümer, wenn eine Registerkarte fehlt."],
  },
  "page.notifications": {
    title: "Benachrichtigungen",
    summary: "Urlaubs-, Gehalts-, Abrechnungs- und Kampagnenbenachrichtigungen.",
    what: "System- und Workflow-Benachrichtigungen, damit Genehmigungen und Kampagnenergebnisse nicht verpasst werden.",
    how: [
      "Öffnen Sie Benachrichtigungen, um ungelesene Elemente anzuzeigen.",
      "Klicken Sie auf eine verknüpfte Warnung, um zum entsprechenden Bildschirm zu gelangen.",
      "Passen Sie die Einstellungen in den Einstellungen an, wenn die Alarme zu laut sind.",
    ],
    when: "Den ganzen Tag über für Genehmigungen und Betriebsaktualisierungen.",
    tips: ["Halten Sie das Panel an arbeitsreichen Tagen geöffnet, damit Urlaubs- und Gehaltsabrechnungsanfragen sichtbar bleiben."],
  },
  "page.profile": {
    title: "Ihr Profil",
    summary: "Persönlicher Name, Telefonnummer, Passwort und Foto.",
    what: "Aktualisiert Ihr Benutzerkonto – nicht die vollständigen Geschäftseinstellungen.",
    how: [
      "Anzeigenamen und Telefon ändern.",
      "Legen Sie nur dann ein neues Passwort fest, wenn Sie es ändern müssen.",
      "Laden Sie ein Profilfoto hoch, sofern verfügbar.",
    ],
    when: "Bei der ersten Anmeldung oder beim Aktualisieren persönlicher Daten.",
    tips: ["Ändern Sie die Sprache über die Sprachsteuerung des Profils oder die Seitenleiste."],
  },
  "page.businesses": {
    title: "Unternehmen",
    summary: "Eigentümerliste der Unternehmen unter Ihrem Konto.",
    what: "Erstellen Sie Unternehmen innerhalb der Plangrenzen und öffnen Sie jedes für Branding, Marktplatz und Filialen.",
    how: [
      "Sehen Sie sich die Liste der aktiven Unternehmen an.",
      "Erstellen Sie ein neues Unternehmen mit Namen und Branche.",
      "Öffnen Sie eine Zeile, um Branding, Marktplatz und Filialen zu bearbeiten.",
    ],
    when: "Beim Onboarding eines neuen Shops oder beim Überprüfen der Plankapazität.",
    tips: ["Fehler beim Planlimit (402) bedeuten, dass Sie unter Einstellungen → Abonnements ein Upgrade durchführen müssen."],
  },
  "page.businessDetail": {
    title: "Geschäftsdetails",
    summary: "Bearbeiten Sie ein Unternehmen: Branding, Marktplatz und Filialen.",
    what: "Eigentümertools für eine einzige Unternehmensidentität und Standorte.",
    how: [
      "Aktualisieren Sie Name, Branche, Slogan und Markenfarbe.",
      "Laden Sie ein Logo hoch und konfigurieren Sie den Marktplatzeintrag.",
      "Fügen Sie nach Bedarf Zweige hinzu oder deaktivieren Sie sie.",
    ],
    when: "Bei der Eröffnung eines Geschäfts oder bei der Auffrischung des Markenauftritts.",
    tips: ["Durch die Deaktivierung bleiben historische Finanzdaten erhalten; Es wird nicht dauerhaft gelöscht."],
  },
  "page.ess": {
    title: "Mitarbeitertools (ESS)",
    summary: "Mitarbeiter-Selbstbedienung für An- und Abwesenheit.",
    what: "Mitarbeiter können ohne vollständigen HR-Administratorzugriff ein- und auschecken und Urlaub einreichen.",
    how: [
      "Markieren Sie die heutige Anwesenheit.",
      "Reichen Sie den Urlaub mit Datum und Grund ein.",
      "Überprüfen Sie den Genehmigungsstatus nach dem Absenden.",
    ],
    when: "Täglich für Mitarbeiter, die Self-Service HR nutzen.",
    tips: ["Manager genehmigen Urlaub weiterhin über die Registerkarte „HR-Urlaub“."],
  },

  "tab.inventory.stock": {
    title: "Vorhandener Lagerbestand",
    summary: "Menge und durchschnittliche Kosten für jedes Produkt in dieser Filiale.",
    what: "Ansicht des Lagerbestands nach Käufen, Verkäufen, Übertragungen und Anpassungen.",
    how: [
      "Suchen Sie nach SKU oder Produktnamen.",
      "Überprüfen Sie die Menge, bevor Sie eine Neubestellung durchführen.",
      "Vergleichen Sie mit Produkten, wenn etwas nicht stimmt.",
    ],
    when: "Bevor Sie Bestellungen aufgeben, Stichproben durchführen oder Engpässe untersuchen.",
    tips: ["Durchschnittliche Kostenaktualisierungen bei Wareneingang."],
  },
  "tab.inventory.products": {
    title: "Produkte",
    summary: "Verkaufsartikel, Dienstleistungen, Preise und Barcodes.",
    what: "Erstellen und bearbeiten Sie Produkte, die in POS und der Bestandsverfolgung verwendet werden.",
    how: [
      "Fügen Sie ein Produkt mit SKU, Namen und Preis hinzu.",
      "Legen Sie einen Barcode zum Scannen an der Kasse fest.",
      "Öffnen Sie ein Produkt, um Details anzuzeigen oder zu bearbeiten.",
    ],
    when: "Beim Hinzufügen neuer Artikel oder beim Aktualisieren von Preisen.",
    tips: ["Sorgen Sie dafür, dass die SKUs im gesamten Unternehmen einzigartig sind."],
  },
  "tab.inventory.suppliers": {
    title: "Lieferanten",
    summary: "Lieferantenstamm für den Einkauf.",
    what: "Lieferantenkontakt, Zahlungsbedingungen und Status für Bestellungen.",
    how: [
      "Fügen Sie einen Lieferanten mit Namen und Kontaktdaten hinzu.",
      "Legen Sie Zahlungsbedingungen fest, bevor Sie eine Bestellung erstellen.",
      "Öffnen Sie einen Lieferanten, um alle Details anzuzeigen.",
    ],
    when: "Beim Einrichten von Einkäufen oder Aktualisieren von Lieferantendetails.",
    tips: ["Verwenden Sie keine inaktiven Lieferanten auf neuen POs."],
  },
  "tab.inventory.pos": {
    title: "Bestellungen",
    summary: "Lieferantenbestellungen und Wareneingang (GRN).",
    what: "Erstellen Sie POs, verfolgen Sie den Status und nehmen Sie Mengen in den Lagerbestand auf.",
    how: [
      "Erstellen Sie eine Bestellung mit Lieferanten und Einzelposten.",
      "Erhalten Sie Waren gegen die Bestellung, wenn der Lagerbestand eintrifft (GRN).",
      "Öffnen Sie eine Bestellung, um Positionen und Status zu überprüfen.",
    ],
    when: "Bei der Nachbestellung von Lagerbeständen bei einem Lieferanten.",
    tips: ["Erhalten Sie nur das, was angekommen ist – Teilbelege werden unterstützt."],
  },
  "tab.inventory.transfers": {
    title: "Überweisungen",
    summary: "Bewegen Sie Lagerbestände zwischen den Filialen.",
    what: "Erstellt ein Übertragungsdokument, das bestätigt werden muss, damit der Bestand von einer Filiale zur anderen bewegt wird.",
    how: [
      "Wählen Sie Zielfiliale, Produkt und Menge aus.",
      "Erstellen Sie die Übertragung und bestätigen Sie, sobald die Waren bewegt wurden.",
    ],
    when: "Beim standortübergreifenden Bestandsausgleich.",
    tips: ["Bestätigen Sie umgehend, damit die verfügbaren Mengen korrekt bleiben."],
  },
  "tab.inventory.adjust": {
    title: "Bestandsanpassung",
    summary: "Korrekte Menge für Schäden, Zählabweichungen oder Abschreibungen.",
    what: "Ändert die Menge (+/−) mit einem Ursachencode für die Prüfung.",
    how: [
      "Wählen Sie Produkt- und Mengendelta.",
      "Wählen Sie einen Ursachencode aus.",
      "Speichern, um den Lagerbestand zu aktualisieren.",
    ],
    when: "Nach einer physischen Zählung oder wenn Waren beschädigt sind oder verloren gehen.",
    tips: ["Bevorzugen Sie GRN/Transfers für normale Bewegungen; Verwenden Sie Adjust für Korrekturen."],
  },

  "tab.accounting.coa": {
    title: "Kontenplan",
    summary: "IFRS-for-SMEs ledger accounts for journals and statements.",
    what: "Hierarchical list of account codes with type, classification, and normal balance. Create new accounts or edit existing ones.",
    how: [
      "Use New account to add a postable or header account.",
      "Browse by code; indent shows parent hierarchy.",
      "Edit an account to change labels or classification.",
    ],
    when: "During setup review or when you need a new ledger account.",
    tips: [
      "Do not delete accounts that already have postings.",
    ],
  },
  "tab.accounting.journals": {
    title: "Zeitschriften",
    summary: "Manuelle und Systemjournaleinträge.",
    what: "Zeigt veröffentlichte Journale an und ermöglicht die Buchung ausgewogener manueller Einträge.",
    how: [
      "Öffnen Sie ein Journal, um Soll-/Habenlinien anzuzeigen.",
      "Verwenden Sie bei Bedarf das Postjournal für eine zweizeilige Anpassung.",
    ],
    when: "Für Korrekturen, Rückstellungen oder die Überprüfung automatisch geposteter Einträge.",
    tips: ["Vor der Buchung müssen die Belastungen der Gutschrift entsprechen."],
  },
  "tab.accounting.tb": {
    title: "Probebilanz",
    summary: "Kontobezogene Soll-/Habensummen für einen Zeitraum.",
    what: "Überprüft, ob die Bücher ausgeglichen sind, bevor Kontoauszüge ausgeführt werden.",
    how: ["Legen Sie das Von-/Bis-Datum fest.", "Überprüfen Sie die Kontosummen."],
    when: "Am Monatsende oder vor GuV/Bilanz.",
    tips: ["Untersuchen Sie unerwartet große Guthaben."],
  },
  "tab.accounting.pl": {
    title: "GuV",
    summary: "Sectioned income statement (IFRS for SMEs).",
    what: "Revenue, cost of sales, operating expenses, and net income for the selected period.",
    how: [
      "Choose dates.",
      "Review sections and subtotals (gross / operating / net).",
    ],
    when: "For owner review and period close.",
    tips: [
      "Accuracy depends on correct account classifications and postings.",
    ],
  },
  "tab.accounting.bs": {
    title: "Bilanz",
    summary: "Sectioned statement of financial position.",
    what: "Current and non-current assets/liabilities plus equity as of the report date.",
    how: [
      "Set the as-of date.",
      "Review current vs non-current sections.",
    ],
    when: "For period close and financial discussions.",
    tips: [
      "AR/AP aging complements customer and supplier balances.",
    ],
  },
  "tab.accounting.cf": {
    title: "Cashflow",
    summary: "Indirect cash flow summary for a period.",
    what: "Starts from net income and adjusts for working-capital changes (AR, inventory, AP).",
    how: [
      "Choose dates.",
      "Review cash from operations.",
    ],
    when: "For cash planning alongside P&L and balance sheet.",
    tips: [
      "This is a simplified indirect method—not a full IAS 7 statement.",
    ],
  },

  "tab.accounting.gl": {
    title: "Hauptbuch",
    summary: "Zeilenweise Aktivität für ein Konto.",
    what: "Soll-/Habenhistorie für ein einzelnes Konto.",
    how: ["Wählen Sie ein Konto aus.", "Termine festlegen.", "Überprüfen Sie jeden Beitrag."],
    when: "Bei der Überprüfung von Salden oder beim Abgleichen eines Kontos.",
    tips: ["Führen Sie zuerst den Probesaldo durch und eröffnen Sie dann das Hauptbuch für ungerade Konten."],
  },
  "tab.accounting.ar": {
    title: "AR-Alterung",
    summary: "Kundenforderungen nach Altersgruppe.",
    what: "Offene Rechnungssalden gruppiert nach Alter (aktuell, 30, 60 Tage usw.).",
    how: ["Überprüfen Sie die Buckets.", "Für Einzelheiten öffnen Sie eine Rechnung.", "Setzen Sie sich mit dem Kunden in Verbindung."],
    when: "Für Inkasso und Kreditkontrolle.",
    tips: ["Kredit/Kreditverkäufe können in AR erscheinen."],
  },
  "tab.accounting.ap": {
    title: "AP-Alterung",
    summary: "Lieferantenverbindlichkeiten nach Altersgruppe.",
    what: "Von Ihnen geschuldete Rechnungen, gruppiert nach Fälligkeitsdatum.",
    how: ["Überprüfen Sie die Buckets.", "Für Einzelheiten öffnen Sie eine Rechnung.", "Planen Sie Lieferantenzahlungen."],
    when: "Für Lieferantenzahlung und Cash-Planung.",
    tips: ["Durch Bestellbelege werden häufig AP-Rechnungen erstellt."],
  },

  "tab.hr.employees": {
    title: "Mitarbeiter",
    summary: "Personalstammliste und Beschäftigungsdetails.",
    what: "Erstellen Sie Mitarbeiterdatensätze, bearbeiten Sie das Grundgehalt und öffnen Sie Profile.",
    how: [
      "Fügen Sie einen Mitarbeiter hinzu oder laden Sie einen vorhandenen Benutzer ein.",
      "Bearbeiten Sie Titel, Gehalt und Status.",
      "Öffnen Sie einen Mitarbeiter, um weitere Informationen zu erhalten.",
    ],
    when: "Für Einstellungen, Rollenänderungen oder Gehaltsaktualisierungen.",
    tips: ["Die Einladung verknüpft den HR-Datensatz mit dem Anmeldezugriff."],
  },
  "tab.hr.attendance": {
    title: "Anwesenheit",
    summary: "Check-in-/Check-out-Verlauf.",
    what: "Anwesenheitszeilen für Gehaltsabrechnung und Compliance.",
    how: ["Nach Datum filtern.", "Beheben Sie fehlende Schläge über ESS oder einen Manager."],
    when: "Für den täglichen Betrieb und vor der Lohn- und Gehaltsabrechnung.",
    tips: ["Die Quelle kann ESS oder ein Managereintrag sein."],
  },
  "tab.hr.leave": {
    title: "Geh",
    summary: "Urlaubsanträge und Genehmigungen.",
    what: "Manager genehmigen oder lehnen Urlaub basierend auf Rollenberechtigungen ab.",
    how: [
      "Überprüfen Sie ausstehende Anfragen.",
      "Genehmigen oder lehnen Sie sorgfältig ab.",
      "Bestätigen Sie Termine mit dem Mitarbeiter, wenn Unklarheiten bestehen.",
    ],
    when: "Wenn Mitarbeiter eine Freistellung beantragen.",
    tips: ["Die Genehmigung hängt vom Leave_approve-Zugriff ab."],
  },
  "tab.hr.payroll": {
    title: "Gehaltsabrechnung",
    summary: "Die Bezahlung läuft für einen ausgewählten Zeitraum.",
    what: "Erstellen Sie Gehaltsabrechnungen, sehen Sie sich Läufe an und genehmigen Sie sie, wenn Sie autorisiert sind.",
    how: [
      "Legen Sie den Beginn und das Ende des Zeitraums fest.",
      "Führen Sie die Gehaltsabrechnung durch.",
      "Öffnen Sie die Details und genehmigen Sie, ob Sie Rechte haben.",
    ],
    when: "Am Ende des Gehaltszyklus.",
    tips: ["Beheben Sie Anwesenheits-/Urlaubsprobleme, bevor Sie die Gehaltsabrechnung durchführen."],
  },

  "page.marketing.template": {
    title: "Nachrichtenvorlage",
    summary: "Vorschau, wie eine CRM-Vorlage für Kunden aussieht.",
    what: "Zeigt Rohplatzhalter und eine interpolierte Vorschau mit Geschäftsbranding und Beispielkundenwerten.",
    how: [
      "Öffnen Sie eine Vorlage unter Marketing → Vorlagen.",
      "Prüfen Sie Platzhalter in der Übersicht.",
      "Prüfen Sie die Kundenvorschau mit Beispielwerten.",
      "Zurück führt zum Vorlagen-Tab.",
    ],
    when: "Beim Erstellen wiederverwendbarer Kampagnennachrichten.",
    tips: ["Platzhalter sind flache Schlüssel wie {{business}} — {{customer.name}} wird nicht unterstützt."],
  },

  "tab.marketing.campaigns": {
    title: "Kampagnen",
    summary: "Verfassen und versenden Sie Kundennachrichten.",
    what: "Erstellen Sie Marketingkampagnen, wählen Sie die Zielgruppe aus und senden Sie sie mit einer Lieferzusammenfassung.",
    how: [
      "Erstellen Sie einen Kampagnenentwurf.",
      "Überprüfen Sie Zielgruppe und Botschaft.",
      "Senden Sie die Ergebnisse, wenn Sie bereit sind, und öffnen Sie sie für Details.",
    ],
    when: "Für Werbeaktionen und Kundenansprache.",
    tips: ["Entwürfe können vor dem Senden bearbeitet werden."],
  },
  "tab.marketing.segments": {
    title: "Segmente",
    summary: "Kundenzielgruppen für das Targeting gespeichert.",
    what: "Wiederverwendbare Filter für Kampagnen (z. B. nach Treue).",
    how: ["Erstellen Sie ein Segment mit Filtern.", "Verwenden Sie es beim Verfassen einer Kampagne wieder."],
    when: "Für zielgerichtete Angebote, statt alle zu verprügeln.",
    tips: ["Halten Sie die Segmentnamen beschreibend."],
  },
  "tab.marketing.coupons": {
    title: "Gutscheine",
    summary: "Promo-Codes für die POS-Kaufabwicklung.",
    what: "Rabattcodes können Kassierer im Warenkorb eingeben.",
    how: [
      "Erstellen Sie einen Code und einen Rabattwert.",
      "Mit Kunden teilen.",
      "Geben Sie vor dem Bezahlen den Code bei POS ein.",
    ],
    when: "Für Rabattaktionen und Partnerangebote.",
    tips: [
      "Legen Sie Nutzungsbeschränkungen fest, damit Codes nicht zu oft eingelöst werden.",
      "Gültig von/bis leer lassen = kein Datumsfenster; abgelaufene Codes scheitern an der Kasse.",
    ],
  },
  "tab.marketing.tiers": {
    title: "Treuestufen",
    summary: "Verdienen/Einlösen-Raten nach Punkteband.",
    what: "Konfiguriert, wie schnell Kunden Punkte sammeln und einlösen.",
    how: [
      "Fügen Sie eine Stufe mit der Mindestpunktzahl hinzu.",
      "Legen Sie Gewinn-/Einlösemultiplikatoren fest.",
      "Testen Sie mit einem Musterkunden.",
    ],
    when: "Beim Launch oder Tuning der Loyalität.",
    tips: ["Höhere Stufen verdienen in der Regel schneller – teilen Sie dies Ihren Kunden mit."],
  },

  "tab.settings.notifications": {
    title: "Benachrichtigungseinstellungen",
    summary: "Wählen Sie aus, welche Benachrichtigungen Sie erhalten.",
    what: "Benutzerspezifisches Umschalten zwischen den Benachrichtigungstypen.",
    how: ["Öffnen Sie in den Einstellungen die Registerkarte „Benachrichtigungen“.", "Aktivieren oder deaktivieren Sie die Typen nach Bedarf."],
    when: "Wenn Warnungen zu laut sind oder wichtige Elemente übersehen werden.",
    tips: ["Diese Einstellungen gelten für Ihren Benutzer, nicht für das gesamte Unternehmen."],
  },
  "tab.settings.profile": {
    title: "Profil",
    summary: "Ihr Name, Ihre Telefonnummer, Ihr Passwort, Ihr Foto und Ihre Sprache.",
    what: "Mitarbeiterkontoeinstellungen, die von jeder Rolle gemeinsam genutzt werden – kein Business-Branding.",
    how: [
      "Anzeigenamen und Telefon aktualisieren.",
      "Laden Sie ein Profilfoto hoch.",
      "Ändern Sie bei Bedarf die Sprache oder legen Sie ein neues Passwort fest.",
    ],
    when: "Beim ersten Login oder immer dann, wenn sich Ihre persönlichen Daten ändern.",
    tips: ["Unternehmensbranding findet unter „Branding“ oder „Unternehmen“ statt, nicht unter „Profil“."],
  },
  "tab.settings.subscriptions": {
    title: "Abonnement und Nutzung",
    summary: "Planstatus und Sitzplatz-/Zweigstellenbeschränkungen.",
    what: "Aktueller Plan, Status, Nutzung von Unternehmen/Filialen/Benutzern im Vergleich zu Limits und Safepay-Upgrade-Checkout (JazzCash, Easypaisa oder Karte).",
    how: [
      "Überprüfen Sie die Nutzungszähler.",
      "Wählen Sie einen Tarif und zahlen Sie für das Upgrade mit JazzCash, Easypaisa oder einer Karte.",
    ],
    when: "Bei Annäherung an Limits oder bei Erneuerung der Rechnung.",
    tips: ["Für diese Registerkarte ist Besitzerzugriff erforderlich."],
  },
  "tab.settings.integrations": {
    title: "Integrationen",
    summary: "Externe Verbindungen und Compliance-Flags.",
    what: "Eigentümertools zum Verbinden von Diensten für das Unternehmen (z. B. FBR-Flags).",
    how: ["Überprüfen Sie die verfügbaren Integrationseinstellungen.", "Ändern Sie Flags nur, wenn Sie die Auswirkungen verstehen."],
    when: "Beim Einrichten von Integrationen oder Compliance.",
    tips: ["Falsche Kennzeichnungen können sich auf die Steuerberichterstattung auswirken – wenden Sie sich hierfür an Ihren Buchhalter."],
  },
  "tab.settings.roles": {
    title: "Rollen",
    summary: "Wer kann auf welche Module zugreifen?",
    what: "Besitzerkonfiguration des rollenbasierten Zugriffs auf Kaarobar-Bundles.",
    how: ["Überprüfen Sie die Rollenzuweisungen.", "Gehen Sie beim Wechsel vorsichtig vor – Mitarbeiter könnten den Zugriff verlieren."],
    when: "Bei der Einstellung, Beförderung oder Verschärfung der Sicherheit.",
    tips: ["Geringste Berechtigung: Geben Sie jeder Rolle nur die Pakete, die sie benötigt."],
  },
  "tab.settings.branding": {
    title: "Store-Branding",
    summary: "Logo, Farben und Marktplatzeintrag für Ihr Unternehmen.",
    what: "Steuert, wie Ihr Shop in Discover/Katalog aussieht und ordnet das In-App-UI-Schema (Schaltflächen, Fokusringe, Navigation) von der Primärfarbe neu zu.",
    how: [
      "Laden Sie ein Logo hoch und wählen Sie eine primäre Markenfarbe aus.",
      "Fügen Sie einen Slogan und eine Marktplatzbeschreibung hinzu.",
      "Speichern Sie das Branding und zeigen Sie dann eine Vorschau von Discover an oder kaufen Sie als Verbraucher ein.",
    ],
    when: "Vor dem Go-Live auf dem Marktplatz oder einem erfrischenden Markenauftritt.",
    tips: ["Besitzerzugriff ist erforderlich. Durch das Speichern des Brandings wird das Design des Mitarbeiterarbeitsbereichs sofort aktualisiert."],
  },
  "tab.marketing.templates": {
    title: "Nachrichtenvorlagen",
    summary: "Wiederverwendbare CRM-Nachrichtentexte mit Variablen.",
    what: "Gespeicherte Vorlagen für Kampagnen und Vorschauen (Firmenname, Slogan usw.).",
    how: [
      "Erstellen oder bearbeiten Sie eine Vorlage mit Platzhaltern.",
      "Vorschau mit Beispielgeschäftsvariablen.",
      "Wählen Sie die Vorlage aus, wenn Sie eine Kampagne erstellen.",
    ],
    when: "Bei der Standardisierung von Werbe- oder Transaktionsnachrichten.",
    tips: ["Halten Sie die Vorlagen für SMS-/WhatsApp-Kanäle kurz."],
  },

  "page.market.discover": {
    title: "Entdecken Sie Geschäfte",
    summary: "Durchsuchen Sie Marktplatzunternehmen und starten Sie eine Abholbestellung.",
    what: "Listet Kaarobar Unternehmen auf, die eine Marktplatz-Storefront mit Branding veröffentlichen.",
    how: [
      "Suchen Sie nach Namen oder filtern Sie nach Industriechips.",
      "Öffnen Sie ein Geschäft, um seinen Katalog zu durchsuchen.",
      "Fügen Sie Artikel aus einem oder mehreren Geschäften zu Ihrem Warenkorb hinzu.",
    ],
    when: "Wann immer Sie die Abholung in einem aufgelisteten Geschäft bestellen möchten.",
    tips: ["Geschäfte werden angezeigt, nachdem der Eigentümer den Marktplatz und das Branding aktiviert hat."],
  },
  "page.market.products": {
    title: "All products",
    summary: "Cross-store product feed from marketplace businesses.",
    what: "Shows sellable products from every marketplace-enabled store. Search and filter, then open a product for details or the store catalog.",
    how: [
      "Search by name or filter by category/industry.",
      "Open a product card for detail, price, and add to cart.",
      "Use Visit store / back links to shop the full catalog.",
    ],
    when: "When you want to find an item without browsing stores one by one.",
    tips: ["If the feed is empty, catalogs may not be published yet—try Discover."],
  },
  "page.market.productDetail": {
    title: "Product detail",
    summary: "One product from a marketplace store.",
    what: "Shows image, price, description, and quantity controls. Adds the line to that store’s cart bag.",
    how: [
      "Adjust quantity and tap Add to cart.",
      "Open the store link to keep shopping.",
      "Checkout from the sticky cart when ready.",
    ],
    when: "After tapping a product from Products or a store grid.",
    tips: ["Sign in as a consumer before adding to cart."],
  },
  "page.market.catalog": {
    title: "Katalog speichern",
    summary: "Produkte aus einem Marktplatz-Shop.",
    what: "Markenproduktraster für ein einzelnes Unternehmen – nach Kategorie, Suche und Preis filtern und dann in den Warenkorb legen.",
    how: [
      "Tippen Sie auf „Shop“, wenn das Geschäft auch Buchungen anbietet.",
      "Verwenden Sie Filter, um den Katalog einzugrenzen.",
      "Tippen Sie auf „Hinzufügen“, um Artikel in Ihren Warenkorb zu legen (Warenkörbe für mehrere Geschäfte sind zulässig).",
      "Öffnen Sie „Warenkorb anzeigen“ oder den Warenkorb in der Navigationsleiste, um zur Kasse zu gehen.",
    ],
    when: "Beim Einkaufen in einem bestimmten Geschäft zur Abholung.",
    tips: ["Jedes Geschäft behält seine eigene Tasche im Warenkorb, bis Sie eine Bestellung aufgeben."],
  },
  "page.market.book": {
    title: "Service buchen",
    summary: "Buchen Sie selbst einen Termin bei einem Dienstleistungsbetrieb.",
    what: "Wählen Sie eine Dienstleistung, optional eine bestimmte Fachkraft und ein verfügbares Zeitfenster aus und bestätigen Sie anschließend. Verwendet die Termin-APIs des Portals (CUS-FR-005).",
    how: [
      "Öffnen Sie „Buchen“ bei einem Salon oder einem Betrieb mit aktivierter Terminbuchung.",
      "Wählen Sie eine Dienstleistung und anschließend „Beliebige Fachkraft“ oder eine bestimmte Person.",
      "Wählen Sie ein Datum und ein freies Zeitfenster, ergänzen Sie bei Bedarf Notizen und bestätigen Sie.",
      "Die Buchung finden Sie unter Bestellungen → Termine.",
    ],
    when: "Wenn Sie statt einer Produktbestellung einen Besuch zu einer festen Uhrzeit planen möchten.",
    tips: ["Melden Sie sich vor der Buchung mit einem Kundenkonto an."],
  },
  "tab.market.shop": {
    title: "Registerkarte „Shop“.",
    summary: "Bestellen Sie Produkte zur Abholung.",
    what: "Zeigt verkaufbare Waren aus dem Katalog dieses Shops.",
    how: ["Durchsuchen oder suchen Sie nach Produkten.", "In den Warenkorb legen und zur Kasse gehen."],
    when: "Hybride Geschäfte, die Waren verkaufen und Termine entgegennehmen.",
  },
  "tab.market.book": {
    title: "Registerkarte „Buchen“",
    summary: "Buchen Sie einen Servicetermin.",
    what: "Buchungsablauf: Dienstleistung → Fachkraft → Zeitfenster → Bestätigung.",
    how: ["Wählen Sie eine Dienstleistung.", "Wählen Sie eine Fachkraft oder „Beliebig“.", "Bestätigen Sie die Uhrzeit."],
    when: "Bei Betrieben mit aktivierter Terminbuchung und Dienstleistungsangeboten.",
  },
  "page.checkout.review": {
    title: "Überprüfen Sie den Warenkorb",
    summary: "Bearbeiten Sie die Mengen vor der Zahlung.",
    what: "Zeigt jede Einkaufstasche in Ihrem Warenkorb mit Einzelposten, Zwischensummen und einer Gesamtsumme an.",
    how: [
      "Passen Sie die Mengen an oder entfernen Sie Zeilen pro Filiale.",
      "Leeren Sie eine Einkaufstasche oder kaufen Sie in diesem Geschäft weiter ein.",
      "Weiter zu Kontakt & Bezahlung.",
    ],
    when: "Nach dem Hinzufügen von Produkten und vor der Aufgabe von Abholaufträgen.",
    tips: ["Wenn Sie den Warenkorb leeren, kehren Sie zu Discover zurück."],
  },
  "page.checkout.pay": {
    title: "Kontakt & Zahlung",
    summary: "Kontaktdaten abholen und Bestellungen aufgeben.",
    what: "Sammelt Name, Telefonnummer und Abholnotizen und gibt dann eine Bestellung pro Geschäft mit denselben Kontaktinformationen auf.",
    how: [
      "Bestätigen oder bearbeiten Sie den Namen und die Telefonnummer des Kontakts.",
      "Fügen Sie optionale Abholnotizen hinzu.",
      "Wählen Sie eine Karte oder ein Portemonnaie (Stub) und geben Sie die Bestellung(en) auf.",
    ],
    when: "Letzter Schritt, bevor Bestellungen unter Bestellungen angezeigt werden.",
    tips: ["Beim Multi-Store-Checkout werden separate Rechnungen pro Unternehmen erstellt."],
  },
  "page.buyer.orders": {
    title: "Bestellungen & Buchungen",
    summary: "Ihre Marktplatz-Abholaufträge und Termine.",
    what: "Listet von Ihnen aufgegebene Online-Bestellungen und bevorstehende/vergangene Termine in allen Filialen auf. Stornieren Sie gebuchte Termine über die Registerkarte „Termine“.",
    how: [
      "Eröffnen Sie Bestellungen über die Marktplatz-Navigation.",
      "Verwenden Sie die Registerkarte „Bestellungen“ für Abholrechnungen. Terminvereinbarungen für Buchungen.",
      "Tippen Sie auf eine Bestellung, um Artikel, Zahlungen und Status anzuzeigen.",
      "Stornieren Sie einen gebuchten Termin, wenn Sie ihn später verschieben müssen.",
    ],
    when: "Um „Platziert → Bestätigt → Bereit → Abgeschlossen“ oder bevorstehende Besuche zu verfolgen.",
    tips: ["Kontaktieren Sie das Geschäft, wenn sich die Abhol- oder Terminzeiten ändern."],
  },
  "tab.buyer.orders": {
    title: "Registerkarte „Bestellungen“.",
    summary: "Historie der Abholungsbestellungen.",
    what: "Online-Marktplatzbestellungen mit Status und Filialname.",
    how: ["Tippen Sie auf eine Bestellung für Einzelposten und Gesamtsummen."],
    when: "Nach Auftragserteilung zur Abholung.",
  },
  "tab.buyer.appointments": {
    title: "Registerkarte „Termine“",
    summary: "Kommende und vergangene Buchungen.",
    what: "Servicetermine, die Sie in Marketplace-Stores gebucht haben.",
    how: ["Überprüfen Sie bevorstehende Besuche.", "Stornieren Sie gebuchte Termine bei Bedarf."],
    when: "Nach der Buchung eines Salon- oder Servicebesuchs.",
  },
  "page.buyer.orderDetail": {
    title: "Bestelldetails",
    summary: "Einzelposten und Gesamtsummen für einen Abholauftrag.",
    what: "Zeigt Rechnungsnummer, Filiale, Status, jede Zeile, Steuer/Rabatt und Zahlungsmethoden an.",
    how: ["Aus der Bestellhistorie öffnen.", "Überprüfen Sie die Artikel vor der Abholung."],
    when: "Nach der Bestellung oder bei der Prüfung der Abholbereitschaft.",
    tips: ["Statusaktualisierungen werden hier angezeigt, während das Geschäft Ihre Bestellung bearbeitet."],
  },
  "page.buyer.loyalty": {
    title: "Loyalität",
    summary: "Punkte und Stufen in allen Geschäften, in denen Sie einkaufen.",
    what: "Zeigt Treueguthaben und Verdienst-/Einlöseraten pro verknüpftem Unternehmen an. Tippen Sie auf ein Geschäft, um Preisdetails anzuzeigen.",
    how: ["Öffnen Sie Loyalty über die Marktplatz-Navigation.", "Tippen Sie auf eine Karte, um Details zum Verdienen/Einlösen zu erhalten."],
    when: "Vor dem Einlösen oder Überprüfen von Prämien.",
    tips: ["Die Tarife ergeben sich aus den Treueeinstellungen jedes Unternehmens."],
  },
  "page.buyer.ar": {
    title: "Kontostand (Kredit)",
    summary: "Ausstehende Salden mit Geschäften.",
    what: "Verbraucheransicht der AR / Kredit-Salden und offenen Rechnungen. Tippen Sie auf eine Rechnung, um sie zu überprüfen und zu bezahlen.",
    how: ["Öffnen Sie den Kontostand über die Marktplatz-Navigation.", "Tippen Sie auf eine Rechnung, um das Fälligkeitsdatum anzuzeigen und zu bezahlen."],
    when: "Bei der Begleichung von Ladenkrediten oder bei der Überprüfung von Gebühren.",
    tips: ["Verknüpfte Kundenprofile synchronisieren die Identität Ihres Verbraucherkontos."],
  },
  "page.buyer.account": {
    title: "Account",
    summary: "Your marketplace profile hub.",
    what: "Shortcuts to Balance/Kredit, Loyalty, and Alerts, plus sign-out.",
    how: [
      "Open Account from the marketplace nav.",
      "Jump to Balance, Loyalty, or Alerts.",
      "Sign out when finished on a shared device.",
    ],
    when: "To manage profile-linked marketplace tools.",
    tips: ["The header avatar also opens Account."],
  },
  "page.buyer.appointmentDetail": {
    title: "Appointment detail",
    summary: "One marketplace booking.",
    what: "Shows service, store, time, staff, notes, and status. Cancel Booked appointments here.",
    how: [
      "Open from Orders → Appointments.",
      "Review time and staff.",
      "Cancel if status is Booked.",
    ],
    when: "Before a visit or when you need to cancel.",
    tips: ["Contact the store if you need to reschedule outside cancel rules."],
  },
  "page.buyer.notifications": {
    title: "Marktplatz-Benachrichtigungen",
    summary: "Bestellen Sie Updates und Nachrichten von Geschäften.",
    what: "In-App-Benachrichtigungen für Ihr Verbraucherkonto (Bestellstatus, Shop-Nachrichten).",
    how: ["Öffnen Sie Warnungen/Benachrichtigungen.", "Markieren Sie Elemente als gelesen, während Sie sie überprüfen."],
    when: "Nachdem Sie Bestellungen aufgegeben haben oder wenn Geschäfte Ihnen eine Nachricht senden.",
    tips: ["Die Benachrichtigungseinstellungen für Mitarbeiter gelten nicht für Verbraucherwarnungen."],
  },
  "page.appointments": {
    title: "Termine",
    summary: "Tagesplan des Teams für gebuchte Dienstleistungen.",
    what: "Zeigt Termine für das ausgewählte Datum und optional eine bestimmte Fachkraft. Buchungen können abgeschlossen oder storniert werden; beim Abschluss kann ein verknüpfter POS-Verkauf vorbereitet werden (SCH-FR-005).",
    how: [
      "Wählen Sie ein Datum und filtern Sie bei Bedarf nach Fachkraft.",
      "Suchen oder filtern Sie nach Status.",
      "Tippen Sie auf „Abschließen“, um einen Termin fertigzustellen, oder bei gebuchten Terminen auf „Stornieren“.",
    ],
    when: "Während des Betriebstags in Salons und anderen Unternehmen mit aktivierter Terminbuchung.",
    tips: ["Kunden buchen über „Buchen“ im Marktplatz; das Team verwaltet hier den Tagesablauf."],
  },
};

export default catalog;
