import type { HelpCatalog } from "./types";

const en: HelpCatalog = {
  "page.dashboard": {
    title: "Dashboard",
    summary: "KPIs plus interactive sales charts filtered by date range.",
    what: "Shows today's sales, cash position, low-stock alerts, pending approvals, and revenue/order trends for a selected date range so owners and managers can decide what to do next.",
    how: [
      "After sign-in, review today's KPI cards.",
      "Set the from/to dates to refresh revenue and order charts.",
      "Hover a chart point for the daily total or ticket count.",
      "Use low-stock or approval cards to jump to Inventory or Returns.",
      "Switch business or branch from the header when you manage multiple locations.",
    ],
    when: "At shift start, end of day, or whenever you need a health check on the branch.",
    tips: [
      "Charts use completed sales for the selected business (RPT-FR-001).",
      "If charts look empty, widen the date range or confirm till activity.",
    ],
  },
  "page.pos": {
    title: "Point of Sale",
    summary: "Fast checkout with cart, customer, and payment.",
    what: "Cashiers can sell products, attach customers for loyalty or khata (credit), apply discounts or coupons, and take payment by cash, card, wallet, or khata.",
    how: [
      "Open a till before taking cash sales.",
      "Add products to the cart by search or barcode scan.",
      "Attach a customer when needed for loyalty or khata.",
      "Review the total, tap Proceed to checkout, and choose a payment method.",
      "Complete the order with Place order, then print or share the receipt.",
    ],
    when: "For every customer checkout at the counter.",
    tips: [
      "Khata payment requires an active khata on the customer.",
      "Keep the till open during the shift and count cash before closing at end of day.",
    ],
  },
  "page.inventory": {
    title: "Inventory & Purchasing",
    summary: "Catalog, on-hand stock, suppliers, purchase orders, transfers, and adjustments.",
    what: "The place to maintain products, view stock levels, buy from suppliers, move stock between branches, and correct quantities.",
    how: [
      "Create or update SKUs and prices from Products.",
      "View on-hand quantity and average cost from Stock.",
      "Add suppliers, then create purchase orders and receive goods (GRN).",
      "Use Transfers to move stock between branches and Adjust to fix quantities.",
    ],
    when: "When receiving goods, adding new items, doing a stock count, or transferring between branches.",
    tips: [
      "Receive against a PO so cost and accounts payable stay accurate.",
      "Use a clear reason code in Adjust for audit trails.",
    ],
  },
  "page.customers": {
    title: "Customers & Khata",
    summary: "Customer profiles, credit/khata balance, ledger, and loyalty points.",
    what: "Stores customer details and lets you enable khata, view the ledger, manage credit limits, and adjust loyalty points.",
    how: [
      "Add a customer with name and phone.",
      "Enable khata for credit sales.",
      "Open Ledger to see debits, credits, and outstanding balance.",
      "Adjust loyalty points for promotions or corrections.",
    ],
    when: "For CRM, credit sales, and loyalty programs.",
    tips: [
      "Attach the customer at POS before khata payment.",
      "Check credit limit before large khata sales.",
    ],
  },
  "page.sales": {
    title: "Sales History",
    summary: "Full list of sales invoices for the selected branch.",
    what: "Shows past checkouts with invoice number, customer, total, status, and time so you can reopen or verify a sale.",
    how: [
      "Search or browse the sales list.",
      "Open a row to view line items and payments.",
      "Use the invoice number when processing a return.",
    ],
    when: "For customer inquiries, audits, reprinting receipts, or before a return.",
    tips: ["Sales appear after a successful POS checkout."],
  },
  "page.returns": {
    title: "Returns & Tills",
    summary: "Refunds on past sales and till open/close history.",
    what: "Staff can look up a sale and submit a return, and view till sessions including over/short amounts.",
    how: [
      "Search by the original sale invoice number.",
      "Submit the return with refund method and reason.",
      "Managers approve or reject pending returns.",
      "Review opening/closing cash and variance in till history.",
    ],
    when: "When issuing refunds, handling damaged goods, or reconciling tills.",
    tips: ["Keep the original invoice—returns link back to that sale."],
  },
  "page.accounting": {
    title: "Accounting",
    summary: "Books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools: chart of accounts, journal entries, trial balance, profit & loss, balance sheet, general ledger, and receivables/payables aging.",
    how: [
      "Browse ledgers in Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Fix source documents before posting manual journals.",
    ],
  },
  "page.hr": {
    title: "HR & Payroll",
    summary: "Employees, attendance, leave, and payroll runs.",
    what: "Manages staff master data, attendance, leave requests, and payroll calculation and approval.",
    how: [
      "Add employees or invite existing users.",
      "Record attendance and review leave requests.",
      "Run payroll for a period, then approve it.",
    ],
    when: "For hiring, daily attendance, leave approval, and salary cycles.",
    tips: ["Payroll approval may require a specific role or bundle."],
  },
  "page.marketing": {
    title: "Marketing",
    summary: "Campaigns, message templates, segments, coupons, and loyalty tiers.",
    what: "Helps you message customers with reusable templates, target segments, set up promo codes, and configure loyalty earn/redeem rates.",
    how: [
      "Create a draft campaign with audience and message.",
      "Reuse templates with {{placeholders}} for consistent copy.",
      "Send when ready—delivery status appears on the campaign.",
      "Build segments and coupons for targeted offers.",
      "Set loyalty tiers based on points bands.",
    ],
    when: "For promotions, festival offers, win-back messages, and loyalty setup.",
    tips: ["Connect customer channels for better delivery."],
  },
  "page.reports": {
    title: "Reports",
    summary: "Operational sales and product performance.",
    what: "Branch reports such as daily sales and top products. Full financial statements live under Accounting.",
    how: [
      "Choose a date range.",
      "Review daily sales and ticket counts.",
      "Check best-selling products by quantity.",
    ],
    when: "For weekly reviews, merchandising decisions, or owner updates.",
    tips: ["Open Accounting for P&L or balance sheet."],
  },
  "page.settings": {
    title: "Settings",
    summary: "Profile, plan limits, billing, notifications, FBR flags, and roles.",
    what: "Account profile for all staff, plus business configuration: subscription usage, notification preferences, integrations, and role access (some tabs are owner-only).",
    how: [
      "Update your profile under the Profile tab.",
      "Review usage against plan limits.",
      "Owners can manage integrations, branding, and roles for the active business.",
    ],
    when: "During onboarding, plan upgrades, or when changing module access.",
    tips: ["Some settings are owner-only—ask the owner if a tab is missing."],
  },
  "page.notifications": {
    title: "Notifications",
    summary: "Leave, payroll, billing, and campaign alerts.",
    what: "System and workflow alerts so approvals and campaign results are not missed.",
    how: [
      "Open Notifications to see unread items.",
      "Click a linked alert to go to the related screen.",
      "Adjust preferences in Settings if alerts are too noisy.",
    ],
    when: "Throughout the day for approvals and operational updates.",
    tips: ["Keep the panel open on busy days so leave and payroll requests stay visible."],
  },
  "page.profile": {
    title: "Your Profile",
    summary: "Personal name, phone, password, and photo.",
    what: "Updates your user account—not full business settings.",
    how: [
      "Change display name and phone.",
      "Set a new password only when you need to change it.",
      "Upload a profile photo when available.",
    ],
    when: "On first login setup or when updating personal details.",
    tips: ["Change language from the profile language control or the sidebar."],
  },
  "page.businesses": {
    title: "Businesses",
    summary: "Owner list of businesses under your account.",
    what: "Create businesses within plan limits and open each for branding, marketplace, and branches.",
    how: [
      "Review the list of active businesses.",
      "Create a new business with name and industry.",
      "Open a row to edit branding, marketplace, and branches.",
    ],
    when: "When onboarding a new store or checking plan capacity.",
    tips: ["Plan limit (402) errors mean you need to upgrade under Settings → Subscriptions."],
  },
  "page.businessDetail": {
    title: "Business detail",
    summary: "Edit one business: branding, marketplace, and branches.",
    what: "Owner tools for a single business identity and locations.",
    how: [
      "Update name, industry, tagline, and brand color.",
      "Upload a logo and configure marketplace listing.",
      "Add or deactivate branches as needed.",
    ],
    when: "When launching a store or refreshing brand look.",
    tips: ["Deactivating keeps historical financial data; it does not hard-delete."],
  },
  "page.ess": {
    title: "Staff Tools (ESS)",
    summary: "Employee self-service for attendance and leave.",
    what: "Staff can check in/out and submit leave without full HR admin access.",
    how: [
      "Mark today's attendance.",
      "Submit leave with dates and reason.",
      "Check approval status after submitting.",
    ],
    when: "Daily for staff using self-service HR.",
    tips: ["Managers still approve leave from the HR Leave tab."],
  },

  "tab.inventory.stock": {
    title: "On-hand Stock",
    summary: "Quantity and average cost for each product at this branch.",
    what: "Inventory balance view after purchases, sales, transfers, and adjustments.",
    how: [
      "Search by SKU or product name.",
      "Review quantity before reordering.",
      "Compare with Products if something looks wrong.",
    ],
    when: "Before placing orders, spot checks, or investigating shortages.",
    tips: ["Average cost updates when goods are received."],
  },
  "tab.inventory.products": {
    title: "Products",
    summary: "Sale items, services, prices, and barcodes.",
    what: "Create and edit products used in POS and stock tracking.",
    how: [
      "Add a product with SKU, name, and price.",
      "Set a barcode for scanning at checkout.",
      "Open a product to view or edit details.",
    ],
    when: "When adding new items or updating prices.",
    tips: ["Keep SKUs unique across the business."],
  },
  "tab.inventory.suppliers": {
    title: "Suppliers",
    summary: "Vendor master for purchasing.",
    what: "Supplier contact, payment terms, and status used on purchase orders.",
    how: [
      "Add a supplier with name and contact details.",
      "Set payment terms before creating a PO.",
      "Open a supplier to view full details.",
    ],
    when: "When setting up purchasing or updating vendor details.",
    tips: ["Do not use inactive suppliers on new POs."],
  },
  "tab.inventory.pos": {
    title: "Purchase Orders",
    summary: "Supplier orders and goods receipt (GRN).",
    what: "Create POs, track status, and receive quantities into stock.",
    how: [
      "Create a PO with supplier and line items.",
      "Receive goods against the PO when stock arrives (GRN).",
      "Open a PO to review lines and status.",
    ],
    when: "When reordering stock from a supplier.",
    tips: ["Receive only what arrived—partial receipts are supported."],
  },
  "tab.inventory.transfers": {
    title: "Transfers",
    summary: "Move stock between branches.",
    what: "Creates a transfer document that must be confirmed so stock moves from one branch to another.",
    how: [
      "Choose destination branch, product, and quantity.",
      "Create the transfer and confirm once goods are moved.",
    ],
    when: "When balancing stock across locations.",
    tips: ["Confirm promptly so on-hand quantities stay accurate."],
  },
  "tab.inventory.adjust": {
    title: "Stock Adjustment",
    summary: "Correct quantity for damage, count variance, or write-offs.",
    what: "Changes quantity (+/−) with a reason code for audit.",
    how: [
      "Choose product and quantity delta.",
      "Select a reason code.",
      "Save to update on-hand stock.",
    ],
    when: "After a physical count or when goods are damaged or lost.",
    tips: ["Prefer GRN/transfers for normal movement; use Adjust for corrections."],
  },

  "tab.accounting.coa": {
    title: "Chart of Accounts",
    summary: "Ledger accounts for journals and statements.",
    what: "List of account codes, names, and types. Edit names when needed.",
    how: ["Browse accounts by code.", "Edit an account to change its label."],
    when: "During setup review or when clearer names are needed.",
    tips: ["Do not delete accounts that already have postings."],
  },
  "tab.accounting.journals": {
    title: "Journals",
    summary: "Manual and system journal entries.",
    what: "Shows posted journals and lets you post balanced manual entries.",
    how: [
      "Open a journal to view debit/credit lines.",
      "Use Post journal for a two-line adjustment when needed.",
    ],
    when: "For corrections, accruals, or reviewing auto-posted entries.",
    tips: ["Debits must equal credits before posting."],
  },
  "tab.accounting.tb": {
    title: "Trial Balance",
    summary: "Account-wise debit/credit totals for a period.",
    what: "Verifies books are balanced before running statements.",
    how: ["Set From/To dates.", "Review account totals."],
    when: "At month-end or before P&L / balance sheet.",
    tips: ["Investigate unexpectedly large balances."],
  },
  "tab.accounting.pl": {
    title: "Profit & Loss",
    summary: "Revenue and expenses for a date range.",
    what: "Profitability for the selected period from posted journals.",
    how: ["Choose dates.", "Read revenue versus expenses."],
    when: "For owner review and period close.",
    tips: ["Accuracy depends on correct account types and postings."],
  },
  "tab.accounting.bs": {
    title: "Balance Sheet",
    summary: "Assets, liabilities, and equity.",
    what: "Position statement as of the end of the selected period.",
    how: ["Set the report date range.", "Review assets versus liabilities sections."],
    when: "For period close and financial discussions.",
    tips: ["AR/AP aging complements customer and supplier balances."],
  },
  "tab.accounting.gl": {
    title: "General Ledger",
    summary: "Line-by-line activity for one account.",
    what: "Debit/credit history for a single account.",
    how: ["Select an account.", "Set dates.", "Review each posting."],
    when: "When investigating balances or reconciling an account.",
    tips: ["Run trial balance first, then open GL for odd accounts."],
  },
  "tab.accounting.ar": {
    title: "AR Aging",
    summary: "Customer receivables by age bucket.",
    what: "Open invoice balances grouped by age (current, 30, 60 days, etc.).",
    how: ["Review buckets.", "Open an invoice for details.", "Follow up with the customer."],
    when: "For collections and credit control.",
    tips: ["Khata/credit sales may appear in AR."],
  },
  "tab.accounting.ap": {
    title: "AP Aging",
    summary: "Supplier payables by age bucket.",
    what: "Bills you owe, grouped by due date.",
    how: ["Review buckets.", "Open a bill for details.", "Plan supplier payments."],
    when: "For supplier payment and cash planning.",
    tips: ["PO receipts often create AP bills."],
  },

  "tab.hr.employees": {
    title: "Employees",
    summary: "Staff master list and employment details.",
    what: "Create employee records, edit base salary, and open profiles.",
    how: [
      "Add an employee or invite an existing user.",
      "Edit title, salary, and status.",
      "Open an employee for full details.",
    ],
    when: "For hiring, role changes, or salary updates.",
    tips: ["Invite links the HR record to login access."],
  },
  "tab.hr.attendance": {
    title: "Attendance",
    summary: "Check-in / check-out history.",
    what: "Attendance rows for payroll and compliance.",
    how: ["Filter by date.", "Fix missing punches via ESS or a manager."],
    when: "For daily operations and before payroll.",
    tips: ["Source may be ESS or manager entry."],
  },
  "tab.hr.leave": {
    title: "Leave",
    summary: "Leave requests and approvals.",
    what: "Managers approve or reject leave based on role permissions.",
    how: [
      "Review pending requests.",
      "Approve or reject carefully.",
      "Confirm dates with the employee if unclear.",
    ],
    when: "When staff request time off.",
    tips: ["Approval depends on leave_approve access."],
  },
  "tab.hr.payroll": {
    title: "Payroll",
    summary: "Pay runs for a selected period.",
    what: "Generate payroll, view runs, and approve when authorized.",
    how: [
      "Set period start and end.",
      "Run payroll.",
      "Open details and approve if you have rights.",
    ],
    when: "At salary cycle close.",
    tips: ["Fix attendance/leave issues before running payroll."],
  },

  "page.marketing.template": {
    title: "Message template",
    summary: "Preview how a CRM template looks when sent to customers.",
    what: "Shows the raw title/body placeholders and an interpolated preview using live business branding plus sample customer values.",
    how: [
      "Open a template from Marketing → Templates.",
      "Review placeholders in the overview.",
      "Check the customer preview with sample values.",
      "Use Back to return to the Templates tab.",
    ],
    when: "When drafting reusable campaign messages or checking SMS length.",
    tips: ["Placeholders are flat keys like {{business}} — nested {{customer.name}} is not supported."],
  },

  "tab.marketing.campaigns": {
    title: "Campaigns",
    summary: "Draft and send customer messages.",
    what: "Create marketing campaigns, choose audience, and send with delivery summary.",
    how: [
      "Create a draft campaign.",
      "Review audience and message.",
      "Send when ready and open results for details.",
    ],
    when: "For promotions and customer outreach.",
    tips: ["Drafts can be edited before sending."],
  },
  "tab.marketing.segments": {
    title: "Segments",
    summary: "Saved customer audiences for targeting.",
    what: "Reusable filters for campaigns (e.g. by loyalty).",
    how: ["Build a segment with filters.", "Reuse it when composing a campaign."],
    when: "For targeted offers instead of blasting everyone.",
    tips: ["Keep segment names descriptive."],
  },
  "tab.marketing.coupons": {
    title: "Coupons",
    summary: "Promo codes for POS checkout.",
    what: "Discount codes cashiers can enter in the cart.",
    how: [
      "Create a code and discount value.",
      "Share with customers.",
      "Enter the code at POS before checkout.",
    ],
    when: "For discount campaigns and partner offers.",
    tips: ["Set usage limits so codes are not over-redeemed."],
  },
  "tab.marketing.tiers": {
    title: "Loyalty Tiers",
    summary: "Earn/redeem rates by points band.",
    what: "Configures how quickly customers earn and redeem points.",
    how: [
      "Add a tier with minimum points.",
      "Set earn/redeem multipliers.",
      "Test with a sample customer.",
    ],
    when: "When launching or tuning loyalty.",
    tips: ["Higher tiers usually earn faster—communicate this to customers."],
  },

  "tab.settings.notifications": {
    title: "Notification Preferences",
    summary: "Choose which alerts you receive.",
    what: "Per-user toggles for notification types.",
    how: ["Open the Notifications tab in Settings.", "Turn types on or off as needed."],
    when: "When alerts are too noisy or important items are being missed.",
    tips: ["These preferences apply to your user, not the whole business."],
  },
  "tab.settings.profile": {
    title: "Profile",
    summary: "Your name, phone, password, photo, and language.",
    what: "Staff account settings shared by every role — not business branding.",
    how: [
      "Update display name and phone.",
      "Upload a profile photo.",
      "Change language or set a new password when needed.",
    ],
    when: "On first login or whenever personal details change.",
    tips: ["Business branding lives under Branding or Businesses, not Profile."],
  },
  "tab.settings.subscriptions": {
    title: "Subscription & Usage",
    summary: "Plan status and seat/branch limits.",
    what: "Current plan, status, usage of businesses/branches/users versus limits, and Safepay upgrade checkout (JazzCash, Easypaisa, or card).",
    how: [
      "Review usage counters.",
      "Choose a plan and pay with JazzCash, Easypaisa, or card to upgrade.",
    ],
    when: "When approaching limits or at billing renewal.",
    tips: ["Owner access is required for this tab."],
  },
  "tab.settings.integrations": {
    title: "Integrations",
    summary: "External connections and compliance flags.",
    what: "Owner tools to connect services for the business (e.g. FBR flags).",
    how: ["Review available integration settings.", "Change flags only when you understand the impact."],
    when: "When setting up integrations or compliance.",
    tips: ["Wrong flags can affect tax reporting—confirm with your accountant."],
  },
  "tab.settings.roles": {
    title: "Roles",
    summary: "Who can access which modules.",
    what: "Owner configuration of role-based access on Kaarobar bundles.",
    how: ["Review role assignments.", "Change carefully—staff may lose access."],
    when: "When hiring, promoting, or tightening security.",
    tips: ["Least privilege: give each role only the bundles they need."],
  },
  "tab.settings.branding": {
    title: "Store branding",
    summary: "Logo, colors, and marketplace listing for your business.",
    what: "Controls how your store looks in Discover/catalog and remaps the in-app UI scheme (buttons, focus rings, nav) from primary color.",
    how: [
      "Upload a logo and pick a primary brand color.",
      "Add tagline and marketplace description.",
      "Save branding, then preview Discover or shop as a consumer.",
    ],
    when: "Before going live on the marketplace or refreshing brand look.",
    tips: ["Owner access is required. Saving branding updates the staff workspace theme immediately."],
  },
  "tab.marketing.templates": {
    title: "Message templates",
    summary: "Reusable CRM message bodies with variables.",
    what: "Saved templates for campaigns and previews (business name, tagline, etc.).",
    how: [
      "Create a template in the modal with placeholders.",
      "Browse available {{variables}} on the Templates tab.",
      "Open a template to preview interpolated customer copy.",
      "Select the template when composing a campaign.",
    ],
    when: "When standardizing promotional or transactional messages.",
    tips: ["Keep templates short for SMS/WhatsApp channels.", "Only flat keys like {{name}} work — not {{customer.name}}."],
  },

  "page.market.discover": {
    title: "Discover products",
    summary: "Browse products from every marketplace shop, or switch to Shops.",
    what: "Product-first feed across marketplace-enabled businesses, with search, industry/category filters, and pagination. A Shops tab lists storefronts.",
    how: [
      "Search products and filter by industry or category.",
      "Load more to page through results.",
      "Open a product for detail and the selling shop.",
      "Switch to Shops to browse by storefront.",
      "Add items from one or many shops — checkout places one pickup order per shop.",
    ],
    when: "Whenever you want to find items without browsing stores one by one.",
    tips: ["Use Shops when you already know which storefront to visit."],
  },
  "page.market.products": {
    title: "All products",
    summary: "Cross-store product feed from marketplace businesses.",
    what: "Shows sellable products from every marketplace-enabled store. Search and filter, then open a product for details or the store catalog.",
    how: [
      "Search by name or filter by category/industry.",
      "Open a product card for detail, price, and add to cart.",
      "Use Visit store / back links to shop the full catalog.",
    ],
    when: "When you want to find an item without browsing stores one by one.",
    tips: ["If the feed is empty, catalogs may not be published yet—try Discover."],
  },
  "page.market.productDetail": {
    title: "Product detail",
    summary: "One product from a marketplace store.",
    what: "Shows image, price, description, and quantity controls. Adds the line to that store’s cart bag.",
    how: [
      "Adjust quantity and tap Add to cart.",
      "Open the store link to keep shopping.",
      "Checkout from the sticky cart when ready.",
    ],
    when: "After tapping a product from Products or a store grid.",
    tips: ["Sign in as a consumer before adding to cart."],
  },
  "page.market.catalog": {
    title: "Store catalog",
    summary: "Products from one marketplace store.",
    what: "Branded product grid for a single business—filter by category, search, and price, then add to cart.",
    how: [
      "Tap Shop when the store also offers booking.",
      "Use filters to narrow the catalog.",
      "Tap Add to put items in your cart (multi-store carts are allowed).",
      "Open View cart or the navbar cart to checkout.",
    ],
    when: "While shopping a specific store for pickup.",
    tips: ["Each store keeps its own bag in the cart until you place orders."],
  },
  "page.market.book": {
    title: "Book a service",
    summary: "Self-book an appointment at a service store.",
    what: "Pick a service, optional staff member, available time slot, then confirm. Uses portal appointment APIs (CUS-FR-005).",
    how: [
      "Open Book on a salon or appointments-enabled store.",
      "Choose a service, then Any staff or a specific person.",
      "Pick a date and open slot, add optional notes, and confirm.",
      "Find the booking under Orders → Appointments.",
    ],
    when: "When you want a timed visit instead of ordering products.",
    tips: ["Sign in as a consumer account before booking."],
  },
  "tab.market.shop": {
    title: "Shop tab",
    summary: "Order products for pickup.",
    what: "Shows sellable goods from this store’s catalog.",
    how: ["Browse or search products.", "Add to cart and checkout."],
    when: "Hybrid stores that sell goods and take appointments.",
  },
  "tab.market.book": {
    title: "Book tab",
    summary: "Book a service appointment.",
    what: "Service → staff → slot → confirm booking flow.",
    how: ["Select a service.", "Choose staff or Any available.", "Confirm a time."],
    when: "On appointments-enabled businesses with service products.",
  },
  "page.checkout.review": {
    title: "Review cart",
    summary: "Edit quantities before payment.",
    what: "Shows every store bag in your cart with line items, subtotals, and a grand total.",
    how: [
      "Adjust quantities or remove lines per store.",
      "Clear a store bag or keep shopping that store.",
      "Continue to contact & payment.",
    ],
    when: "After adding products and before placing pickup orders.",
    tips: ["Empty cart returns you to Discover."],
  },
  "page.checkout.pay": {
    title: "Contact & payment",
    summary: "Pickup contact details and place orders.",
    what: "Collects name, phone, and pickup notes, then places one order per store with the same contact info.",
    how: [
      "Confirm or edit contact name and phone.",
      "Add optional pickup notes.",
      "Choose card or wallet (stub) and place order(s).",
    ],
    when: "Final step before orders appear under Orders.",
    tips: ["Multi-store checkout creates separate invoices per business."],
  },
  "page.buyer.orders": {
    title: "Orders & bookings",
    summary: "Your marketplace pickup orders and appointments.",
    what: "Lists online orders you placed and upcoming/past appointments across stores. Cancel Booked appointments from the Appointments tab.",
    how: [
      "Open Orders from the marketplace nav.",
      "Use the Orders tab for pickup invoices; Appointments for bookings.",
      "Tap an order to see items, payments, and status.",
      "Cancel a Booked appointment if you need to reschedule later.",
    ],
    when: "To track Placed → Confirmed → Ready → Completed, or upcoming visits.",
    tips: ["Contact the store if pickup or appointment timing changes."],
  },
  "tab.buyer.orders": {
    title: "Orders tab",
    summary: "Pickup order history.",
    what: "Online marketplace orders with status and store name.",
    how: ["Tap an order for line items and totals."],
    when: "After placing a pickup order.",
  },
  "tab.buyer.appointments": {
    title: "Appointments tab",
    summary: "Upcoming and past bookings.",
    what: "Service appointments you booked at marketplace stores.",
    how: ["Review upcoming visits.", "Cancel Booked appointments when needed."],
    when: "After booking a salon or service visit.",
  },
  "page.buyer.orderDetail": {
    title: "Order detail",
    summary: "Line items and totals for one pickup order.",
    what: "Shows invoice number, store, status, each line, tax/discount, and payment methods.",
    how: ["Open from Order history.", "Review items before pickup."],
    when: "After placing an order or when checking pickup readiness.",
    tips: ["Status updates appear here as the store progresses your order."],
  },
  "page.buyer.loyalty": {
    title: "Loyalty",
    summary: "Points and tiers across stores you shop.",
    what: "Shows loyalty balances and earn/redeem rates per linked business. Tap a store for rate details.",
    how: [
      "Open Loyalty from the marketplace nav.",
      "Tap a card for earn/redeem details.",
      "Open Balance from Loyalty or Account for khata invoices.",
    ],
    when: "Before redeeming or checking rewards.",
    tips: ["Rates come from each business’s loyalty settings."],
  },
  "page.buyer.ar": {
    title: "Balance (khata)",
    summary: "Outstanding balances with stores.",
    what: "Consumer view of AR / khata balances and open invoices. Tap an invoice to review and pay.",
    how: [
      "Open Account → Balance & khata, or the Balance link on Loyalty.",
      "Tap an invoice for due date and pay.",
    ],
    when: "When settling store credit or checking dues.",
    tips: ["Linked customer profiles sync identity from your consumer account."],
  },
  "page.buyer.account": {
    title: "Accounts",
    summary: "Your marketplace profile hub.",
    what: "Shortcuts to Balance/khata, Loyalty, and Alerts, plus sign-out.",
    how: [
      "Open Accounts from the marketplace nav.",
      "Jump to Balance, Loyalty, or Alerts.",
      "Sign out when finished on a shared device.",
    ],
    when: "To manage profile-linked marketplace tools.",
    tips: ["The header avatar also opens Accounts."],
  },
  "page.buyer.appointmentDetail": {
    title: "Appointment detail",
    summary: "One marketplace booking.",
    what: "Shows service, store, time, staff, notes, and status. Cancel Booked appointments here.",
    how: [
      "Open from Orders → Appointments.",
      "Review time and staff.",
      "Cancel if status is Booked.",
    ],
    when: "Before a visit or when you need to cancel.",
    tips: ["Contact the store if you need to reschedule outside cancel rules."],
  },
  "page.buyer.notifications": {
    title: "Marketplace alerts",
    summary: "Order updates and messages from stores.",
    what: "In-app notifications for your consumer account (order status, store messages).",
    how: ["Open Account → Alerts, or the bell in the header.", "Mark items read as you review them."],
    when: "After placing orders or when stores message you.",
    tips: ["Staff notification preferences do not apply to consumer alerts."],
  },
  "page.appointments": {
    title: "Appointments",
    summary: "Staff day schedule for service bookings.",
    what: "Lists appointments for the selected date (and optional staff). Complete or cancel bookings; completion can link a POS sale stub (SCH-FR-005).",
    how: [
      "Pick a date and optionally filter by staff.",
      "Search or filter by status.",
      "Tap Complete to advance a visit, or Cancel for Booked rows.",
    ],
    when: "On salon / appointments-enabled businesses during the service day.",
    tips: ["Customers book from the marketplace Book flow; staff manage the day here."],
  },
};

export default en;
