import type { HelpCatalog } from "./types";

const en: HelpCatalog = {
  "page.dashboard": {
    title: "Dashboard",
    summary: "Quick view of sales, cash, stock risk, and pending approvals.",
    what: "Shows today's sales, cash position, low-stock alerts, and tasks waiting for approval so owners and managers can decide what to do next.",
    how: [
      "After sign-in, open the dashboard and review today's numbers.",
      "Use low-stock or approval cards to jump to Inventory or HR.",
      "If you have multiple locations, switch business or branch from the header.",
      "Open POS when you're ready to start selling.",
    ],
    when: "At shift start, end of day, or whenever you need a health check on the branch.",
    tips: [
      "Figures reflect the selected business and branch.",
      "If KPIs look empty, check the branch and today's till activity.",
    ],
  },
  "page.pos": {
    title: "Point of Sale",
    summary: "Fast checkout with cart, customer, and payment.",
    what: "Cashiers can sell products, attach customers for loyalty or khata (credit), apply discounts or coupons, and take payment by cash, card, wallet, or khata.",
    how: [
      "Open a till before taking cash sales.",
      "Add products to the cart by search or barcode scan.",
      "Attach a customer when needed for loyalty or khata.",
      "Review the total, tap Proceed to checkout, and choose a payment method.",
      "Complete the order with Place order, then print or share the receipt.",
    ],
    when: "For every customer checkout at the counter.",
    tips: [
      "Khata payment requires an active khata on the customer.",
      "Keep the till open during the shift and count cash before closing at end of day.",
    ],
  },
  "page.inventory": {
    title: "Inventory & Purchasing",
    summary: "Catalog, on-hand stock, suppliers, purchase orders, transfers, and adjustments.",
    what: "The place to maintain products, view stock levels, buy from suppliers, move stock between branches, and correct quantities.",
    how: [
      "Create or update SKUs and prices from Products.",
      "View on-hand quantity and average cost from Stock.",
      "Add suppliers, then create purchase orders and receive goods (GRN).",
      "Use Transfers to move stock between branches and Adjust to fix quantities.",
    ],
    when: "When receiving goods, adding new items, doing a stock count, or transferring between branches.",
    tips: [
      "Receive against a PO so cost and accounts payable stay accurate.",
      "Use a clear reason code in Adjust for audit trails.",
    ],
  },
  "page.customers": {
    title: "Customers & Khata",
    summary: "Customer profiles, credit/khata balance, ledger, and loyalty points.",
    what: "Stores customer details and lets you enable khata, view the ledger, manage credit limits, and adjust loyalty points.",
    how: [
      "Add a customer with name and phone.",
      "Enable khata for credit sales.",
      "Open Ledger to see debits, credits, and outstanding balance.",
      "Adjust loyalty points for promotions or corrections.",
    ],
    when: "For CRM, credit sales, and loyalty programs.",
    tips: [
      "Attach the customer at POS before khata payment.",
      "Check credit limit before large khata sales.",
    ],
  },
  "page.sales": {
    title: "Sales History",
    summary: "Full list of sales invoices for the selected branch.",
    what: "Shows past checkouts with invoice number, customer, total, status, and time so you can reopen or verify a sale.",
    how: [
      "Search or browse the sales list.",
      "Open a row to view line items and payments.",
      "Use the invoice number when processing a return.",
    ],
    when: "For customer inquiries, audits, reprinting receipts, or before a return.",
    tips: ["Sales appear after a successful POS checkout."],
  },
  "page.returns": {
    title: "Returns & Tills",
    summary: "Refunds on past sales and till open/close history.",
    what: "Staff can look up a sale and submit a return, and view till sessions including over/short amounts.",
    how: [
      "Search by the original sale invoice number.",
      "Submit the return with refund method and reason.",
      "Managers approve or reject pending returns.",
      "Review opening/closing cash and variance in till history.",
    ],
    when: "When issuing refunds, handling damaged goods, or reconciling tills.",
    tips: ["Keep the original invoice—returns link back to that sale."],
  },
  "page.accounting": {
    title: "Accounting",
    summary: "Books, journals, statements, and AR/AP aging.",
    what: "Double-entry tools: chart of accounts, journal entries, trial balance, profit & loss, balance sheet, general ledger, and receivables/payables aging.",
    how: [
      "Browse ledgers in Chart of accounts.",
      "Post manual corrections from Journals.",
      "Run Trial balance, P&L, Balance sheet, or GL for a date range.",
      "Follow up on overdue invoices and bills from AR/AP aging.",
    ],
    when: "For month-end close, owner reporting, or collections and payments follow-up.",
    tips: [
      "POS and inventory create many journals automatically.",
      "Fix source documents before posting manual journals.",
    ],
  },
  "page.hr": {
    title: "HR & Payroll",
    summary: "Employees, attendance, leave, and payroll runs.",
    what: "Manages staff master data, attendance, leave requests, and payroll calculation and approval.",
    how: [
      "Add employees or invite existing users.",
      "Record attendance and review leave requests.",
      "Run payroll for a period, then approve it.",
    ],
    when: "For hiring, daily attendance, leave approval, and salary cycles.",
    tips: ["Payroll approval may require a specific role or bundle."],
  },
  "page.marketing": {
    title: "Marketing",
    summary: "Campaigns, segments, coupons, and loyalty tiers.",
    what: "Helps you message customers, target segments, set up promo codes, and configure loyalty earn/redeem rates.",
    how: [
      "Create a draft campaign with audience and message.",
      "Send when ready—delivery status appears on the campaign.",
      "Build segments and coupons for targeted offers.",
      "Set loyalty tiers based on points bands.",
    ],
    when: "For promotions, festival offers, win-back messages, and loyalty setup.",
    tips: ["Connect customer channels for better delivery."],
  },
  "page.reports": {
    title: "Reports",
    summary: "Operational sales and product performance.",
    what: "Branch reports such as daily sales and top products. Full financial statements live under Accounting.",
    how: [
      "Choose a date range.",
      "Review daily sales and ticket counts.",
      "Check best-selling products by quantity.",
    ],
    when: "For weekly reviews, merchandising decisions, or owner updates.",
    tips: ["Open Accounting for P&L or balance sheet."],
  },
  "page.settings": {
    title: "Settings",
    summary: "Plan limits, billing, notifications, FBR flags, and roles.",
    what: "Business configuration: subscription usage, notification preferences, integrations, and role access (some tabs are owner-only).",
    how: [
      "Review usage against plan limits.",
      "Update your notification preferences.",
      "Owners can manage integrations and roles.",
    ],
    when: "During onboarding, plan upgrades, or when changing module access.",
    tips: ["Some settings are owner-only—ask the owner if a tab is missing."],
  },
  "page.notifications": {
    title: "Notifications",
    summary: "Leave, payroll, billing, and campaign alerts.",
    what: "System and workflow alerts so approvals and campaign results are not missed.",
    how: [
      "Open Notifications to see unread items.",
      "Click a linked alert to go to the related screen.",
      "Adjust preferences in Settings if alerts are too noisy.",
    ],
    when: "Throughout the day for approvals and operational updates.",
    tips: ["Keep the panel open on busy days so leave and payroll requests stay visible."],
  },
  "page.profile": {
    title: "Your Profile",
    summary: "Personal name, phone, language, password, and photo.",
    what: "Updates your user account—not full business settings.",
    how: [
      "Change display name and phone.",
      "Choose English or Urdu (Urdu enables RTL layout).",
      "Set a new password only when you need to change it.",
      "Upload a profile photo when available.",
    ],
    when: "On first login setup or when updating personal details.",
    tips: ["Language preference is saved for this device/session."],
  },
  "page.ess": {
    title: "Staff Tools (ESS)",
    summary: "Employee self-service for attendance and leave.",
    what: "Staff can check in/out and submit leave without full HR admin access.",
    how: [
      "Mark today's attendance.",
      "Submit leave with dates and reason.",
      "Check approval status after submitting.",
    ],
    when: "Daily for staff using self-service HR.",
    tips: ["Managers still approve leave from the HR Leave tab."],
  },

  "tab.inventory.stock": {
    title: "On-hand Stock",
    summary: "Quantity and average cost for each product at this branch.",
    what: "Inventory balance view after purchases, sales, transfers, and adjustments.",
    how: [
      "Search by SKU or product name.",
      "Review quantity before reordering.",
      "Compare with Products if something looks wrong.",
    ],
    when: "Before placing orders, spot checks, or investigating shortages.",
    tips: ["Average cost updates when goods are received."],
  },
  "tab.inventory.products": {
    title: "Products",
    summary: "Sale items, services, prices, and barcodes.",
    what: "Create and edit products used in POS and stock tracking.",
    how: [
      "Add a product with SKU, name, and price.",
      "Set a barcode for scanning at checkout.",
      "Open a product to view or edit details.",
    ],
    when: "When adding new items or updating prices.",
    tips: ["Keep SKUs unique across the business."],
  },
  "tab.inventory.suppliers": {
    title: "Suppliers",
    summary: "Vendor master for purchasing.",
    what: "Supplier contact, payment terms, and status used on purchase orders.",
    how: [
      "Add a supplier with name and contact details.",
      "Set payment terms before creating a PO.",
      "Open a supplier to view full details.",
    ],
    when: "When setting up purchasing or updating vendor details.",
    tips: ["Do not use inactive suppliers on new POs."],
  },
  "tab.inventory.pos": {
    title: "Purchase Orders",
    summary: "Supplier orders and goods receipt (GRN).",
    what: "Create POs, track status, and receive quantities into stock.",
    how: [
      "Create a PO with supplier and line items.",
      "Receive goods against the PO when stock arrives (GRN).",
      "Open a PO to review lines and status.",
    ],
    when: "When reordering stock from a supplier.",
    tips: ["Receive only what arrived—partial receipts are supported."],
  },
  "tab.inventory.transfers": {
    title: "Transfers",
    summary: "Move stock between branches.",
    what: "Creates a transfer document that must be confirmed so stock moves from one branch to another.",
    how: [
      "Choose destination branch, product, and quantity.",
      "Create the transfer and confirm once goods are moved.",
    ],
    when: "When balancing stock across locations.",
    tips: ["Confirm promptly so on-hand quantities stay accurate."],
  },
  "tab.inventory.adjust": {
    title: "Stock Adjustment",
    summary: "Correct quantity for damage, count variance, or write-offs.",
    what: "Changes quantity (+/−) with a reason code for audit.",
    how: [
      "Choose product and quantity delta.",
      "Select a reason code.",
      "Save to update on-hand stock.",
    ],
    when: "After a physical count or when goods are damaged or lost.",
    tips: ["Prefer GRN/transfers for normal movement; use Adjust for corrections."],
  },

  "tab.accounting.coa": {
    title: "Chart of Accounts",
    summary: "Ledger accounts for journals and statements.",
    what: "List of account codes, names, and types. Edit names when needed.",
    how: ["Browse accounts by code.", "Edit an account to change its label."],
    when: "During setup review or when clearer names are needed.",
    tips: ["Do not delete accounts that already have postings."],
  },
  "tab.accounting.journals": {
    title: "Journals",
    summary: "Manual and system journal entries.",
    what: "Shows posted journals and lets you post balanced manual entries.",
    how: [
      "Open a journal to view debit/credit lines.",
      "Use Post journal for a two-line adjustment when needed.",
    ],
    when: "For corrections, accruals, or reviewing auto-posted entries.",
    tips: ["Debits must equal credits before posting."],
  },
  "tab.accounting.tb": {
    title: "Trial Balance",
    summary: "Account-wise debit/credit totals for a period.",
    what: "Verifies books are balanced before running statements.",
    how: ["Set From/To dates.", "Review account totals."],
    when: "At month-end or before P&L / balance sheet.",
    tips: ["Investigate unexpectedly large balances."],
  },
  "tab.accounting.pl": {
    title: "Profit & Loss",
    summary: "Revenue and expenses for a date range.",
    what: "Profitability for the selected period from posted journals.",
    how: ["Choose dates.", "Read revenue versus expenses."],
    when: "For owner review and period close.",
    tips: ["Accuracy depends on correct account types and postings."],
  },
  "tab.accounting.bs": {
    title: "Balance Sheet",
    summary: "Assets, liabilities, and equity.",
    what: "Position statement as of the end of the selected period.",
    how: ["Set the report date range.", "Review assets versus liabilities sections."],
    when: "For period close and financial discussions.",
    tips: ["AR/AP aging complements customer and supplier balances."],
  },
  "tab.accounting.gl": {
    title: "General Ledger",
    summary: "Line-by-line activity for one account.",
    what: "Debit/credit history for a single account.",
    how: ["Select an account.", "Set dates.", "Review each posting."],
    when: "When investigating balances or reconciling an account.",
    tips: ["Run trial balance first, then open GL for odd accounts."],
  },
  "tab.accounting.ar": {
    title: "AR Aging",
    summary: "Customer receivables by age bucket.",
    what: "Open invoice balances grouped by age (current, 30, 60 days, etc.).",
    how: ["Review buckets.", "Open an invoice for details.", "Follow up with the customer."],
    when: "For collections and credit control.",
    tips: ["Khata/credit sales may appear in AR."],
  },
  "tab.accounting.ap": {
    title: "AP Aging",
    summary: "Supplier payables by age bucket.",
    what: "Bills you owe, grouped by due date.",
    how: ["Review buckets.", "Open a bill for details.", "Plan supplier payments."],
    when: "For supplier payment and cash planning.",
    tips: ["PO receipts often create AP bills."],
  },

  "tab.hr.employees": {
    title: "Employees",
    summary: "Staff master list and employment details.",
    what: "Create employee records, edit base salary, and open profiles.",
    how: [
      "Add an employee or invite an existing user.",
      "Edit title, salary, and status.",
      "Open an employee for full details.",
    ],
    when: "For hiring, role changes, or salary updates.",
    tips: ["Invite links the HR record to login access."],
  },
  "tab.hr.attendance": {
    title: "Attendance",
    summary: "Check-in / check-out history.",
    what: "Attendance rows for payroll and compliance.",
    how: ["Filter by date.", "Fix missing punches via ESS or a manager."],
    when: "For daily operations and before payroll.",
    tips: ["Source may be ESS or manager entry."],
  },
  "tab.hr.leave": {
    title: "Leave",
    summary: "Leave requests and approvals.",
    what: "Managers approve or reject leave based on role permissions.",
    how: [
      "Review pending requests.",
      "Approve or reject carefully.",
      "Confirm dates with the employee if unclear.",
    ],
    when: "When staff request time off.",
    tips: ["Approval depends on leave_approve access."],
  },
  "tab.hr.payroll": {
    title: "Payroll",
    summary: "Pay runs for a selected period.",
    what: "Generate payroll, view runs, and approve when authorized.",
    how: [
      "Set period start and end.",
      "Run payroll.",
      "Open details and approve if you have rights.",
    ],
    when: "At salary cycle close.",
    tips: ["Fix attendance/leave issues before running payroll."],
  },

  "tab.marketing.campaigns": {
    title: "Campaigns",
    summary: "Draft and send customer messages.",
    what: "Create marketing campaigns, choose audience, and send with delivery summary.",
    how: [
      "Create a draft campaign.",
      "Review audience and message.",
      "Send when ready and open results for details.",
    ],
    when: "For promotions and customer outreach.",
    tips: ["Drafts can be edited before sending."],
  },
  "tab.marketing.segments": {
    title: "Segments",
    summary: "Saved customer audiences for targeting.",
    what: "Reusable filters for campaigns (e.g. by loyalty).",
    how: ["Build a segment with filters.", "Reuse it when composing a campaign."],
    when: "For targeted offers instead of blasting everyone.",
    tips: ["Keep segment names descriptive."],
  },
  "tab.marketing.coupons": {
    title: "Coupons",
    summary: "Promo codes for POS checkout.",
    what: "Discount codes cashiers can enter in the cart.",
    how: [
      "Create a code and discount value.",
      "Share with customers.",
      "Enter the code at POS before checkout.",
    ],
    when: "For discount campaigns and partner offers.",
    tips: ["Set usage limits so codes are not over-redeemed."],
  },
  "tab.marketing.tiers": {
    title: "Loyalty Tiers",
    summary: "Earn/redeem rates by points band.",
    what: "Configures how quickly customers earn and redeem points.",
    how: [
      "Add a tier with minimum points.",
      "Set earn/redeem multipliers.",
      "Test with a sample customer.",
    ],
    when: "When launching or tuning loyalty.",
    tips: ["Higher tiers usually earn faster—communicate this to customers."],
  },

  "tab.settings.notifications": {
    title: "Notification Preferences",
    summary: "Choose which alerts you receive.",
    what: "Per-user toggles for notification types.",
    how: ["Open the Notifications tab in Settings.", "Turn types on or off as needed."],
    when: "When alerts are too noisy or important items are being missed.",
    tips: ["These preferences apply to your user, not the whole business."],
  },
  "tab.settings.subscriptions": {
    title: "Subscription & Usage",
    summary: "Plan status and seat/branch limits.",
    what: "Current plan, status, and usage of businesses/branches/users versus limits.",
    how: ["Review usage counters.", "Use the upgrade link if available."],
    when: "When approaching limits or at billing renewal.",
    tips: ["Owner access is required for this tab."],
  },
  "tab.settings.integrations": {
    title: "Integrations",
    summary: "External connections and compliance flags.",
    what: "Owner tools to connect services for the business (e.g. FBR flags).",
    how: ["Review available integration settings.", "Change flags only when you understand the impact."],
    when: "When setting up integrations or compliance.",
    tips: ["Wrong flags can affect tax reporting—confirm with your accountant."],
  },
  "tab.settings.roles": {
    title: "Roles",
    summary: "Who can access which modules.",
    what: "Owner configuration of role-based access on Kaarobar bundles.",
    how: ["Review role assignments.", "Change carefully—staff may lose access."],
    when: "When hiring, promoting, or tightening security.",
    tips: ["Least privilege: give each role only the bundles they need."],
  },
};

export default en;
