import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Panel de control",
    summary: "Vista rápida de ventas, caja, riesgo bursátil y aprobaciones pendientes.",
    what: "Muestra las ventas actuales, la posición de efectivo, las alertas de existencias bajas y las tareas en espera de aprobación para que los propietarios y gerentes puedan decidir qué hacer a continuación.",
    how: [
      "Después de iniciar sesión, abra el panel y revise los números de hoy.",
      "Utilice tarjetas de aprobación o de stock bajo para pasar a Inventario o Recursos Humanos.",
      "Si tiene varias ubicaciones, cambie de negocio o sucursal desde el encabezado.",
      "Abra POS cuando esté listo para comenzar a vender.",
    ],
    when: "Al inicio del turno, al final del día o cuando necesites un control de salud en la sucursal.",
    tips: [
      "Las cifras reflejan el negocio y rama seleccionados.",
      "Si los KPI parecen vacíos, verifique la sucursal y la actividad de caja de hoy.",
    ],
  },
  "page.pos": {
    title: "Punto de Venta",
    summary: "Pago rápido con carrito, cliente y pago.",
    what: "Los cajeros pueden vender productos, vincular clientes por fidelidad o khata (crédito), aplicar descuentos o cupones y aceptar pagos en efectivo, tarjeta, billetera o khata.",
    how: [
      "Abra una caja antes de realizar ventas en efectivo.",
      "Agregue productos al carrito mediante búsqueda o escaneo de código de barras.",
      "Adjunte un cliente cuando sea necesario para fidelizarlo o khata.",
      "Revise el total, toque Continuar con el pago y elija un método de pago.",
      "Complete el pedido con Realizar pedido y luego imprima o comparta el recibo.",
    ],
    when: "Por cada pago del cliente en el mostrador.",
    tips: [
      "El pago Khata requiere un khata activo en el cliente.",
      "Mantenga la caja abierta durante el turno y cuente el efectivo antes de cerrar al final del día.",
    ],
  },
  "page.inventory": {
    title: "Inventario y compras",
    summary: "Catálogo, stock disponible, proveedores, órdenes de compra, traslados y ajustes.",
    what: "El lugar para mantener productos, ver niveles de stock, comprar a proveedores, mover stock entre sucursales y corregir cantidades.",
    how: [
      "Cree o actualice SKU y precios de Productos.",
      "Vea la cantidad disponible y el costo promedio del inventario.",
      "Agregue proveedores, luego cree órdenes de compra y reciba mercancías (GRN).",
      "Utilice Transferencias para mover stock entre sucursales y Ajustar para fijar cantidades.",
    ],
    when: "Al recibir mercancías, agregar nuevos artículos, realizar un recuento de existencias o realizar transferencias entre sucursales.",
    tips: [
      "Reciba contra una orden de compra para que los costos y las cuentas por pagar se mantengan precisos.",
      "Utilice un código de motivo claro en Ajustar para los seguimientos de auditoría.",
    ],
  },
  "page.customers": {
    title: "Clientes y Khata",
    summary: "Perfiles de clientes, saldo de crédito/khata, libro mayor y puntos de fidelidad.",
    what: "Almacena los detalles del cliente y le permite habilitar khata, ver el libro mayor, administrar los límites de crédito y ajustar los puntos de fidelidad.",
    how: [
      "Agregue un cliente con nombre y teléfono.",
      "Habilite khata para ventas a crédito.",
      "Abra Ledger para ver débitos, créditos y saldo pendiente.",
      "Ajustar puntos de fidelidad por promociones o correcciones.",
    ],
    when: "Para CRM, ventas a crédito y programas de fidelización.",
    tips: [
      "Adjunte al cliente en POS antes del pago khata.",
      "Verifique el límite de crédito antes de grandes ventas de khata.",
    ],
  },
  "page.sales": {
    title: "Historial de ventas",
    summary: "Listado completo de facturas de venta de la sucursal seleccionada.",
    what: "Muestra pagos anteriores con número de factura, cliente, total, estado y hora para que pueda reabrir o verificar una venta.",
    how: [
      "Busque o explore la lista de ventas.",
      "Abra una fila para ver partidas y pagos.",
      "Utilice el número de factura al procesar una devolución.",
    ],
    when: "Para consultas de clientes, auditorías, reimpresión de recibos o antes de una devolución.",
    tips: ["Las ventas aparecen después de un pago exitoso POS."],
  },
  "page.returns": {
    title: "Devoluciones y Cajas",
    summary: "Reembolsos sobre ventas pasadas y hasta el historial de apertura/cierre.",
    what: "El personal puede buscar una venta y enviar una devolución, y ver sesiones de caja que incluyen montos excesivos o insuficientes.",
    how: [
      "Busque por el número de factura de venta original.",
      "Envíe la devolución con el método de reembolso y el motivo.",
      "Los directivos aprueban o rechazan las devoluciones pendientes.",
      "Revise el efectivo de apertura/cierre y la variación en el historial de caja.",
    ],
    when: "Al emitir reembolsos, manipular mercancías dañadas o conciliar cajas.",
    tips: ["Conserve la factura original: devuelve el enlace a esa venta."],
  },
  "page.accounting": {
    title: "contabilidad",
    summary: "Libros, revistas, declaraciones y envejecimiento AR/AP.",
    what: "Herramientas de doble entrada: plan de cuentas, asientos de diario, balance de comprobación, pérdidas y ganancias, balance general, libro mayor y antigüedad de cuentas por cobrar/pagar.",
    how: [
      "Explore los libros mayores en el Plan de cuentas.",
      "Publicar correcciones manuales de los diarios.",
      "Ejecute Saldo de prueba, P&L, Balance general o GL para un rango de fechas.",
      "Seguimiento de facturas vencidas y facturas por antigüedad AR/AP.",
    ],
    when: "Para cierre de mes, informes de propietarios o seguimiento de cobros y pagos.",
    tips: [
      "POS y el inventario crean muchos diarios automáticamente.",
      "Corrija los documentos fuente antes de publicar diarios manuales.",
    ],
  },
  "page.hr": {
    title: "Recursos Humanos y Nómina",
    summary: "Empleados, asistencia, licencias y cálculos de nómina.",
    what: "Gestiona los datos maestros del personal, la asistencia, las solicitudes de licencia y el cálculo y aprobación de la nómina.",
    how: [
      "Agregue empleados o invite a usuarios existentes.",
      "Registre la asistencia y revise las solicitudes de licencia.",
      "Ejecute la nómina por un período y luego apruebe.",
    ],
    when: "Para contratación, asistencia diaria, aprobación de licencias y ciclos salariales.",
    tips: ["La aprobación de la nómina puede requerir un rol o paquete específico."],
  },
  "page.marketing": {
    title: "Comercialización",
    summary: "Campañas, segmentos, cupones y niveles de fidelización.",
    what: "Le ayuda a enviar mensajes a los clientes, apuntar a segmentos, configurar códigos promocionales y configurar tasas de obtención/canje de fidelidad.",
    how: [
      "Crea un borrador de campaña con audiencia y mensaje.",
      "Envíe cuando esté listo: el estado de entrega aparece en la campaña.",
      "Cree segmentos y cupones para ofertas específicas.",
      "Establezca niveles de fidelidad basados en bandas de puntos.",
    ],
    when: "Para promociones, ofertas de festivales, mensajes de recuperación y configuración de fidelización.",
    tips: ["Conecte los canales de los clientes para una mejor entrega."],
  },
  "page.reports": {
    title: "Informes",
    summary: "Ventas operativas y desempeño del producto.",
    what: "Informes de sucursales como ventas diarias y productos principales. Los estados financieros completos se encuentran en Contabilidad.",
    how: [
      "Elija un rango de fechas.",
      "Revise las ventas diarias y el recuento de entradas.",
      "Consulta los productos más vendidos por cantidad.",
    ],
    when: "Para revisiones semanales, decisiones de comercialización o actualizaciones de propietarios.",
    tips: ["Abra Contabilidad para P&L o balance."],
  },
  "page.settings": {
    title: "Configuración",
    summary: "Perfil, límites del plan, facturación, notificaciones, indicadores FBR y roles.",
    what: "Perfil de cuenta para todo el personal, además de configuración empresarial: uso de suscripción, preferencias de notificación, integraciones y acceso a roles (algunas pestañas son solo para propietarios).",
    how: [
      "Actualice su perfil en la pestaña Perfil.",
      "Revise el uso con respecto a los límites del plan.",
      "Los propietarios pueden gestionar integraciones, marcas y roles para la empresa activa.",
    ],
    when: "Durante la incorporación, las actualizaciones del plan o al cambiar el acceso al módulo.",
    tips: ["Algunas configuraciones son solo para el propietario: pregúntele al propietario si falta una pestaña."],
  },
  "page.notifications": {
    title: "Notificaciones",
    summary: "Alertas de bajas, nómina, facturación y campaña.",
    what: "Alertas del sistema y del flujo de trabajo para que no se pierdan las aprobaciones y los resultados de la campaña.",
    how: [
      "Abra Notificaciones para ver elementos no leídos.",
      "Haga clic en una alerta vinculada para ir a la pantalla relacionada.",
      "Ajuste las preferencias en Configuración si las alertas son demasiado ruidosas.",
    ],
    when: "Durante todo el día para aprobaciones y actualizaciones operativas.",
    tips: ["Mantenga el panel abierto en los días de mayor actividad para que las solicitudes de licencia y nómina permanezcan visibles."],
  },
  "page.profile": {
    title: "Tu perfil",
    summary: "Nombre personal, teléfono, contraseña y foto.",
    what: "Actualiza su cuenta de usuario, no la configuración comercial completa.",
    how: [
      "Cambiar nombre para mostrar y teléfono.",
      "Establezca una nueva contraseña sólo cuando necesite cambiarla.",
      "Sube una foto de perfil cuando esté disponible.",
    ],
    when: "Al configurar el primer inicio de sesión o al actualizar datos personales.",
    tips: ["Cambie el idioma desde el control de idioma del perfil o la barra lateral."],
  },
  "page.businesses": {
    title: "Empresas",
    summary: "Lista de propietarios de empresas bajo su cuenta.",
    what: "Cree negocios dentro de los límites del plan y ábralos para la marca, el mercado y las sucursales.",
    how: [
      "Revise la lista de negocios activos.",
      "Crear un nuevo negocio con nombre e industria.",
      "Abra una fila para editar la marca, el mercado y las sucursales.",
    ],
    when: "Al incorporar una nueva tienda o verificar la capacidad del plan.",
    tips: ["Los errores de límite del plan (402) significan que necesita actualizar en Configuración → Suscripciones."],
  },
  "page.businessDetail": {
    title: "Detalle del negocio",
    summary: "Edite una empresa: marca, mercado y sucursales.",
    what: "Herramientas de propietario para una única identidad empresarial y ubicaciones.",
    how: [
      "Actualice el nombre, la industria, el eslogan y el color de la marca.",
      "Cargue un logotipo y configure la lista del mercado.",
      "Agregue o desactive sucursales según sea necesario.",
    ],
    when: "Al lanzar una tienda o renovar la apariencia de la marca.",
    tips: ["La desactivación mantiene los datos financieros históricos; no se elimina de forma definitiva."],
  },
  "page.ess": {
    title: "Herramientas del personal (ESS)",
    summary: "Autoservicio del empleado para asistencia y bajas.",
    what: "El personal puede realizar el registro de entrada/salida y enviar licencias sin acceso completo de administrador de recursos humanos.",
    how: [
      "Marque la asistencia de hoy.",
      "Presentar licencia con fechas y motivo.",
      "Verifique el estado de aprobación después del envío.",
    ],
    when: "Diariamente para el personal que utiliza el autoservicio de RRHH.",
    tips: ["Los gerentes aún aprueban las licencias desde la pestaña Licencia de Recursos Humanos."],
  },

  "tab.inventory.stock": {
    title: "Stock disponible",
    summary: "Cantidad y costo promedio de cada producto en esta sucursal.",
    what: "Vista del saldo de inventario después de compras, ventas, transferencias y ajustes.",
    how: [
      "Busque por SKU o nombre del producto.",
      "Revise la cantidad antes de realizar otro pedido.",
      "Compare con Productos si algo parece estar mal.",
    ],
    when: "Antes de realizar pedidos, realizar inspecciones al azar o investigar la escasez.",
    tips: ["Actualizaciones de costos promedio cuando se reciben los bienes."],
  },
  "tab.inventory.products": {
    title: "Productos",
    summary: "Venta de artículos, servicios, precios y códigos de barras.",
    what: "Cree y edite productos utilizados en POS y seguimiento de existencias.",
    how: [
      "Agregue un producto con SKU, nombre y precio.",
      "Configure un código de barras para escanear al finalizar la compra.",
      "Abra un producto para ver o editar detalles.",
    ],
    when: "Al agregar nuevos artículos o actualizar precios.",
    tips: ["Mantenga los SKU únicos en toda la empresa."],
  },
  "tab.inventory.suppliers": {
    title: "Proveedores",
    summary: "Maestro de proveedores para compras.",
    what: "Contacto del proveedor, condiciones de pago y estado utilizados en las órdenes de compra.",
    how: [
      "Agregue un proveedor con nombre y datos de contacto.",
      "Establezca las condiciones de pago antes de crear una orden de compra.",
      "Abra un proveedor para ver todos los detalles.",
    ],
    when: "Al configurar compras o actualizar los detalles del proveedor.",
    tips: ["No utilice proveedores inactivos en el nuevo POs."],
  },
  "tab.inventory.pos": {
    title: "Órdenes de compra",
    summary: "Pedidos de proveedores y entrada de mercancías (GRN).",
    what: "Cree POs, realice un seguimiento del estado y reciba cantidades en stock.",
    how: [
      "Cree una orden de compra con proveedores y artículos de línea.",
      "Recibir mercancías contra la orden de compra cuando llegue el stock (GRN).",
      "Abra una orden de compra para revisar las líneas y el estado.",
    ],
    when: "Al reordenar stock a un proveedor.",
    tips: ["Reciba solo lo que llegó: se admiten recibos parciales."],
  },
  "tab.inventory.transfers": {
    title: "Transferencias",
    summary: "Mover stock entre sucursales.",
    what: "Crea un documento de transferencia que debe ser confirmado para que el stock pase de una sucursal a otra.",
    how: [
      "Elige sucursal de destino, producto y cantidad.",
      "Cree la transferencia y confirme una vez que se muevan las mercancías.",
    ],
    when: "Al equilibrar el stock entre ubicaciones.",
    tips: ["Confirme con prontitud para que las cantidades disponibles sean precisas."],
  },
  "tab.inventory.adjust": {
    title: "Ajuste de existencias",
    summary: "Cantidad correcta por daños, variación de conteo o cancelaciones.",
    what: "Cantidad de cambios (+/-) con un código de motivo para auditoría.",
    how: [
      "Elija producto y cantidad delta.",
      "Seleccione un código de motivo.",
      "Guárdelo para actualizar el stock disponible.",
    ],
    when: "Después de un recuento físico o cuando la mercancía se daña o se pierde.",
    tips: ["Prefiera GRN/transferencias para movimiento normal; utilice Ajustar para realizar correcciones."],
  },

  "tab.accounting.coa": {
    title: "Plan de cuentas",
    summary: "Cuentas contables para diarios y extractos.",
    what: "Lista de códigos, nombres y tipos de cuentas. Edite los nombres cuando sea necesario.",
    how: ["Busque cuentas por código.", "Edite una cuenta para cambiar su etiqueta."],
    when: "Durante la revisión de la configuración o cuando se necesitan nombres más claros.",
    tips: ["No elimine cuentas que ya tengan publicaciones."],
  },
  "tab.accounting.journals": {
    title: "Revistas",
    summary: "Asientos de diario manuales y del sistema.",
    what: "Muestra diarios publicados y le permite publicar entradas manuales equilibradas.",
    how: [
      "Abra un diario para ver las líneas de débito/crédito.",
      "Utilice Publicar diario para realizar un ajuste de dos líneas cuando sea necesario.",
    ],
    when: "Para correcciones, acumulaciones o revisión de entradas publicadas automáticamente.",
    tips: ["Los débitos deben ser iguales a los créditos antes de su contabilización."],
  },
  "tab.accounting.tb": {
    title: "Saldo de prueba",
    summary: "Totales de débito/crédito por cuenta para un período.",
    what: "Verifica que los libros estén equilibrados antes de ejecutar los extractos.",
    how: ["Establecer fechas desde/hasta.", "Revisar los totales de la cuenta."],
    when: "Al final de mes o antes de P&L / balance.",
    tips: ["Investigue saldos inesperadamente grandes."],
  },
  "tab.accounting.pl": {
    title: "Ganancias y pérdidas",
    summary: "Ingresos y gastos para un rango de fechas.",
    what: "Rentabilidad para el período seleccionado a partir de los diarios publicados.",
    how: ["Elige fechas.", "Lea ingresos versus gastos."],
    when: "Para revisión del propietario y cierre de período.",
    tips: ["La precisión depende de los tipos de cuenta y las publicaciones correctas."],
  },
  "tab.accounting.bs": {
    title: "Balance general",
    summary: "Activos, pasivos y patrimonio.",
    what: "Declaración de posición al final del período seleccionado.",
    how: ["Establezca el rango de fechas del informe.", "Revisar las secciones de activos versus pasivos."],
    when: "Para cierre de período y discusiones financieras.",
    tips: ["La antigüedad de AR/AP complementa los saldos de clientes y proveedores."],
  },
  "tab.accounting.gl": {
    title: "Libro mayor",
    summary: "Actividad línea por línea para una cuenta.",
    what: "Historial de débito/crédito para una sola cuenta.",
    how: ["Seleccione una cuenta.", "Establecer fechas.", "Revisa cada publicación."],
    when: "Al investigar saldos o conciliar una cuenta.",
    tips: ["Primero ejecute el balance de comprobación y luego abra GL para cuentas impares."],
  },
  "tab.accounting.ar": {
    title: "Envejecimiento AR",
    summary: "Cuentas por cobrar de clientes por grupo de edad.",
    what: "Saldos de facturas abiertas agrupados por antigüedad (vigente, 30, 60 días, etc.).",
    how: ["Revisar los cubos.", "Abra una factura para obtener más detalles.", "Seguimiento con el cliente."],
    when: "Para cobranzas y control de crédito.",
    tips: ["Khata/ventas a crédito pueden aparecer en AR."],
  },
  "tab.accounting.ap": {
    title: "Envejecimiento AP",
    summary: "Cuentas por pagar de proveedores por grupo de edad.",
    what: "Facturas que debes, agrupadas por fecha de vencimiento.",
    how: ["Revisar los cubos.", "Abra una factura para obtener más detalles.", "Planificar pagos a proveedores."],
    when: "Para pago de proveedores y planificación de efectivo.",
    tips: ["Los recibos de PO a menudo crean facturas AP."],
  },

  "tab.hr.employees": {
    title: "Empleados",
    summary: "Lista maestra de personal y detalles de empleo.",
    what: "Cree registros de empleados, edite el salario base y abra perfiles.",
    how: [
      "Agregue un empleado o invite a un usuario existente.",
      "Edite el título, el salario y el estado.",
      "Abra un empleado para obtener todos los detalles.",
    ],
    when: "Para contrataciones, cambios de roles o actualizaciones salariales.",
    tips: ["La invitación vincula el registro de recursos humanos para iniciar sesión."],
  },
  "tab.hr.attendance": {
    title: "Asistencia",
    summary: "Historial de check-in/check-out.",
    what: "Filas de asistencia para nómina y cumplimiento.",
    how: ["Filtrar por fecha.", "Corrija los golpes faltantes a través de ESS o un administrador."],
    when: "Para operaciones diarias y antes de nómina.",
    tips: ["La fuente puede ser ESS o la entrada del administrador."],
  },
  "tab.hr.leave": {
    title: "salir",
    summary: "Dejar solicitudes y aprobaciones.",
    what: "Los gerentes aprueban o rechazan las licencias según los permisos de función.",
    how: [
      "Revisar solicitudes pendientes.",
      "Aprobar o rechazar con cuidado.",
      "Confirme las fechas con el empleado si no están claras.",
    ],
    when: "Cuando el personal solicite tiempo libre.",
    tips: ["La aprobación depende del acceso a Leave_approve."],
  },
  "tab.hr.payroll": {
    title: "Nómina",
    summary: "El pago se ejecuta durante un período seleccionado.",
    what: "Genere nómina, vea ejecuciones y apruebe cuando esté autorizado.",
    how: [
      "Establecer el inicio y el final del período.",
      "Ejecutar nómina.",
      "Abra los detalles y apruebe si tiene derechos.",
    ],
    when: "Al cierre del ciclo salarial.",
    tips: ["Solucione problemas de asistencia/licencias antes de ejecutar la nómina."],
  },

  "tab.marketing.campaigns": {
    title: "Campañas",
    summary: "Redactar y enviar mensajes a los clientes.",
    what: "Cree campañas de marketing, elija audiencia y envíelas con un resumen de entrega.",
    how: [
      "Crea un borrador de campaña.",
      "Revisar audiencia y mensaje.",
      "Envíe cuando esté listo y abra los resultados para obtener más detalles.",
    ],
    when: "Para promociones y atención al cliente.",
    tips: ["Los borradores se pueden editar antes de enviarlos."],
  },
  "tab.marketing.segments": {
    title: "Segmentos",
    summary: "Audiencias de clientes guardadas para segmentación.",
    what: "Filtros reutilizables para campañas (p. ej. por fidelización).",
    how: ["Construya un segmento con filtros.", "Reutilícelo al redactar una campaña."],
    when: "Para ofertas específicas en lugar de criticar a todos.",
    tips: ["Mantenga los nombres de los segmentos descriptivos."],
  },
  "tab.marketing.coupons": {
    title: "Cupones",
    summary: "Códigos promocionales para el pago POS.",
    what: "Los códigos de descuento que los cajeros pueden ingresar en el carrito.",
    how: [
      "Crea un código y un valor de descuento.",
      "Compartir con los clientes.",
      "Ingrese el código en POS antes de realizar el pago.",
    ],
    when: "Para campañas de descuentos y ofertas de socios.",
    tips: ["Establezca límites de uso para que los códigos no se canjeen en exceso."],
  },
  "tab.marketing.tiers": {
    title: "Niveles de lealtad",
    summary: "Gane/canjee tarifas por banda de puntos.",
    what: "Configura la rapidez con la que los clientes ganan y canjean puntos.",
    how: [
      "Añade un nivel con puntos mínimos.",
      "Establezca multiplicadores de ganancias/canjeos.",
      "Pruebe con un cliente de muestra.",
    ],
    when: "Al lanzar o afinar la fidelización.",
    tips: ["Los niveles más altos generalmente ganan más rápido; comuníqueselo a los clientes."],
  },

  "tab.settings.notifications": {
    title: "Preferencias de notificación",
    summary: "Elija qué alertas recibir.",
    what: "Por usuario alterna entre los tipos de notificación.",
    how: ["Abra la pestaña Notificaciones en Configuración.", "Active o desactive los tipos según sea necesario."],
    when: "Cuando las alertas son demasiado ruidosas o se pasan por alto elementos importantes.",
    tips: ["Estas preferencias se aplican a su usuario, no a toda la empresa."],
  },
  "tab.settings.profile": {
    title: "Perfil",
    summary: "Tu nombre, teléfono, contraseña, foto e idioma.",
    what: "Configuración de la cuenta del personal compartida por todos los roles, no la marca comercial.",
    how: [
      "Actualice el nombre para mostrar y el teléfono.",
      "Sube una foto de perfil.",
      "Cambie el idioma o establezca una nueva contraseña cuando sea necesario.",
    ],
    when: "Al iniciar sesión por primera vez o cada vez que cambien los datos personales.",
    tips: ["La marca comercial se encuentra en Branding o Businesses, no en Profile."],
  },
  "tab.settings.subscriptions": {
    title: "Suscripción y uso",
    summary: "Estado del plan y límites de asientos/sucursales.",
    what: "Plan actual, estado, uso de empresas/sucursales/usuarios versus límites y pago de actualización de Safepay (JazzCash, Easypaisa o tarjeta).",
    how: [
      "Revisar los contadores de uso.",
      "Elija un plan y pague con JazzCash, Easypaisa o tarjeta para actualizar.",
    ],
    when: "Al acercarse a límites o en renovación de facturación.",
    tips: ["Se requiere acceso de propietario para esta pestaña."],
  },
  "tab.settings.integrations": {
    title: "Integraciones",
    summary: "Conexiones externas y banderas de cumplimiento.",
    what: "Herramientas de propietario para conectar servicios para la empresa (por ejemplo, banderas FBR).",
    how: ["Revise la configuración de integración disponible.", "Cambie las banderas sólo cuando comprenda el impacto."],
    when: "Al configurar integraciones o cumplimiento.",
    tips: ["Las marcas incorrectas pueden afectar la declaración de impuestos; confírmela con su contador."],
  },
  "tab.settings.roles": {
    title: "Roles",
    summary: "Quién puede acceder a qué módulos.",
    what: "Configuración del propietario del acceso basado en roles en paquetes Kaarobar.",
    how: ["Revisar las asignaciones de roles.", "Cambie con cuidado: el personal puede perder el acceso."],
    when: "Al contratar, promocionar o reforzar la seguridad.",
    tips: ["Mínimo privilegio: otorga a cada rol solo los paquetes que necesita."],
  },
  "tab.settings.branding": {
    title: "Marca de la tienda",
    summary: "Logotipo, colores y listado del mercado para su negocio.",
    what: "Controla el aspecto de tu tienda en Descubrir/catálogo y reasigna el esquema de interfaz de usuario en la aplicación (botones, anillos de enfoque, navegación) desde el color primario.",
    how: [
      "Cargue un logotipo y elija un color de marca principal.",
      "Agregue un eslogan y una descripción del mercado.",
      "Guarde la marca y luego obtenga una vista previa de Descubrir o comprar como consumidor.",
    ],
    when: "Antes de lanzarse al mercado o de renovar la apariencia de la marca.",
    tips: ["Se requiere acceso de propietario. Al guardar la marca, se actualiza el tema del espacio de trabajo del personal de inmediato."],
  },
  "tab.marketing.templates": {
    title: "Plantillas de mensajes",
    summary: "Cuerpos de mensajes de CRM reutilizables con variables.",
    what: "Plantillas guardadas para campañas y vistas previas (nombre comercial, eslogan, etc.).",
    how: [
      "Cree o edite una plantilla con marcadores de posición.",
      "Vista previa con variables comerciales de muestra.",
      "Seleccione la plantilla al redactar una campaña.",
    ],
    when: "Al estandarizar mensajes promocionales o transaccionales.",
    tips: ["Mantenga las plantillas breves para los canales de SMS/WhatsApp."],
  },

  "page.market.discover": {
    title: "Descubre tiendas",
    summary: "Explore las empresas del mercado e inicie un pedido de recogida.",
    what: "Enumera las empresas Kaarobar que publican un escaparate de mercado con marca.",
    how: [
      "Busque por nombre o filtre por chips de industria.",
      "Abra una tienda para explorar su catálogo.",
      "Añade artículos de una o más tiendas a tu carrito.",
    ],
    when: "Siempre que desee realizar un pedido para recogerlo en una tienda incluida en la lista.",
    tips: ["Las tiendas aparecen después de que el propietario habilita el mercado y la marca."],
  },
  "page.market.products": {
    title: "All products",
    summary: "Cross-store product feed from marketplace businesses.",
    what: "Shows sellable products from every marketplace-enabled store. Search and filter, then open a product for details or the store catalog.",
    how: [
      "Search by name or filter by category/industry.",
      "Open a product card for detail, price, and add to cart.",
      "Use Visit store / back links to shop the full catalog.",
    ],
    when: "When you want to find an item without browsing stores one by one.",
    tips: ["If the feed is empty, catalogs may not be published yet—try Discover."],
  },
  "page.market.productDetail": {
    title: "Product detail",
    summary: "One product from a marketplace store.",
    what: "Shows image, price, description, and quantity controls. Adds the line to that store’s cart bag.",
    how: [
      "Adjust quantity and tap Add to cart.",
      "Open the store link to keep shopping.",
      "Checkout from the sticky cart when ready.",
    ],
    when: "After tapping a product from Products or a store grid.",
    tips: ["Sign in as a consumer before adding to cart."],
  },
  "page.market.catalog": {
    title: "Catálogo de tienda",
    summary: "Productos de una tienda del mercado.",
    what: "Cuadrícula de productos de marca para una sola empresa: filtre por categoría, búsqueda y precio, luego agréguelos al carrito.",
    how: [
      "Toca Comprar cuando la tienda también ofrezca reservas.",
      "Utilice filtros para limitar el catálogo.",
      "Toque Agregar para colocar artículos en su carrito (se permiten carritos de varias tiendas).",
      "Abra Ver carrito o el carrito de la barra de navegación para realizar el pago.",
    ],
    when: "Mientras compra en una tienda específica para recogerlo.",
    tips: ["Cada tienda guarda su propia bolsa en el carrito hasta que realizas el pedido."],
  },
  "page.market.book": {
    title: "Reserva un servicio",
    summary: "Reserva directamente una cita en un negocio de servicios.",
    what: "Elige un servicio, opcionalmente un profesional concreto y un horario disponible; después, confirma la reserva. Utiliza las API de citas del portal (CUS-FR-005).",
    how: [
      "Abre Reservar en un salón o negocio con citas habilitadas.",
      "Elige un servicio y luego Cualquier profesional o una persona concreta.",
      "Selecciona una fecha y un horario libre, añade notas opcionales y confirma.",
      "Encuentre la reserva en Pedidos → Citas.",
    ],
    when: "Cuando quieras programar una visita en vez de pedir productos.",
    tips: ["Inicia sesión con una cuenta de cliente antes de reservar."],
  },
  "tab.market.shop": {
    title: "Pestaña de tienda",
    summary: "Solicite productos para recoger.",
    what: "Muestra productos vendibles del catálogo de esta tienda.",
    how: ["Explorar o buscar productos.", "Añadir al carrito y pagar."],
    when: "Tiendas híbridas que venden productos y aceptan citas.",
  },
  "tab.market.book": {
    title: "Pestaña Reservar",
    summary: "Reserva una cita para un servicio.",
    what: "Flujo de reserva: servicio → profesional → horario → confirmación.",
    how: ["Selecciona un servicio.", "Elige un profesional o Cualquiera disponible.", "Confirma la hora."],
    when: "En negocios con citas habilitadas y productos de tipo servicio.",
  },
  "page.checkout.review": {
    title: "Revisar carrito",
    summary: "Edite las cantidades antes del pago.",
    what: "Muestra cada bolsa de la tienda en su carrito con artículos en línea, subtotales y un total general.",
    how: [
      "Ajusta cantidades o elimina líneas por tienda.",
      "Limpia la bolsa de una tienda o sigue comprando en esa tienda.",
      "Continuar contactando y pagando.",
    ],
    when: "Después de agregar productos y antes de realizar pedidos para recoger.",
    tips: ["El carrito vacío lo regresa a Discover."],
  },
  "page.checkout.pay": {
    title: "Contacto y pago",
    summary: "Recoger datos de contacto y realizar pedidos.",
    what: "Recopila el nombre, el teléfono y las notas de recogida y luego realiza un pedido por tienda con la misma información de contacto.",
    how: [
      "Confirme o edite el nombre y el teléfono del contacto.",
      "Agregue notas de recogida opcionales.",
      "Elija tarjeta o billetera (talón) y realice el pedido.",
    ],
    when: "Paso final antes de que los pedidos aparezcan en Órdenes.",
    tips: ["El pago en varias tiendas crea facturas separadas por negocio."],
  },
  "page.buyer.orders": {
    title: "Pedidos y reservas",
    summary: "Sus pedidos y citas para recoger en el mercado.",
    what: "Enumera los pedidos en línea que realizó y las citas próximas o pasadas en todas las tiendas. Cancelar citas reservadas desde la pestaña Citas.",
    how: [
      "Órdenes abiertas desde la navegación del mercado.",
      "Utilice la pestaña Pedidos para facturas de recogida; Citas para reservas.",
      "Toque un pedido para ver artículos, pagos y estado.",
      "Cancele una cita reservada si necesita reprogramarla más tarde.",
    ],
    when: "Para realizar un seguimiento de visitas realizadas → confirmadas → listas → completadas o próximas.",
    tips: ["Comuníquese con la tienda si cambia el horario de recogida o cita."],
  },
  "tab.buyer.orders": {
    title: "Pestaña de pedidos",
    summary: "Historial de pedidos de recogida.",
    what: "Pedidos del mercado en línea con estado y nombre de la tienda.",
    how: ["Toque un pedido para líneas de pedido y totales."],
    when: "Después de realizar un pedido de recogida.",
  },
  "tab.buyer.appointments": {
    title: "Pestaña de citas",
    summary: "Reservas próximas y pasadas.",
    what: "Citas de servicio que usted reservó en las tiendas del mercado.",
    how: ["Revisar próximas visitas.", "Cancelar citas reservadas cuando sea necesario."],
    when: "Después de reservar una visita al salón o servicio.",
  },
  "page.buyer.orderDetail": {
    title: "Detalle del pedido",
    summary: "Artículos en línea y totales para una orden de recogida.",
    what: "Muestra el número de factura, tienda, estado, cada línea, impuesto/descuento y métodos de pago.",
    how: ["Abrir desde el historial de pedidos.", "Revise los artículos antes de recogerlos."],
    when: "Después de realizar un pedido o al comprobar la preparación para la recogida.",
    tips: ["Las actualizaciones de estado aparecen aquí a medida que la tienda avanza con su pedido."],
  },
  "page.buyer.loyalty": {
    title: "Lealtad",
    summary: "Puntos y niveles en las tiendas en las que compras.",
    what: "Muestra saldos de fidelidad y tasas de ganancia/canje por negocio vinculado. Toca una tienda para obtener detalles sobre las tarifas.",
    how: ["Abra Loyalty desde la navegación del mercado.", "Toque una tarjeta para obtener detalles sobre cómo ganar/canjear."],
    when: "Antes de canjear o comprobar recompensas.",
    tips: ["Las tarifas provienen de la configuración de fidelización de cada empresa."],
  },
  "page.buyer.ar": {
    title: "Saldo (khata)",
    summary: "Saldos pendientes con tiendas.",
    what: "Vista del consumidor de saldos AR/khata y facturas abiertas. Toque una factura para revisarla y pagarla.",
    how: ["Abrir saldo desde la navegación del mercado.", "Toque una factura para la fecha de vencimiento y pague."],
    when: "Al liquidar el crédito de la tienda o comprobar las cuotas.",
    tips: ["Los perfiles de clientes vinculados sincronizan la identidad de su cuenta de consumidor."],
  },
  "page.buyer.account": {
    title: "Account",
    summary: "Your marketplace profile hub.",
    what: "Shortcuts to Balance/khata, Loyalty, and Alerts, plus sign-out.",
    how: [
      "Open Account from the marketplace nav.",
      "Jump to Balance, Loyalty, or Alerts.",
      "Sign out when finished on a shared device.",
    ],
    when: "To manage profile-linked marketplace tools.",
    tips: ["The header avatar also opens Account."],
  },
  "page.buyer.appointmentDetail": {
    title: "Appointment detail",
    summary: "One marketplace booking.",
    what: "Shows service, store, time, staff, notes, and status. Cancel Booked appointments here.",
    how: [
      "Open from Orders → Appointments.",
      "Review time and staff.",
      "Cancel if status is Booked.",
    ],
    when: "Before a visit or when you need to cancel.",
    tips: ["Contact the store if you need to reschedule outside cancel rules."],
  },
  "page.buyer.notifications": {
    title: "Alertas del mercado",
    summary: "Solicite actualizaciones y mensajes de las tiendas.",
    what: "Notificaciones dentro de la aplicación para su cuenta de consumidor (estado del pedido, mensajes de la tienda).",
    how: ["Abra Alertas/Notificaciones.", "Marque los elementos leídos mientras los revisa."],
    when: "Después de realizar pedidos o cuando las tiendas te envíen un mensaje.",
    tips: ["Las preferencias de notificación del personal no se aplican a las alertas al consumidor."],
  },
  "page.appointments": {
    title: "Citas",
    summary: "Agenda diaria del personal para reservas de servicios.",
    what: "Muestra las citas de la fecha seleccionada y, opcionalmente, de un profesional. Permite completar o cancelar reservas; al completarlas se puede preparar una venta POS vinculada (SCH-FR-005).",
    how: [
      "Elige una fecha y, si lo necesitas, filtra por profesional.",
      "Busca o filtra por estado.",
      "Pulsa Completar para finalizar una visita o Cancelar en las citas reservadas.",
    ],
    when: "Durante la jornada en salones y otros negocios con citas habilitadas.",
    tips: ["Los clientes reservan desde Reservar en el marketplace; el personal gestiona aquí la agenda del día."],
  },
};

export default catalog;
