import type { HelpCatalog } from "./types";

const catalog: HelpCatalog = {
  "page.dashboard": {
    title: "Tableau de bord",
    summary: "KPIs et graphiques de ventes interactifs filtrés par période.",
    what: "Affiche les ventes du jour, la trésorerie, les stocks bas, les validations en attente et les tendances CA/commandes pour une période choisie.",
    how: [
      "Après connexion, consultez les cartes KPI du jour.",
      "Définissez les dates de/à pour actualiser les graphiques.",
      "Survolez un point pour le total journalier ou le nombre de tickets.",
      "Utilisez les cartes stock bas ou validations pour aller vers Inventaire ou Retours.",
      "Changez d'entreprise ou de succursale dans l'en-tête si besoin.",
    ],
    when: "Au début du quart de travail, à la fin de la journée ou chaque fois que vous avez besoin d’un bilan de santé en agence.",
    tips: [
      "Les graphiques utilisent les ventes terminées de l'entreprise sélectionnée (RPT-FR-001).",
      "Graphiques vides : élargissez la période ou vérifiez l'activité de caisse.",
    ],
  },
  "page.pos": {
    title: "Point de vente",
    summary: "Paiement rapide avec panier, client et paiement.",
    what: "Les caissiers peuvent vendre des produits, fidéliser les clients ou crédit (crédit), appliquer des remises ou des coupons et accepter les paiements en espèces, par carte, par portefeuille ou par crédit.",
    how: [
      "Ouvrez une caisse avant d'effectuer des ventes au comptant.",
      "Ajoutez des produits au panier par recherche ou numérisation de codes-barres.",
      "Attachez un client en cas de besoin pour la fidélité ou crédit.",
      "Vérifiez le total, appuyez sur Passer à la caisse et choisissez un mode de paiement.",
      "Complétez la commande avec Passer la commande, puis imprimez ou partagez le reçu.",
    ],
    when: "Pour chaque paiement client au comptoir.",
    tips: [
      "Le paiement Crédit nécessite un crédit actif sur le client.",
      "Gardez la caisse ouverte pendant le quart de travail et comptez les espèces avant de fermer en fin de journée.",
    ],
  },
  "page.inventory": {
    title: "Inventaire et achats",
    summary: "Catalogue, stock disponible, fournisseurs, bons de commande, transferts et ajustements.",
    what: "L'endroit où gérer les produits, consulter les niveaux de stock, acheter auprès des fournisseurs, déplacer les stocks entre les succursales et corriger les quantités.",
    how: [
      "Créez ou mettez à jour les SKU et les prix à partir des produits.",
      "Affichez la quantité disponible et le coût moyen du stock.",
      "Ajoutez des fournisseurs, puis créez des bons de commande et recevez des marchandises (GRN).",
      "Utilisez les transferts pour déplacer le stock entre les succursales et Ajuster pour fixer les quantités.",
    ],
    when: "Lors de la réception de marchandises, de l'ajout de nouveaux articles, d'un inventaire ou d'un transfert entre succursales.",
    tips: [
      "Recevez contre un bon de commande afin que les coûts et les comptes créditeurs restent exacts.",
      "Utilisez un code motif clair dans Adjust pour les pistes d’audit.",
    ],
  },
  "page.customers": {
    title: "Clients et Crédit",
    summary: "Profils clients, crédit/solde crédit, grand livre et points de fidélité.",
    what: "Stocke les détails du client et vous permet d'activer crédit, d'afficher le grand livre, de gérer les limites de crédit et d'ajuster les points de fidélité.",
    how: [
      "Ajoutez un client avec son nom et son téléphone.",
      "Activez crédit pour les ventes à crédit.",
      "Ouvrez Ledger pour voir les débits, les crédits et le solde impayé.",
      "Ajustez les points de fidélité pour les promotions ou les corrections.",
    ],
    when: "Pour les programmes CRM, de vente à crédit et de fidélité.",
    tips: [
      "Attachez le client à POS avant le paiement crédit.",
      "Vérifiez la limite de crédit avant les ventes crédit importantes.",
    ],
  },
  "page.sales": {
    title: "Historique des ventes",
    summary: "Liste complète des factures de ventes de la succursale sélectionnée.",
    what: "Affiche les paiements passés avec le numéro de facture, le client, le total, le statut et l'heure afin que vous puissiez rouvrir ou vérifier une vente.",
    how: [
      "Recherchez ou parcourez la liste des ventes.",
      "Ouvrez une ligne pour afficher les éléments de campagne et les paiements.",
      "Utilisez le numéro de facture lors du traitement d'un retour.",
    ],
    when: "Pour les demandes des clients, les audits, la réimpression des reçus ou avant un retour.",
    tips: ["Les ventes apparaissent après un paiement POS réussi."],
  },
  "page.returns": {
    title: "Retours et caisses",
    summary: "Remboursements sur les ventes passées et jusqu’à l’historique d’ouverture/fermeture.",
    what: "Le personnel peut rechercher une vente et soumettre un retour, et consulter les sessions de caisse, y compris les montants excédentaires/courts.",
    how: [
      "Recherchez par le numéro de facture de vente originale.",
      "Soumettez le retour avec la méthode de remboursement et le motif.",
      "Les gestionnaires approuvent ou rejettent les retours en attente.",
      "Examinez la trésorerie d'ouverture/de clôture et les écarts dans l'historique de la caisse.",
    ],
    when: "Lors de l'émission de remboursements, de la manipulation de marchandises endommagées ou du rapprochement des caisses.",
    tips: ["Conservez la facture originale : les retours renvoient à cette vente."],
  },
  "page.accounting": {
    title: "Comptabilité",
    summary: "Livres, revues, déclarations et vieillissement AR/AP.",
    what: "Outils en partie double : plan comptable, écritures de journal, balance de vérification, profits et pertes, bilan, grand livre et ancienneté des créances/dettes.",
    how: [
      "Parcourez les grands livres dans le plan comptable.",
      "Publier des corrections manuelles à partir des journaux.",
      "Exécutez la Balance de vérification, le P&L, le Bilan ou le GL pour une plage de dates.",
      "Effectuer le suivi des factures en souffrance et des factures dues au vieillissement AR/AP.",
    ],
    when: "Pour la clôture de fin de mois, le reporting des propriétaires ou le suivi des encaissements et des paiements.",
    tips: [
      "POS et l'inventaire créent automatiquement de nombreux journaux.",
      "Corrigez les documents sources avant de valider les journaux manuels.",
    ],
  },
  "page.hr": {
    title: "RH et Paie",
    summary: "Exécutions des employés, des présences, des congés et de la paie.",
    what: "Gère les données de base du personnel, les présences, les demandes de congés, ainsi que le calcul et l'approbation de la paie.",
    how: [
      "Ajoutez des employés ou invitez des utilisateurs existants.",
      "Enregistrer les présences et examiner les demandes de congés.",
      "Exécutez la paie pour une période, puis approuvez-la.",
    ],
    when: "Pour l'embauche, la présence quotidienne, l'approbation des congés et les cycles de salaire.",
    tips: ["L’approbation de la paie peut nécessiter un rôle ou un ensemble spécifique."],
  },
  "page.marketing": {
    title: "Commercialisation",
    summary: "Campagnes, segments, coupons et niveaux de fidélité.",
    what: "Vous aide à envoyer des messages aux clients, à cibler des segments, à configurer des codes promotionnels et à configurer les taux de fidélité/d'échange.",
    how: [
      "Créez un brouillon de campagne avec une audience et un message.",
      "Envoyer lorsque vous êtes prêt : le statut de livraison apparaît sur la campagne.",
      "Créez des segments et des coupons pour des offres ciblées.",
      "Définissez des niveaux de fidélité en fonction de tranches de points.",
    ],
    when: "Pour les promotions, les offres de festival, les messages de reconquête et la configuration de la fidélité.",
    tips: ["Connectez les canaux clients pour une meilleure livraison."],
  },
  "page.reports": {
    title: "Rapports",
    summary: "Ventes opérationnelles et performance produits.",
    what: "Rapports de succursale tels que les ventes quotidiennes et les meilleurs produits. Les états financiers complets sont disponibles sous Comptabilité.",
    how: [
      "Choisissez une plage de dates.",
      "Passez en revue les ventes quotidiennes et le nombre de billets.",
      "Vérifiez les produits les plus vendus par quantité.",
    ],
    when: "Pour les revues hebdomadaires, les décisions de marchandisage ou les mises à jour des propriétaires.",
    tips: ["Comptabilité ouverte pour le P&L ou le bilan."],
  },
  "page.settings": {
    title: "Paramètres",
    summary: "Profil, limites du forfait, facturation, notifications, indicateurs FBR et rôles.",
    what: "Profil de compte pour tout le personnel, plus configuration de l'entreprise : utilisation de l'abonnement, préférences de notification, intégrations et accès aux rôles (certains onglets sont réservés au propriétaire).",
    how: [
      "Mettez à jour votre profil sous l'onglet Profil.",
      "Examinez l’utilisation par rapport aux limites du forfait.",
      "Les propriétaires peuvent gérer les intégrations, la marque et les rôles pour l'entreprise active.",
    ],
    when: "Lors de l'intégration, planifiez des mises à niveau ou lors de la modification de l'accès au module.",
    tips: ["Certains paramètres sont réservés au propriétaire : demandez au propriétaire s'il manque un onglet."],
  },
  "page.notifications": {
    title: "Notifications",
    summary: "Alertes de congés, de paie, de facturation et de campagne.",
    what: "Alertes du système et du flux de travail pour que les approbations et les résultats de la campagne ne soient pas manqués.",
    how: [
      "Ouvrez les notifications pour voir les éléments non lus.",
      "Cliquez sur une alerte liée pour accéder à l'écran associé.",
      "Ajustez les préférences dans Paramètres si les alertes sont trop bruyantes.",
    ],
    when: "Tout au long de la journée pour les approbations et les mises à jour opérationnelles.",
    tips: ["Gardez le panneau ouvert les jours de pointe afin que les demandes de congés et de paie restent visibles."],
  },
  "page.profile": {
    title: "Votre profil",
    summary: "Nom personnel, téléphone, mot de passe et photo.",
    what: "Met à jour votre compte utilisateur, et non les paramètres professionnels complets.",
    how: [
      "Changez le nom d’affichage et le téléphone.",
      "Définissez un nouveau mot de passe uniquement lorsque vous devez le modifier.",
      "Téléchargez une photo de profil lorsqu’elle est disponible.",
    ],
    when: "Lors de la première configuration de connexion ou lors de la mise à jour des informations personnelles.",
    tips: ["Changez la langue à partir du contrôle de langue du profil ou de la barre latérale."],
  },
  "page.businesses": {
    title: "Entreprises",
    summary: "Liste des propriétaires des entreprises sous votre compte.",
    what: "Créez des entreprises dans les limites du plan et ouvrez chacune d'elles à la marque, au marché et aux succursales.",
    how: [
      "Consultez la liste des entreprises actives.",
      "Créez une nouvelle entreprise avec un nom et un secteur d'activité.",
      "Ouvrez une ligne pour modifier la marque, la place de marché et les succursales.",
    ],
    when: "Lors de l’intégration d’un nouveau magasin ou de la vérification de la capacité du plan.",
    tips: ["Les erreurs de limite de forfait (402) signifient que vous devez effectuer une mise à niveau sous Paramètres → Abonnements."],
  },
  "page.businessDetail": {
    title: "Détail de l'entreprise",
    summary: "Modifiez une entreprise : image de marque, place de marché et succursales.",
    what: "Outils propriétaires pour une identité commerciale et des emplacements uniques.",
    how: [
      "Mettez à jour le nom, le secteur d’activité, le slogan et la couleur de la marque.",
      "Téléchargez un logo et configurez la liste du marché.",
      "Ajoutez ou désactivez des branches selon vos besoins.",
    ],
    when: "Lors du lancement d’un magasin ou du rafraîchissement du look de la marque.",
    tips: ["La désactivation conserve les données financières historiques ; il n'y a pas de suppression définitive."],
  },
  "page.ess": {
    title: "Outils du personnel (ESS)",
    summary: "Libre-service des employés pour les présences et les congés.",
    what: "Le personnel peut s'enregistrer/départ et soumettre des congés sans accès complet à l'administrateur RH.",
    how: [
      "Notez la présence d'aujourd'hui.",
      "Soumettez le congé avec les dates et le motif.",
      "Vérifiez le statut d'approbation après la soumission.",
    ],
    when: "Quotidien pour le personnel utilisant les RH en libre-service.",
    tips: ["Les managers approuvent toujours les congés à partir de l'onglet Congés RH."],
  },

  "tab.inventory.stock": {
    title: "Stock disponible",
    summary: "Quantité et coût moyen pour chaque produit dans cette succursale.",
    what: "Vue du solde des stocks après achats, ventes, transferts et ajustements.",
    how: [
      "Recherchez par SKU ou par nom de produit.",
      "Vérifiez la quantité avant de commander à nouveau.",
      "Comparez avec les produits si quelque chose ne va pas.",
    ],
    when: "Avant de passer des commandes, des contrôles ponctuels ou d’enquêter sur des pénuries.",
    tips: ["Le coût moyen est mis à jour lorsque les marchandises sont reçues."],
  },
  "tab.inventory.products": {
    title: "Produits",
    summary: "Articles en vente, services, prix et codes-barres.",
    what: "Créez et modifiez les produits utilisés dans POS et le suivi des stocks.",
    how: [
      "Ajoutez un produit avec SKU, nom et prix.",
      "Définissez un code-barres à numériser à la caisse.",
      "Ouvrez un produit pour afficher ou modifier les détails.",
    ],
    when: "Lors de l'ajout de nouveaux articles ou de la mise à jour des prix.",
    tips: ["Gardez les SKU uniques dans toute l’entreprise."],
  },
  "tab.inventory.suppliers": {
    title: "Fournisseurs",
    summary: "Maître des fournisseurs pour les achats.",
    what: "Contact du fournisseur, conditions de paiement et statut utilisés sur les bons de commande.",
    how: [
      "Ajoutez un fournisseur avec son nom et ses coordonnées.",
      "Définissez les conditions de paiement avant de créer un bon de commande.",
      "Ouvrez un fournisseur pour afficher tous les détails.",
    ],
    when: "Lors de la configuration des achats ou de la mise à jour des détails du fournisseur.",
    tips: ["N'utilisez pas de fournisseurs inactifs sur le nouveau POs."],
  },
  "tab.inventory.pos": {
    title: "Bons de commande",
    summary: "Commandes fournisseurs et entrée de marchandises (GRN).",
    what: "Créez POs, suivez le statut et recevez les quantités en stock.",
    how: [
      "Créez un bon de commande avec un fournisseur et des éléments de campagne.",
      "Réceptionner les marchandises contre le bon de commande à l'arrivée du stock (GRN).",
      "Ouvrez un bon de commande pour consulter les lignes et le statut.",
    ],
    when: "Lors d’une commande de stock auprès d’un fournisseur.",
    tips: ["Recevez uniquement ce qui est arrivé : les reçus partiels sont pris en charge."],
  },
  "tab.inventory.transfers": {
    title: "Transferts",
    summary: "Déplacez le stock entre les succursales.",
    what: "Crée un document de transfert qui doit être confirmé pour que le stock passe d'une succursale à une autre.",
    how: [
      "Choisissez la succursale de destination, le produit et la quantité.",
      "Créez le transfert et confirmez une fois les marchandises déplacées.",
    ],
    when: "Lors de l’équilibrage des stocks entre les sites.",
    tips: ["Confirmez rapidement afin que les quantités disponibles restent exactes."],
  },
  "tab.inventory.adjust": {
    title: "Ajustement des stocks",
    summary: "Corrigez la quantité pour les dommages, les écarts de comptage ou les radiations.",
    what: "Modifie la quantité (+/−) avec un code motif pour audit.",
    how: [
      "Choisissez le produit et le delta de quantité.",
      "Sélectionnez un code motif.",
      "Enregistrez pour mettre à jour le stock disponible.",
    ],
    when: "Après un comptage physique ou lorsque des marchandises sont endommagées ou perdues.",
    tips: ["Préférez GRN/transferts pour un mouvement normal ; utilisez Ajuster pour les corrections."],
  },

  "tab.accounting.coa": {
    title: "Plan comptable",
    summary: "Comptes généraux pour les journaux et les relevés.",
    what: "Liste des codes de compte, des noms et des types. Modifiez les noms si nécessaire.",
    how: ["Parcourez les comptes par code.", "Modifiez un compte pour changer son étiquette."],
    when: "Lors de la révision de la configuration ou lorsque des noms plus clairs sont nécessaires.",
    tips: ["Ne supprimez pas les comptes qui ont déjà des publications."],
  },
  "tab.accounting.journals": {
    title: "Journaux",
    summary: "Écritures de journal manuelles et système.",
    what: "Affiche les journaux publiés et vous permet de publier des écritures manuelles équilibrées.",
    how: [
      "Ouvrez un journal pour afficher les lignes de débit/crédit.",
      "Utilisez le journal de publication pour un ajustement sur deux lignes si nécessaire.",
    ],
    when: "Pour les corrections, les régularisations ou la révision des entrées publiées automatiquement.",
    tips: ["Les débits doivent être égaux aux crédits avant la comptabilisation."],
  },
  "tab.accounting.tb": {
    title: "Balance de vérification",
    summary: "Totaux de débit/crédit par compte pour une période.",
    what: "Vérifie que les livres sont équilibrés avant d’exécuter des relevés.",
    how: ["Définissez les dates du/au.", "Vérifiez les totaux du compte."],
    when: "En fin de mois ou avant P&L/bilan.",
    tips: ["Enquêtez sur des soldes étonnamment importants."],
  },
  "tab.accounting.pl": {
    title: "Profits et pertes",
    summary: "Revenus et dépenses pour une plage de dates.",
    what: "Rentabilité pour la période sélectionnée à partir des journaux validés.",
    how: ["Choisissez des dates.", "Lisez les revenus par rapport aux dépenses."],
    when: "Pour examen par le propriétaire et clôture de la période.",
    tips: ["La précision dépend des types de comptes et des publications corrects."],
  },
  "tab.accounting.bs": {
    title: "Bilan",
    summary: "Actif, passif et capitaux propres.",
    what: "Prise de position à la fin de la période sélectionnée.",
    how: ["Définissez la plage de dates du rapport.", "Examinez les sections actif/passif."],
    when: "Pour la clôture de la période et les discussions financières.",
    tips: ["Le vieillissement AR/AP complète les soldes clients et fournisseurs."],
  },
  "tab.accounting.gl": {
    title: "Grand livre général",
    summary: "Activité ligne par ligne pour un compte.",
    what: "Historique de débit/crédit pour un seul compte.",
    how: ["Sélectionnez un compte.", "Fixez des dates.", "Examinez chaque publication."],
    when: "Lors de l’enquête sur les soldes ou du rapprochement d’un compte.",
    tips: ["Exécutez d'abord la balance de vérification, puis ouvrez GL pour les comptes impairs."],
  },
  "tab.accounting.ar": {
    title: "Vieillissement de la RA",
    summary: "Créances clients par tranche d’âge.",
    what: "Soldes de factures ouvertes regroupés par âge (actuel, 30, 60 jours, etc.).",
    how: ["Examinez les compartiments.", "Ouvrez une facture pour plus de détails.", "Effectuer le suivi auprès du client."],
    when: "Pour les recouvrements et le contrôle du crédit.",
    tips: ["Les ventes Crédit/à crédit peuvent apparaître dans AR."],
  },
  "tab.accounting.ap": {
    title: "Vieillissement AP",
    summary: "Dettes fournisseurs par tranche d’âge.",
    what: "Factures que vous devez, regroupées par date d'échéance.",
    how: ["Examinez les compartiments.", "Ouvrez une facture pour plus de détails.", "Planifier les paiements des fournisseurs."],
    when: "Pour le paiement des fournisseurs et la planification de la trésorerie.",
    tips: ["Les reçus de bon de commande créent souvent des factures AP."],
  },

  "tab.hr.employees": {
    title: "Employés",
    summary: "Liste principale du personnel et détails de l'emploi.",
    what: "Créez des dossiers d'employés, modifiez le salaire de base et ouvrez des profils.",
    how: [
      "Ajoutez un employé ou invitez un utilisateur existant.",
      "Modifiez le titre, le salaire et le statut.",
      "Ouvrez un employé pour plus de détails.",
    ],
    when: "Pour l'embauche, les changements de rôle ou les mises à jour de salaire.",
    tips: ["L'invitation relie l'enregistrement RH à l'accès à la connexion."],
  },
  "tab.hr.attendance": {
    title: "Participation",
    summary: "Historique d’arrivée/départ.",
    what: "Lignes de présence pour la paie et la conformité.",
    how: ["Filtrer par date.", "Corrigez les poinçons manquants via ESS ou un manager."],
    when: "Pour les opérations quotidiennes et avant la paie.",
    tips: ["La source peut être ESS ou une entrée du gestionnaire."],
  },
  "tab.hr.leave": {
    title: "Partir",
    summary: "Laissez les demandes et les approbations.",
    what: "Les responsables approuvent ou rejettent les congés en fonction des autorisations des rôles.",
    how: [
      "Examinez les demandes en attente.",
      "Approuvez ou rejetez soigneusement.",
      "Confirmez les dates avec l'employé si elles ne sont pas claires.",
    ],
    when: "Lorsque le personnel demande un congé.",
    tips: ["L’approbation dépend de l’accès Leave_approve."],
  },
  "tab.hr.payroll": {
    title: "Paie",
    summary: "La paie s'exécute pour une période sélectionnée.",
    what: "Générez la paie, consultez les exécutions et approuvez lorsque cela est autorisé.",
    how: [
      "Définir le début et la fin de la période.",
      "Exécutez la paie.",
      "Ouvrez les détails et approuvez si vous avez des droits.",
    ],
    when: "À la clôture du cycle salarial.",
    tips: ["Résolvez les problèmes de présence/congés avant d’exécuter la paie."],
  },

  "page.marketing.template": {
    title: "Modèle de message",
    summary: "Aperçu de l’apparence d’un modèle CRM pour les clients.",
    what: "Affiche les variables brutes et un aperçu interpolé avec la marque et des valeurs d’exemple.",
    how: [
      "Ouvrez un modèle dans Marketing → Modèles.",
      "Vérifiez les variables dans l’aperçu.",
      "Contrôlez l’aperçu client.",
      "Retour rouvre l’onglet Modèles.",
    ],
    when: "Lors de la rédaction de messages de campagne réutilisables.",
    tips: ["Les variables sont des clés plates comme {{business}} — {{customer.name}} n’est pas pris en charge."],
  },

  "tab.marketing.campaigns": {
    title: "Campagnes",
    summary: "Rédiger et envoyer des messages clients.",
    what: "Créez des campagnes marketing, choisissez votre audience et envoyez-les avec un récapitulatif de livraison.",
    how: [
      "Créez un brouillon de campagne.",
      "Examinez l’audience et le message.",
      "Envoyez lorsque vous êtes prêt et ouvrez les résultats pour plus de détails.",
    ],
    when: "Pour les promotions et la sensibilisation des clients.",
    tips: ["Les brouillons peuvent être modifiés avant l’envoi."],
  },
  "tab.marketing.segments": {
    title: "Segments",
    summary: "Audiences de clients enregistrées pour le ciblage.",
    what: "Filtres réutilisables pour les campagnes (par exemple par fidélité).",
    how: ["Créez un segment avec des filtres.", "Réutilisez-le lors de la composition d’une campagne."],
    when: "Pour des offres ciblées au lieu de faire exploser tout le monde.",
    tips: ["Gardez les noms de segments descriptifs."],
  },
  "tab.marketing.coupons": {
    title: "Coupons",
    summary: "Codes promotionnels pour le paiement POS.",
    what: "Les caissiers peuvent saisir des codes de réduction dans le panier.",
    how: [
      "Créez un code et une valeur de réduction.",
      "Partagez avec les clients.",
      "Entrez le code sur POS avant de procéder au paiement.",
    ],
    when: "Pour les campagnes de réduction et les offres partenaires.",
    tips: ["Définissez des limites d'utilisation afin que les codes ne soient pas utilisés de manière excessive."],
  },
  "tab.marketing.tiers": {
    title: "Niveaux de fidélité",
    summary: "Gagnez/échangez des taux par tranche de points.",
    what: "Configure la rapidité avec laquelle les clients gagnent et échangent des points.",
    how: [
      "Ajoutez un niveau avec un minimum de points.",
      "Définissez des multiplicateurs de gain/échange.",
      "Testez avec un échantillon de client.",
    ],
    when: "Lors du lancement ou du réglage de la fidélité.",
    tips: ["Les niveaux supérieurs gagnent généralement plus rapidement : communiquez-le aux clients."],
  },

  "tab.settings.notifications": {
    title: "Préférences de notifications",
    summary: "Choisissez les alertes que vous recevez.",
    what: "Bascule par utilisateur pour les types de notification.",
    how: ["Ouvrez l'onglet Notifications dans Paramètres.", "Activez ou désactivez les types selon vos besoins."],
    when: "Lorsque les alertes sont trop bruyantes ou que des éléments importants sont manqués.",
    tips: ["Ces préférences s'appliquent à votre utilisateur, et non à l'ensemble de l'entreprise."],
  },
  "tab.settings.profile": {
    title: "Profil",
    summary: "Votre nom, téléphone, mot de passe, photo et langue.",
    what: "Paramètres du compte du personnel partagés par tous les rôles, et non par l'image de marque de l'entreprise.",
    how: [
      "Mettez à jour le nom d’affichage et le téléphone.",
      "Téléchargez une photo de profil.",
      "Changez de langue ou définissez un nouveau mot de passe si nécessaire.",
    ],
    when: "Lors de la première connexion ou chaque fois que les données personnelles changent.",
    tips: ["L'image de marque de l'entreprise se trouve sous l'image de marque ou les entreprises, et non sous le profil."],
  },
  "tab.settings.subscriptions": {
    title: "Abonnement et utilisation",
    summary: "Statut du plan et limites de sièges/succursales.",
    what: "Forfait actuel, statut, utilisation des entreprises/succursales/utilisateurs par rapport aux limites et paiement de mise à niveau Safepay (JazzCash, Easypaisa ou carte).",
    how: [
      "Examinez les compteurs d’utilisation.",
      "Choisissez un forfait et payez avec JazzCash, Easypaisa ou une carte pour mettre à niveau.",
    ],
    when: "À l’approche des limites ou au renouvellement de la facturation.",
    tips: ["L'accès propriétaire est requis pour cet onglet."],
  },
  "tab.settings.integrations": {
    title: "Intégrations",
    summary: "Connexions externes et indicateurs de conformité.",
    what: "Outils propriétaires pour connecter les services pour l'entreprise (par exemple, les indicateurs FBR).",
    how: ["Vérifiez les paramètres d’intégration disponibles.", "Changez les drapeaux uniquement lorsque vous comprenez l’impact."],
    when: "Lors de la mise en place d’intégrations ou de conformité.",
    tips: ["Des indicateurs erronés peuvent affecter la déclaration fiscale : confirmez auprès de votre comptable."],
  },
  "tab.settings.roles": {
    title: "Rôles",
    summary: "Qui peut accéder à quels modules.",
    what: "Configuration propriétaire de l'accès basé sur les rôles sur les bundles Kaarobar.",
    how: ["Passez en revue les attributions de rôles.", "Changez-le avec précaution : le personnel pourrait perdre l’accès."],
    when: "Lors de l’embauche, de la promotion ou du renforcement de la sécurité.",
    tips: ["Moindre privilège : accordez à chaque rôle uniquement les bundles dont il a besoin."],
  },
  "tab.settings.branding": {
    title: "Image de marque du magasin",
    summary: "Logo, couleurs et liste de places de marché pour votre entreprise.",
    what: "Contrôle l'apparence de votre boutique dans Discover/catalogue et remappe le schéma d'interface utilisateur de l'application (boutons, bagues de mise au point, navigation) à partir de la couleur primaire.",
    how: [
      "Téléchargez un logo et choisissez une couleur principale de marque.",
      "Ajoutez un slogan et une description du marché.",
      "Enregistrez la marque, puis prévisualisez Discover ou achetez en tant que consommateur.",
    ],
    when: "Avant d'être mis en ligne sur le marché ou de rafraîchir le look de la marque.",
    tips: ["L'accès du propriétaire est requis. L’enregistrement de la marque met immédiatement à jour le thème de l’espace de travail du personnel."],
  },
  "tab.marketing.templates": {
    title: "Modèles de messages",
    summary: "Corps de message CRM réutilisables avec variables.",
    what: "Modèles enregistrés pour les campagnes et les aperçus (nom de l'entreprise, slogan, etc.).",
    how: [
      "Créez ou modifiez un modèle avec des espaces réservés.",
      "Aperçu avec des exemples de variables métier.",
      "Sélectionnez le modèle lors de la composition d'une campagne.",
    ],
    when: "Lors de la standardisation des messages promotionnels ou transactionnels.",
    tips: ["Gardez les modèles courts pour les canaux SMS/WhatsApp."],
  },

  "page.market.discover": {
    title: "Découvrez les magasins",
    summary: "Parcourez les entreprises du marché et lancez une commande de ramassage.",
    what: "Répertorie les entreprises Kaarobar qui publient une vitrine Marketplace avec une image de marque.",
    how: [
      "Recherchez par nom ou filtrez par puces industrielles.",
      "Ouvrez une boutique pour parcourir son catalogue.",
      "Ajoutez des articles d'un ou plusieurs magasins à votre panier.",
    ],
    when: "Chaque fois que vous souhaitez commander un retrait dans un magasin répertorié.",
    tips: ["Les magasins apparaissent une fois que le propriétaire a activé le marché et l'image de marque."],
  },
  "page.market.products": {
    title: "All products",
    summary: "Cross-store product feed from marketplace businesses.",
    what: "Shows sellable products from every marketplace-enabled store. Search and filter, then open a product for details or the store catalog.",
    how: [
      "Search by name or filter by category/industry.",
      "Open a product card for detail, price, and add to cart.",
      "Use Visit store / back links to shop the full catalog.",
    ],
    when: "When you want to find an item without browsing stores one by one.",
    tips: ["If the feed is empty, catalogs may not be published yet—try Discover."],
  },
  "page.market.productDetail": {
    title: "Product detail",
    summary: "One product from a marketplace store.",
    what: "Shows image, price, description, and quantity controls. Adds the line to that store’s cart bag.",
    how: [
      "Adjust quantity and tap Add to cart.",
      "Open the store link to keep shopping.",
      "Checkout from the sticky cart when ready.",
    ],
    when: "After tapping a product from Products or a store grid.",
    tips: ["Sign in as a consumer before adding to cart."],
  },
  "page.market.catalog": {
    title: "Catalogue du magasin",
    summary: "Produits d'un magasin du marché.",
    what: "Grille de produits de marque pour une seule entreprise : filtrez par catégorie, recherche et prix, puis ajoutez-la au panier.",
    how: [
      "Appuyez sur Acheter lorsque le magasin propose également la réservation.",
      "Utilisez des filtres pour affiner le catalogue.",
      "Appuyez sur Ajouter pour mettre des articles dans votre panier (les paniers multi-magasins sont autorisés).",
      "Ouvrez Afficher le panier ou le panier de la barre de navigation pour passer à la caisse.",
    ],
    when: "Lors de vos achats dans un magasin spécifique pour le retrait.",
    tips: ["Chaque magasin conserve son propre sac dans le panier jusqu'à ce que vous passiez commande."],
  },
  "page.market.book": {
    title: "Réserver une prestation",
    summary: "Réservez directement un rendez-vous auprès d’un établissement de services.",
    what: "Choisissez une prestation, éventuellement un professionnel précis, puis un créneau disponible et confirmez. Utilise les API de rendez-vous du portail (CUS-FR-005).",
    how: [
      "Ouvrez Réserver dans un salon ou un établissement où les rendez-vous sont activés.",
      "Choisissez une prestation, puis N’importe quel professionnel ou une personne précise.",
      "Choisissez une date et un créneau libre, ajoutez éventuellement des notes, puis confirmez.",
      "Retrouvez la réservation sous Commandes → Rendez-vous.",
    ],
    when: "Lorsque vous souhaitez planifier une visite plutôt que commander des produits.",
    tips: ["Connectez-vous avec un compte client avant de réserver."],
  },
  "tab.market.shop": {
    title: "Onglet Boutique",
    summary: "Commandez des produits à emporter.",
    what: "Affiche les produits vendables du catalogue de ce magasin.",
    how: ["Parcourez ou recherchez des produits.", "Ajouter au panier et payer."],
    when: "Magasins hybrides qui vendent des biens et prennent rendez-vous.",
  },
  "tab.market.book": {
    title: "Onglet Réserver",
    summary: "Réservez un rendez-vous pour une prestation.",
    what: "Parcours de réservation : prestation → professionnel → créneau → confirmation.",
    how: ["Sélectionnez une prestation.", "Choisissez un professionnel ou N’importe lequel.", "Confirmez l’heure."],
    when: "Dans les établissements proposant des prestations et ayant activé les rendez-vous.",
  },
  "page.checkout.review": {
    title: "Panier d'évaluation",
    summary: "Modifiez les quantités avant le paiement.",
    what: "Affiche chaque sac de magasin dans votre panier avec les éléments de campagne, les sous-totaux et un total général.",
    how: [
      "Ajustez les quantités ou supprimez des lignes par magasin.",
      "Videz un sac de magasin ou continuez à magasiner dans ce magasin.",
      "Continuez à contacter et à payer.",
    ],
    when: "Après avoir ajouté des produits et avant de passer des commandes à emporter.",
    tips: ["Le panier vide vous renvoie à Discover."],
  },
  "page.checkout.pay": {
    title: "Contact & paiement",
    summary: "Récupérez vos coordonnées et passez vos commandes.",
    what: "Recueille les noms, les numéros de téléphone et les notes de ramassage, puis passe une commande par magasin avec les mêmes coordonnées.",
    how: [
      "Confirmez ou modifiez le nom et le téléphone du contact.",
      "Ajoutez des notes de ramassage facultatives.",
      "Choisissez une carte ou un portefeuille (stub) et passez une ou plusieurs commandes.",
    ],
    when: "Dernière étape avant que les commandes n'apparaissent sous Commandes.",
    tips: ["Le paiement multi-magasins crée des factures distinctes par entreprise."],
  },
  "page.buyer.orders": {
    title: "Commandes et réservations",
    summary: "Vos commandes et rendez-vous de retrait sur la Marketplace.",
    what: "Répertorie les commandes en ligne que vous avez passées et les rendez-vous à venir/passés dans les magasins. Annulez les rendez-vous réservés à partir de l’onglet Rendez-vous.",
    how: [
      "Ouvrez les commandes à partir de la navigation du marché.",
      "Utilisez l'onglet Commandes pour les factures de ramassage ; Rendez-vous pour réservations.",
      "Appuyez sur une commande pour voir les articles, les paiements et le statut.",
      "Annulez un rendez-vous réservé si vous devez le reprogrammer plus tard.",
    ],
    when: "Pour suivre les visites placées → confirmées → prêtes → terminées ou à venir.",
    tips: ["Contactez le magasin si l'heure de ramassage ou de rendez-vous change."],
  },
  "tab.buyer.orders": {
    title: "Onglet Commandes",
    summary: "Historique des commandes de ramassage.",
    what: "Commandes du marché en ligne avec statut et nom du magasin.",
    how: ["Appuyez sur une commande pour les éléments de campagne et les totaux."],
    when: "Après avoir passé une commande de ramassage.",
  },
  "tab.buyer.appointments": {
    title: "Onglet Rendez-vous",
    summary: "Réservations à venir et passées.",
    what: "Rendez-vous de service que vous avez réservés dans les magasins Marketplace.",
    how: ["Passez en revue les visites à venir.", "Annulez les rendez-vous réservés en cas de besoin."],
    when: "Après avoir réservé une visite de salon ou de service.",
  },
  "page.buyer.orderDetail": {
    title: "Détail de la commande",
    summary: "Éléments de campagne et totaux pour une commande de retrait.",
    what: "Affiche le numéro de facture, le magasin, le statut, chaque ligne, les taxes/remises et les modes de paiement.",
    how: ["Ouvrir à partir de l'historique des commandes.", "Examinez les articles avant de les récupérer."],
    when: "Après avoir passé une commande ou lors de la vérification de l'état de préparation au retrait.",
    tips: ["Les mises à jour de statut apparaissent ici au fur et à mesure que le magasin progresse dans votre commande."],
  },
  "page.buyer.loyalty": {
    title: "Fidélité",
    summary: "Points et niveaux dans les magasins dans lesquels vous magasinez.",
    what: "Affiche les soldes de fidélité et les taux de gain/échange par entreprise liée. Appuyez sur un magasin pour obtenir des détails sur les tarifs.",
    how: ["Ouvrez Loyalty à partir de la navigation du marché.", "Appuyez sur une carte pour obtenir/échanger des détails."],
    when: "Avant d'échanger ou de vérifier les récompenses.",
    tips: ["Les tarifs proviennent des paramètres de fidélité de chaque entreprise."],
  },
  "page.buyer.ar": {
    title: "Solde (crédit)",
    summary: "Soldes impayés auprès des magasins.",
    what: "Vue consommateur des soldes AR / crédit et des factures ouvertes. Appuyez sur une facture pour la consulter et la payer.",
    how: ["Ouvrez le solde depuis la navigation du marché.", "Appuyez sur une facture pour connaître la date d'échéance et payez."],
    when: "Lors du règlement du crédit du magasin ou de la vérification des cotisations.",
    tips: ["Les profils clients liés synchronisent l’identité de votre compte consommateur."],
  },
  "page.buyer.account": {
    title: "Account",
    summary: "Your marketplace profile hub.",
    what: "Shortcuts to Balance/crédit, Loyalty, and Alerts, plus sign-out.",
    how: [
      "Open Account from the marketplace nav.",
      "Jump to Balance, Loyalty, or Alerts.",
      "Sign out when finished on a shared device.",
    ],
    when: "To manage profile-linked marketplace tools.",
    tips: ["The header avatar also opens Account."],
  },
  "page.buyer.appointmentDetail": {
    title: "Appointment detail",
    summary: "One marketplace booking.",
    what: "Shows service, store, time, staff, notes, and status. Cancel Booked appointments here.",
    how: [
      "Open from Orders → Appointments.",
      "Review time and staff.",
      "Cancel if status is Booked.",
    ],
    when: "Before a visit or when you need to cancel.",
    tips: ["Contact the store if you need to reschedule outside cancel rules."],
  },
  "page.buyer.notifications": {
    title: "Alertes du marché",
    summary: "Commandez des mises à jour et des messages dans les magasins.",
    what: "Notifications dans l'application pour votre compte consommateur (état de la commande, messages du magasin).",
    how: ["Ouvrez Alertes/Notifications.", "Marquez les éléments comme lus au fur et à mesure que vous les examinez."],
    when: "Après avoir passé des commandes ou lorsque les magasins vous envoient un message.",
    tips: ["Les préférences de notification du personnel ne s’appliquent pas aux alertes aux consommateurs."],
  },
  "page.appointments": {
    title: "Rendez-vous",
    summary: "Planning quotidien du personnel pour les prestations réservées.",
    what: "Affiche les rendez-vous de la date sélectionnée et, si besoin, d’un professionnel précis. Les réservations peuvent être terminées ou annulées ; leur achèvement peut préparer une vente POS liée (SCH-FR-005).",
    how: [
      "Choisissez une date et filtrez éventuellement par professionnel.",
      "Recherchez ou filtrez par statut.",
      "Appuyez sur Terminer pour clôturer une visite, ou sur Annuler pour un rendez-vous réservé.",
    ],
    when: "Pendant la journée de service dans les salons et autres établissements où les rendez-vous sont activés.",
    tips: ["Les clients réservent via Réserver sur la place de marché ; le personnel gère ici le planning du jour."],
  },
};

export default catalog;
